-- ═══════════════════════════════════════════════════════════════════════════
-- vendor_devices — one row per signed-in astrologer DEVICE
--
-- WHY THIS EXISTS
-- `astrologers.fcm_token` is a single column and `logged_out_at` a single
-- timestamp, so both describe an ACCOUNT while the events they record are
-- per-DEVICE. Measured 2026-09-09: an astrologer signed in and online on an
-- iPhone was marked signed-out — and had their push token wiped — because they
-- logged out of the Android app afterwards. Their own screen said "You are
-- Online" with every service toggle green, so there was no way for them to tell
-- customers could not see them, and the only symptom was silence.
--
-- Signing out on one device must not sign out another.
--
-- ┌──────────────────────────────────────────────────────────────────────────┐
-- │ COMPATIBILITY IS THE WHOLE RISK HERE, so read this before changing the   │
-- │ reachability rule.                                                       │
-- │                                                                          │
-- │ Installed vendor builds do not send a device_id and never will — only a  │
-- │ new release does. So the legacy columns STAY authoritative for any        │
-- │ astrologer with no device rows:                                          │
-- │                                                                          │
-- │     isLoggedOut = (device rows exist) ? false : !!logged_out_at           │
-- │                                                                          │
-- │ A device row PROVES signed-in. The absence of rows proves nothing, and    │
-- │ must fall back rather than hide someone. Any rule that treats "no rows"   │
-- │ as signed-out makes every astrologer on an old build vanish the moment    │
-- │ this deploys.                                                            │
-- └──────────────────────────────────────────────────────────────────────────┘
--
-- Idempotent. Safe to re-run. NO explicit BEGIN/COMMIT — free_call_booking_pool.sql
-- wrapped its statements in a transaction and its DROP INDEX silently did not take
-- effect, leaving a half-applied schema that threw no runtime error. Ends with a
-- self-verifying DO block for the same reason.
-- ═══════════════════════════════════════════════════════════════════════════

CREATE TABLE IF NOT EXISTS public.vendor_devices (
  id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  astrologer_id  uuid NOT NULL REFERENCES public.astrologers(id) ON DELETE CASCADE,

  -- Generated by the app and persisted in its own storage. Deliberately NOT the
  -- FCM token: those rotate on reinstall, restore and Firebase's own refresh, so
  -- keying identity on one means a device can fail to recognise itself and then
  -- cannot sign itself out. A device_id survives token rotation.
  device_id      text NOT NULL,

  fcm_token      text,
  -- iOS PushKit token — a DIFFERENT token from fcm_token, and the only thing that
  -- can ring a killed iOS app. See src/voipPush.js.
  voip_token     text,
  platform       text CHECK (platform IN ('ios', 'android', 'unknown')),
  app_version    text,

  -- Refreshed on login and on token refresh. Used to pick the newest device to
  -- ring, and to reap devices that were uninstalled without signing out — those
  -- would otherwise leave an astrologer looking permanently reachable, the same
  -- zombie shape chat_sessions already has with is_active/next_billing_at.
  last_seen_at   timestamptz NOT NULL DEFAULT now(),
  created_at     timestamptz NOT NULL DEFAULT now()
);

-- One row per device per astrologer. An upsert on login therefore updates the
-- existing row rather than accumulating one per sign-in.
CREATE UNIQUE INDEX IF NOT EXISTS vendor_devices_astro_device_uniq
  ON public.vendor_devices (astrologer_id, device_id);

-- "Newest device for this astrologer" — the ring target, and the reachability
-- existence check.
CREATE INDEX IF NOT EXISTS vendor_devices_astro_seen_idx
  ON public.vendor_devices (astrologer_id, last_seen_at DESC);

-- ── Seed from the current state ──────────────────────────────────────────────
-- Every astrologer who is signed in TODAY (has a push token and is not marked
-- signed out) gets a 'legacy' device, so nobody's reachability changes on the
-- day this is applied. Their real device_id replaces this row the next time they
-- sign in on an updated build.
--
-- Astrologers with no token are deliberately NOT seeded: they get no row, the
-- fallback above keeps reading logged_out_at for them, and they are unaffected.
INSERT INTO public.vendor_devices (astrologer_id, device_id, fcm_token, voip_token, platform)
SELECT a.id, 'legacy', a.fcm_token, a.voip_token, 'unknown'
  FROM public.astrologers a
 WHERE a.fcm_token IS NOT NULL
   AND a.logged_out_at IS NULL
ON CONFLICT (astrologer_id, device_id) DO NOTHING;

-- ── Access control ───────────────────────────────────────────────────────────
-- Service-role only. These rows carry push tokens, which are credentials for
-- reaching a person's phone; the publishable key shipped in both APKs must never
-- read or write them. RLS on with zero policies denies every non-service role.
ALTER TABLE public.vendor_devices ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.vendor_devices FROM anon, authenticated;

-- ── Self-verifying tail ──────────────────────────────────────────────────────
DO $$
DECLARE
  v_seeded int;
  v_policies int;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM information_schema.tables
                  WHERE table_schema = 'public' AND table_name = 'vendor_devices') THEN
    RAISE EXCEPTION 'vendor_devices: table is missing';
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_indexes
                  WHERE schemaname = 'public'
                    AND indexname = 'vendor_devices_astro_device_uniq') THEN
    RAISE EXCEPTION 'vendor_devices: the (astrologer_id, device_id) unique index is missing — logins would accumulate a row per sign-in';
  END IF;

  IF NOT EXISTS (SELECT 1 FROM pg_indexes
                  WHERE schemaname = 'public'
                    AND indexname = 'vendor_devices_astro_seen_idx') THEN
    RAISE EXCEPTION 'vendor_devices: the (astrologer_id, last_seen_at) index is missing';
  END IF;

  SELECT count(*) INTO v_policies FROM pg_policies
   WHERE schemaname = 'public' AND tablename = 'vendor_devices';
  IF v_policies <> 0 THEN
    RAISE EXCEPTION 'vendor_devices: expected NO policies (service-role only), found %', v_policies;
  END IF;

  SELECT count(*) INTO v_seeded FROM public.vendor_devices WHERE device_id = 'legacy';
  RAISE NOTICE 'vendor_devices: OK. % astrologer(s) seeded as legacy devices.', v_seeded;
END $$;

-- Expect one row per currently-signed-in astrologer.
SELECT count(*) AS legacy_devices_seeded
  FROM public.vendor_devices WHERE device_id = 'legacy';
