// English ⇄ Hindi switching for the paid astrology reports.
//
// The app already had a global language toggle (routes/CustomHeader.js) but it only ever
// swapped the app's OWN labels. A report is mostly the PROVIDER's text — predictions,
// remedies, dosha explanations — so flipping the UI to Hindi left the substance in English
// and the screen read as half-translated.
//
// JyotishamAstroAPI takes a `lang` param and returns the whole payload in Hindi (verified
// live 2026-08-16), so a real switch means re-fetching the report. That raises the obvious
// question — does the customer pay twice? No:
//
//   * `astroRoutes.js` builds its wallet idempotency key from the request body with `lang`
//     REMOVED, so the same report in the other language hashes identically and the atomic
//     debit dedupes it to zero.
//   * It also checks `wallet_transactions` for that key BEFORE the balance gate, so a
//     customer whose balance has since dropped below the price can still switch language.
//
// The upstream call is still spent, which is the intended trade: they paid for the content
// once and are entitled to read it in either language.
import React, {useCallback, useContext, useEffect, useRef, useState} from 'react';
import {
  View, Text, StyleSheet, TouchableOpacity, ActivityIndicator, Animated, Easing,
} from 'react-native';
import {LanguageContext} from '../../context/LanguageContext';
import {runAstroReport} from '../../api/astroApi';
import {showStatusPopup} from '../../components/StatusPopup';
import {moderateScale, scale, verticalScale} from '../../utils/Scaling';
import {ASTRO} from './AstroUI';

// The app stores its language as 'English' | 'Hindi'; the API wants 'en' | 'hi'.
export const apiLang = (language) => (language === 'Hindi' ? 'hi' : 'en');

/**
 * Owns the report payload and swaps it when the language changes.
 *
 * Screens receive `{data, payload, serviceKey}` from their input screen and render
 * `data` from this hook instead of straight off route.params, so a switch re-renders
 * every card with the translated payload.
 *
 * Falls back to the payload already on screen if a re-fetch fails — a network blip must
 * never blank out a report the customer has paid for.
 */
export function useReportLanguage(route, navigation) {
  const {language, changeLanguage, t} = useContext(LanguageContext);
  const params = route?.params || {};
  const {payload, serviceKey} = params;

  const [data, setData] = useState(params.data);
  const [busy, setBusy] = useState(false);
  // Which language the payload currently on screen was fetched in. The report was
  // generated by the input screen using whatever the app language was at that moment.
  const loadedLang = useRef(params.lang || apiLang(language));
  // Keeps both translations once fetched, so flipping back and forth is instant and
  // spends no further upstream calls.
  const cache = useRef({[loadedLang.current]: params.data});

  const canSwitch = !!(payload && serviceKey);

  // LanguageProvider builds `t` and `changeLanguage` inline, so both are NEW FUNCTIONS on
  // every provider render. Listing them in the useCallback deps below would give `switchTo`
  // a new identity every render, which would re-run the navigation.setOptions effect, which
  // re-renders the screen — a loop. Reading them through a ref keeps `switchTo` stable while
  // still always calling the current versions.
  const ctxRef = useRef({t, changeLanguage});
  ctxRef.current = {t, changeLanguage};

  const switchTo = useCallback(async (nextAppLang) => {
    const next = apiLang(nextAppLang);
    ctxRef.current.changeLanguage(nextAppLang);
    if (!canSwitch || next === loadedLang.current) return;

    if (cache.current[next]) {
      loadedLang.current = next;
      setData(cache.current[next]);
      return;
    }

    setBusy(true);
    try {
      const fresh = await runAstroReport(serviceKey, {...payload, lang: next});
      if (fresh) {
        cache.current[next] = fresh;
        loadedLang.current = next;
        setData(fresh);
      }
    } catch (err) {
      // Keep showing what we have; say why the text did not change.
      showStatusPopup({
        variant: 'info',
        title: ctxRef.current.t('common.error'),
        message: err?.message || ctxRef.current.t('report.langSwitchFailed'),
      });
    } finally {
      setBusy(false);
    }
  }, [canSwitch, payload, serviceKey]);

  // Mount the toggle into the navigation header rather than drawing a control inside the
  // scroll view — the user asked for it in the top bar's right corner, and a header button
  // also stays put while the report scrolls.
  useEffect(() => {
    if (!navigation?.setOptions) return;
    navigation.setOptions({
      headerRight: () => (
        <ReportLanguageToggle
          language={language}
          busy={busy}
          disabled={!canSwitch}
          onSwitch={switchTo}
        />
      ),
    });
  }, [navigation, language, busy, canSwitch, switchTo]);

  return {data, busy, language, switchTo, canSwitch};
}

/**
 * Header toggle for the FREE (₹1) service screens.
 *
 * Much simpler than the paid-report version: the free endpoints all take a
 * `?language=` param and cost nothing to re-request (the ₹1 charge is a separate
 * `/api/free-services/charge` call made once when the card is tapped, not per
 * fetch), so there is no wallet bookkeeping to do. Flipping the app language is
 * enough — each screen re-fetches because its effect depends on `language`.
 *
 * Returns the current language so callers can thread it into their request.
 */
export function useFreeServiceLanguage(navigation) {
  const {language, changeLanguage} = useContext(LanguageContext);

  // Same ref trick as above: LanguageProvider rebuilds changeLanguage inline on
  // every render, so depending on it directly would re-run setOptions forever.
  const changeRef = useRef(changeLanguage);
  changeRef.current = changeLanguage;

  const switchTo = useCallback((next) => changeRef.current(next), []);

  useEffect(() => {
    if (!navigation?.setOptions) return;
    navigation.setOptions({
      headerRight: () => (
        <ReportLanguageToggle language={language} busy={false} onSwitch={switchTo} />
      ),
    });
  }, [navigation, language, switchTo]);

  // 'en' | 'hi' — what the free-services endpoints expect as ?language=
  return {language, apiLanguage: apiLang(language)};
}

/**
 * The EN | हिं pill for the navigation header's right side.
 *
 * Deliberately a segmented control rather than a single toggle button: with one button a
 * reader cannot tell whether the label names the current language or the one they will get
 * by tapping. Here the active half is filled in, so the state is unambiguous.
 */
export function ReportLanguageToggle({language, busy, onSwitch, disabled}) {
  const active = language === 'Hindi' ? 'Hindi' : 'English';
  const slide = useRef(new Animated.Value(active === 'Hindi' ? 1 : 0)).current;

  const go = (lang) => {
    if (busy || disabled || lang === active) return;
    Animated.timing(slide, {
      toValue: lang === 'Hindi' ? 1 : 0,
      duration: 220,
      easing: Easing.out(Easing.cubic),
      useNativeDriver: true,
    }).start();
    onSwitch(lang);
  };

  const half = scale(30);
  const knobX = slide.interpolate({inputRange: [0, 1], outputRange: [0, half]});

  return (
    <View style={styles.wrap}>
      {busy && <ActivityIndicator size="small" color="#fff" style={styles.spinner} />}
      <View style={[styles.track, disabled && styles.trackDisabled]}>
        <Animated.View
          style={[styles.knob, {width: half, transform: [{translateX: knobX}]}]}
        />
        <TouchableOpacity style={[styles.half, {width: half}]} onPress={() => go('English')} activeOpacity={0.8}>
          <Text style={[styles.label, active === 'English' && styles.labelActive]}>EN</Text>
        </TouchableOpacity>
        <TouchableOpacity style={[styles.half, {width: half}]} onPress={() => go('Hindi')} activeOpacity={0.8}>
          <Text style={[styles.label, active === 'Hindi' && styles.labelActive]}>हिं</Text>
        </TouchableOpacity>
      </View>
    </View>
  );
}

/**
 * Full-screen veil while a translation is in flight. The re-fetch hits five upstream
 * endpoints, so it is not instant — without this the screen would just sit there and a
 * reader would tap the toggle again.
 */
export function TranslatingOverlay({visible, label}) {
  if (!visible) return null;
  return (
    <View style={styles.overlay} pointerEvents="auto">
      <View style={styles.overlayCard}>
        <ActivityIndicator size="large" color={ASTRO.maroon} />
        <Text style={styles.overlayText}>{label}</Text>
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  wrap: {flexDirection: 'row', alignItems: 'center', marginRight: scale(10)},
  spinner: {marginRight: scale(7)},
  track: {
    flexDirection: 'row',
    backgroundColor: 'rgba(255,255,255,0.18)',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.35)',
    padding: 2,
  },
  trackDisabled: {opacity: 0.45},
  knob: {
    position: 'absolute',
    top: 2,
    left: 2,
    bottom: 2,
    borderRadius: 20,
    backgroundColor: '#fff',
  },
  half: {paddingVertical: verticalScale(3), alignItems: 'center', justifyContent: 'center'},
  label: {fontSize: moderateScale(11), fontFamily: 'Lato-Bold', color: 'rgba(255,255,255,0.85)'},
  labelActive: {color: ASTRO.maroon},

  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(46,27,18,0.35)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  overlayCard: {
    backgroundColor: '#FFF8EF',
    borderRadius: moderateScale(14),
    paddingVertical: verticalScale(20),
    paddingHorizontal: scale(28),
    alignItems: 'center',
  },
  overlayText: {
    marginTop: verticalScale(10),
    fontSize: moderateScale(13),
    fontFamily: 'Lato-Bold',
    color: ASTRO.maroon,
  },
});
