// Hindi/English toggle for the vendor app — mirrors astrowani_customer-main's
// LanguageContext.js pattern (namespaced keys, AsyncStorage-persisted choice, t() lookup
// with English fallback). Astrologers skew heavily towards Hindi, so this exists to let
// them use the app in their preferred language.
//
// COVERAGE NOTE: this is a real, working toggle (drawer footer buttons + the header
// language icon on Home, both call changeLanguage()), and translation coverage covers
// the drawer menu and the HomeScreen dashboard (online/offline, service toggles, go
// live, profile-completion banner, session history button) — not every screen in the
// app yet. Extend `translations` below with more namespaced keys (e.g. 'wallet.balance')
// and wrap the corresponding strings in t('...') as more screens are covered; the
// switching mechanism itself doesn't need to change.
import React, { createContext, useState, useEffect } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

// NOTE: the context itself is created *below* `translations`, because its default
// value needs to read from it. See the comment there.

const translations = {
  English: {
    'drawer.dashboard': 'Dashboard',
    'drawer.myCustomers': 'My Customers',
    'drawer.profile': 'Profile',
    'drawer.sessionHistory': 'Session History',
    'drawer.missedSessions': 'Missed Sessions',
    'drawer.support': 'Support',
    'drawer.notification': 'Notification',
    'drawer.settings': 'Settings',
    'drawer.ratingReview': 'Rating & Review',
    'drawer.performance': 'Performance',
    'drawer.wallet': 'Wallet',
    'drawer.logout': 'Logout',
    'drawer.followUs': 'Follow Us',
    'drawer.language': 'Language',

    'home.youAreOnline': 'You are Online',
    'home.youAreOffline': 'You are Offline',
    'home.goLive': 'GO LIVE',
    'home.endLive': 'END LIVE',
    'home.sessionHistory': 'Session History',
    'home.chat': 'Chat',
    'home.call': 'Call',
    'home.video': 'Video',
    'home.todayEarnings': "Today's Earnings",
    'home.totalEarnings': 'Total Earnings',
    'home.walletBalance': 'Wallet Balance',
    'home.youAreOnlineSub': 'Customers can reach you for chat, call & video',
    'home.youAreOfflineSub': "You're hidden from new requests everywhere",
    'home.serviceSettings': 'Service Settings',
    'home.completeProfile': 'Complete your profile',
    'home.completeProfileSub': 'Add your photo, experience, languages and charges so customers can find you. Tap to finish.',
    'home.pendingApproval': 'We will review your profile and get back to you soon!',
    'home.suspended': 'Your account is suspended',
    'vsupport.title': 'Support',
    'vsupport.sessionExpired': 'Your session has expired. Please log out and log in again, then come back here.',
    'vsupport.offline': "We couldn't reach the server. Please check your connection.",
    'vsupport.tapToRetry': 'Type your message below and I will try again.',
    'vsupport.statusAssistant': 'Support assistant',
    'vsupport.statusTyping': 'typing...',
    'vsupport.statusConnecting': 'Connecting you to the team...',
    'vsupport.statusTeam': 'Support team',
    'vsupport.statusWithAgent': '{{name}} from support',
    'vsupport.statusResolved': 'Resolved',
    'vsupport.talkToPerson': 'Talk to a person',
    'vsupport.fromAgent': '{{name}} from the support team',
    'vsupport.fromTeam': 'Support team',
    'vsupport.messagePlaceholder': 'Describe your issue...',
    'vsupport.sendFailed': "That message didn't send. Please check your connection and try again.",
    'vsupport.couldNotOpen': 'We could not open support just now. Please try again in a moment.',
    'vsupport.notReady': 'Support chat is being set up. Please try again shortly.',
    'vsupport.quickHint': 'Or start with one of these:',
    'vsupport.quick.payout': 'My withdrawal has not reached my bank yet',
    'vsupport.quick.requests': 'I am not receiving call or chat requests',
    'vsupport.quick.profile': 'A question about my profile or approval',
    'vsupport.quick.charges': 'I want to change my per-minute charges',
    'home.suspendedSub': 'Customers cannot see or reach you right now. Tap to contact support.',
    'home.sessionHistoryBtn': 'Session History',

    'common.ok': 'OK',
    'common.cancel': 'Cancel',
    'common.save': 'Save',
    'common.accept': 'Accept',
    'common.reject': 'Reject',
    'common.perMin': '/min',
    'common.submit': 'Submit',
    'common.customer': 'Customer',
    'common.notAvailable': 'Not available',
    'common.notSpecified': 'Not specified',

    'popup.incomingCall': 'Incoming Call',
    'popup.incomingVideoCall': 'Incoming Video Call',
    'popup.requesting': 'is requesting a consultation...',
    'popup.moreWaiting': 'more waiting',
    'popup.decline': 'Decline',

    'sessionHistory.chat': 'Chat',
    'sessionHistory.audioCall': 'Audio Call',
    'sessionHistory.videoCall': 'Video Call',
    'sessionHistory.live': 'Live',
    'sessionHistory.active': 'Active',
    'sessionHistory.completed': 'Completed',
    'sessionHistory.duration': 'Duration',
    'sessionHistory.rate': 'Rate',
    'sessionHistory.earned': 'Earned',
    'sessionHistory.noHistory': 'No history yet',
    'sessionHistory.noHistorySub': 'Sessions will appear here after calls end',

    'missed.missed': 'Missed',
    'missed.noMissed': 'No missed sessions',
    'missed.noMissedSub': "Calls you don't answer in 1 minute show up here",

    'notification.noNotifications': 'No notifications',

    'customers.lastConnected': 'Last connected',
    'customers.sessionType': 'Session type',
    'customers.sendVoiceNote': 'Send Voice Note',
    'customers.noCustomers': 'No customers found.',

    'profile.personalDetails': 'Personal Details',
    'profile.professionalDetails': 'Professional Details',
    'profile.firstName': 'First Name',
    'profile.lastName': 'Last Name',
    'profile.gender': 'Gender',
    'profile.phone': 'Phone',
    'profile.experience': 'Experience',
    'profile.years': 'Years',
    'profile.chatCharges': 'Chat Charges',
    'profile.callCharges': 'Call Charges',
    'profile.language': 'Language',
    'profile.editProfile': 'Edit Profile',
    // --- Share an astrologer's profile out of the app (utils/shareAstrologerProfile.js) ---
    'share.namaste': 'Namaste!',
    'share.selfLine': 'I am {{name}}, an astrologer on Astrowani.',
    'share.otherLine': 'I would like to recommend {{name}}, an astrologer on Astrowani.',
    'share.experienceLine': 'Experience: {{years}} years',
    'share.specialtiesLine': 'Areas of guidance: {{list}}',
    'share.ratingLine': 'Rating: {{rating}} out of 5',
    'share.selfClosing': 'You can consult me on Astrowani through chat, call or video. I am here to help you.',
    'share.otherClosing': 'You can consult {{name}} through chat, call or video on Astrowani.',
    'share.downloadLine': 'Download the Astrowani app:',
    'device.alreadySignedInTitle': 'Already signed in elsewhere',
    'device.alreadySignedInBody': 'Your account is signed in on another device:{{list}}\n\nOnly one device receives call and chat requests. Continue here and sign the other one out?',
    'device.continueHere': 'Continue here',
    'device.keepOther': 'Keep other device',
    'device.unknownDevice': 'Another device',
    'device.justNow': 'just now',
    'device.signedOutTitle': 'Signed out on this device',
    'device.signedOutBody': 'Your account was signed in on another device, so this one has been signed out. Only one device can receive call and chat requests at a time.',
    'device.signedOutOk': 'OK',
    'moderation.reportTitle': 'Report this customer',
    'moderation.reportSubtitle': 'Tell us what happened. Our team reviews every report.',
    'moderation.reportSubtitleNamed': 'Reporting {{name}}. Our team reviews every report.',
    'moderation.reason.abusive': 'Abusive or rude language',
    'moderation.reason.harassment': 'Harassment or repeated unwanted contact',
    'moderation.reason.sexual': 'Sexual or obscene content',
    'moderation.reason.threat': 'Threats or intimidation',
    'moderation.reason.spam': 'Spam or advertising',
    'moderation.reason.fraud': 'Fraud or payment abuse',
    'moderation.reason.other': 'Something else',
    'moderation.notePlaceholder': 'Add any details that would help us (optional)',
    'moderation.alsoBlock': 'Also block this customer',
    'moderation.alsoBlockHint': 'They will not be able to chat or call you again. You can undo this in Settings.',
    'moderation.cancel': 'Cancel',
    'moderation.submit': 'Submit report',
    'moderation.reportSentTitle': 'Report received',
    'moderation.reportSentBody': 'Thank you. Our team will review this report.',
    'moderation.reportSentAndBlocked': 'Thank you. Our team will review this report, and this customer can no longer contact you.',
    'moderation.reportFailedTitle': 'Could not send the report',
    'moderation.reportFailedBody': 'Please check your connection and try again.',
    'moderation.blockedTitle': 'Blocked customers',
    'moderation.blockedEmpty': 'You have not blocked anyone. Customers you block will appear here.',
    'moderation.blockedLoadFailed': 'Could not load your blocked list. Pull down to try again.',
    'moderation.unblockTitle': 'Unblock customer',
    'moderation.unblockConfirm': 'Unblock {{name}}? They will be able to chat and call you again.',
    'moderation.unblockAction': 'Unblock',
    'moderation.unblockFailedTitle': 'Could not unblock',
    'moderation.unblockFailedBody': 'Please check your connection and try again.',
    'moderation.blockAction': 'Block',
    'moderation.reportAction': 'Report',
    'device.minutesAgo': '{{n}} min ago',
    'device.hoursAgo': '{{n}} hr ago',
    'device.daysAgo': '{{n}} days ago',
    'share.androidLink': 'Android: {{url}}',
    'share.iosLink': 'iPhone: {{url}}',
    'share.dialogTitle': 'Share profile',
    'share.failedTitle': 'Could not share',
    'share.failed': 'The share sheet could not be opened. Please try again.',
    'share.fallbackName': 'Astrologer',
    'share.shareMyProfile': 'Share Profile',
    'profile.logout': 'Logout',
    'profile.confirmLogout': 'Are you sure you want to logout?',
    'profile.confirm': 'Confirm',

    'settings.aboutUs': 'About Us',
    'settings.faq': "FAQ's",
    'settings.refundCancellation': 'Refund & Cancellation',
    'settings.privacyPolicy': 'Privacy Policy',
    'settings.termsConditions': 'Terms & Conditions',
    'settings.safetyGuidelines': 'Safety Guidelines',
    'settings.childSafety': 'Child Safety',
    // Account deletion. The balance warning says "earnings", not "balance": this is
    // money the astrologer worked for, and the honest advice is to withdraw first.
    'settings.deleteAccount': 'Delete my account',
    'settings.confirmDeleteTitle': 'Delete your account?',
    'settings.confirmDeleteMsg':
      'This permanently removes your astrologer account. Your profile stops appearing to customers and you will no longer receive calls or chats. This cannot be undone.',
    'settings.deleteChecking': 'Checking your account…',
    'settings.deletePreviewFailed':
      'Could not check your account right now. Please try again when you are back online.',
    'settings.deleteBlockedSession':
      'You are in a consultation right now. Please end it, then try again.',
    'settings.deleteBlockedWithdrawal':
      'You have a withdrawal being processed. Please wait until it is paid or rejected, then try again.',
    'settings.deleteBalanceWarning':
      'You still have ₹{{amount}} in earnings. This will be forfeited and cannot be refunded — withdraw it before deleting.',
    'settings.deleteBtn': 'Delete',
    'settings.accountDeleted': 'Your account has been deleted.',
    'settings.deleteFailedTitle': 'Could not delete account',
    'settings.deleteFailedMsg': 'Something went wrong. Please try again, or contact support.',

    // Shown by components/ErrorBoundary.js when a subtree crashes. Kept short and
    // non-technical: the astrologer's next action is Retry or Go home, not a diagnosis.
    'errorBoundary.title': 'Something went wrong',
    'errorBoundary.subtitle': 'This screen ran into a problem. You can try again, or go back to your dashboard.',
    'errorBoundary.retry': 'Try again',
    'errorBoundary.goHome': 'Go to dashboard',

    // Shown by the axios 401 interceptor (api/ApiCall.js) when the stored token has
    // aged out. Names the cause, because "something went wrong" would leave the
    // astrologer retrying a call that can never succeed.
    'session.expiredTitle': 'Please log in again',
    'session.expiredMsg': 'Your session has expired for security. Log in again to continue — your earnings and session history are safe.',
    // Registration screen. This screen was hardcoded English until 2026-08-16,
    // when the Terms & Conditions checkbox was added and translating two lines
    // in an otherwise-English form would have looked broken.
    'registration.uploadImage': 'Upload Image (below 5MB)',
    'registration.fullName': 'Full Name',
    'registration.selectSkills': 'Select Skills',
    'registration.totalExperience': 'Total Experience',
    'registration.selectGender': 'Select Gender',
    'registration.selectLanguages': 'Select Languages',
    'registration.email': 'Enter Email ID',
    'registration.phone': 'Enter Phone number',
    'registration.submit': 'Submit',
    'registration.alreadyHaveAccount': 'Already have an Account? Sign in',
    'registration.male': 'Male',
    'registration.female': 'Female',
    'registration.other': 'Other',
    'registration.missingInfoTitle': 'Missing info',
    'registration.missingNamePhone': 'Please enter at least your full name and phone number.',
    'registration.invalidPhone': 'Please enter a valid 10-digit phone number.',
    'registration.failedTitle': 'Registration Failed',
    'registration.otpSendFailed': 'Could not send OTP. Please try again.',
    // Terms acceptance. Hindi is verb-final, so acceptSuffix carries the verb
    // and is empty in English, where the sentence is complete before the links.
    'registration.acceptTermsA11y': 'Accept terms and conditions',
    'registration.acceptPrefix': 'I have read and accept the ',
    'registration.acceptAnd': ' and the ',
    'registration.acceptSuffix': '',
    'registration.acceptRequired': 'Please accept the Terms & Conditions to continue.',

    'wallet.walletBalance': 'Wallet Balance',
    'wallet.requestWithdrawal': 'Request Withdrawal',
    'wallet.transactions': 'Transactions',
    'wallet.withdrawals': 'Withdrawals',
    'wallet.noTransactions': 'No transactions yet.',
    'wallet.noWithdrawals': 'No withdrawal requests yet.',
    'wallet.requested': 'Requested',

    'reviews.title': 'Ratings & Reviews',
    'reviews.noReviews': 'No reviews yet.',

    'performance.title': 'Your Performance',
    'performance.avgResponseTime': 'Avg. Response Time',
    'performance.acceptanceRate': 'Acceptance Rate',
    'performance.repeatCustomers': 'Repeat Customers',
    'performance.notEnoughActivity': 'Not enough activity yet to show your performance.',
    'performance.subtitlePrefix': 'How you look to customers — based on your last',
    'performance.subtitleSuffix': 'requests.',
    'performance.avgResponseHint': 'How fast you accept or reject incoming requests',
    'performance.acceptanceHint': "Of requests you've accepted, rejected, or missed",

    'missedHome.title': 'Missed Sessions',
    'missedHome.viewAll': 'View All',
    'missedHome.today': 'Today',
    'missedHome.yesterday': 'Yesterday',
    'missedHome.thisMonth': 'This Month',
    'missedHome.all': 'All',
    'missedHome.chat': 'Chat',
    'missedHome.videoCall': 'Video Call',
    'missedHome.audioCall': 'Audio Call',
    'missedHome.more': 'more',

    'call.audioCall': 'AUDIO CALL',
    'call.videoCall': 'VIDEO CALL',
    'call.remoteVideoPaused': 'Customer paused their video',
    'call.connecting': 'Connecting...',
    'call.mute': 'Mute',
    'call.unmute': 'Unmute',
    'call.video': 'Video',
    'call.videoOff': 'Video Off',
    'call.flip': 'Flip',
    'call.speaker': 'Speaker',
    'call.earpiece': 'Earpiece',
    'call.billingActive': 'billing active',
    'call.endCallTitle': 'End Call',
    'call.endCallMsg': 'Are you sure you want to end the call?',
    'call.end': 'End',
    'call.permissionRequired': 'Permission Required',
    'call.micPermissionMsg': 'Microphone access is needed for audio calls.',
    'call.micCameraPermissionMsg': 'Microphone and camera access are needed for video calls.',
    'call.setupFailed': 'Could Not Start Call',
    'call.setupFailedMsg': 'We could not start the call on this device. Please check your microphone is not in use by another app and try again.',
    'call.typing': 'typing...',
    'call.messagePlaceholder': 'Message...',
    'call.sessionEnded': 'Session Ended',

    'editProfile.requiredNotice': 'Fields marked with',
    'editProfile.requiredNoticeSuffix': 'are required for your profile to appear on the Astrowani customer app.',
    'editProfile.profilePhoto': 'Profile photo',
    'editProfile.removePhoto': 'Remove Photo',
    'editProfile.fullName': 'Full Name',
    'editProfile.email': 'Email',
    'editProfile.phoneNumber': 'Phone Number',
    'editProfile.gender': 'Gender',
    'editProfile.aboutYou': 'About You',
    'editProfile.description': 'Description',
    'editProfile.experienceYears': 'Experience (Years)',
    'editProfile.chargesLockedNotice': 'Your charges are locked — you set them once already. Contact the admin team if you need a change.',
    'editProfile.chargesHint': 'At least one of Chat / Call / Video charges must be set above ₹0.',
    'editProfile.chatCharges': 'Chat Charges (₹/min)',
    'editProfile.callCharges': 'Call Charges (₹/min)',
    'editProfile.videoCharges': 'Video Charges (₹/min)',
    'editProfile.languages': 'Languages (comma separated)',
    'editProfile.payoutDetails': 'Payout Details',
    'editProfile.payoutHint': 'Required to request a withdrawal — add either a bank account or a UPI ID.',
    'editProfile.accountHolderName': 'Account Holder Name',
    'editProfile.accountNumber': 'Account Number',
    'editProfile.ifscCode': 'IFSC Code',
    'editProfile.bankName': 'Bank Name',
    'editProfile.upiId': 'UPI ID (alternative to bank details)',
    'editProfile.saveChanges': 'Save Changes',
    'editProfile.chooseOption': 'Choose an option',
    'editProfile.camera': 'Camera',
    'editProfile.gallery': 'Gallery',

    'login.forAstrologers': 'For Astrologers',
    'login.phoneNumber': 'Phone number',
    'login.continue': 'Continue',
    'login.termsPrefix': 'By signing up, you agree to our',
    'login.termsOfUse': 'Terms of use',
    'login.and': '&',
    'login.privacyPolicy': 'Privacy Policy',
    'login.noAccount': "Don't have an Account ? Register",
    'login.close': 'Close',
    'login.validationError': 'Validation Error',
    'login.phoneEmpty': 'Phone number cannot be empty.',
    'login.phoneTooShort': 'Phone number must be at least 10 digits long.',
    'login.error': 'Error',
    'login.otpSendFailed': 'Could not send OTP. Please try again.',
    'login.notFound': 'Not Found',
    'login.noAccountFound': 'No astrologer account found with this phone number. Please register first.',
    'login.loginError': 'Login Error',
    'login.somethingWrong': 'Something went wrong. Please try again.',

    'otp.verifyTitle': 'Verify Your Number',
    'otp.enterCode': 'Enter the 6-digit code sent to',
    'otp.yourNumber': 'your number',
    'otp.almostThere': 'Almost There!',
    'otp.verifyBtn': 'Verify OTP',
    'otp.resendIn': 'Resend OTP in',
    'otp.noOtp': "Didn't receive the OTP?",
    'otp.sending': 'Sending...',
    'otp.resend': 'Resend OTP',
    'otp.changeNumber': 'Change Phone Number',
    'otp.invalidOtp': 'Invalid OTP',
    'otp.enterComplete': 'Please enter the complete 6-digit code.',
    'otp.verificationFailed': 'Verification Failed',
    'otp.invalidTryAgain': 'Invalid OTP. Please try again.',
    'otp.otpSent': 'OTP Sent',
    'otp.newCodeSent': 'A new code has been sent to your number.',
    'otp.resendFailed': 'Could not resend OTP.',

    'goLive.live': 'LIVE',
    'goLive.starting': 'STARTING…',
    'goLive.end': 'End',
    'goLive.someone': 'Someone',
    'goLive.sent': 'sent',
    'goLive.guest': 'Guest',
    'goLive.sessionMissing': 'Session missing. Please log in again.',
    'goLive.permissionsRequired': 'Permissions required',
    'goLive.cameraMicRequired': 'Camera and microphone are needed to go live.',
    'goLive.couldNotStart': 'Could not start live session.',
    // 2026-09-11 vendor i18n pass
    'common.error': "Error",
    'common.tryAgain': "Please try again.",
    'common.sessionMissing': "Session missing. Please log in again.",
    'nav.registration': "Astrologer Registration",
    'nav.thankYou': "Thank you",
    'nav.myWallet': "My Wallet",
    'drawer.whatsapp': "WhatsApp Customers",
    'drawer.freeCalls': "My Free Calls",
    'drawer.referrals': "Referrals & Commission",
    'drawer.nameNotAvailable': "Name not available",
    'drawer.emailNotAvailable': "Email not available",
    'freeCalls.intro': "Free introductory calls assigned to you. Ring the customer yourself at the time shown — there is nothing for them to join.",
    'freeCalls.empty': "No free calls assigned to you yet.",
    'freeCalls.upcoming': "Upcoming",
    'freeCalls.earlier': "Earlier",
    'freeCalls.today': "Today",
    'freeCalls.minFree': "{{n}} MIN · FREE",
    'freeCalls.done': "Done",
    'freeCalls.missed': "Missed",
    'freeCalls.timePassed': "Time passed",
    'freeCalls.ringsInApp': "Rings in their app",
    'freeCalls.ringsInAppWithPhone': "{{phone}} · rings in their app",
    'freeCalls.note': "Note",
    'freeCalls.calling': "Calling…",
    'freeCalls.callNow': "Call now",
    'freeCalls.markDone': "Mark done",
    'freeCalls.noAnswer': "No answer",
    'freeCalls.startFailed': "Could not start the call",
    'freeCalls.markDoneTitle': "Mark as done?",
    'freeCalls.markMissedTitle': "Mark as missed?",
    'freeCalls.yesDone': "Yes, done",
    'freeCalls.yesMissed': "Yes, missed",
    'freeCalls.thisCustomer': "This customer",
    'freeCalls.updateFailed': "Could not update",
    'whatsapp.openFailed': "Could not open",
    'whatsapp.notSent': "Not sent",
    'whatsapp.handBackTitle': "Hand back to the assistant?",
    'whatsapp.handBackBody': "The shop assistant will start answering this customer again.",
    'whatsapp.handBack': "Hand back",
    'whatsapp.handBackFailed': "Could not hand back",
    'whatsapp.assistant': "Assistant",
    'whatsapp.replyPlaceholder': "Reply to the customer…",
    'whatsapp.emptyTitle': "No customers waiting",
    'whatsapp.emptyBody': "When the shop assistant needs an astrologer, that customer appears here.",
    'pending.title': "Account Under Review",
    'pending.message': "Thank you for registering with Astrowani. Our team will review your details and contact you soon. Have a nice day! 🙏",
    'pending.subMessage': "Once your account is approved, you'll be taken to your dashboard automatically.",
    'pending.checkStatus': "Check Approval Status",
    'pending.logout': "Log out",
    'pending.rejected': "Your application was not approved. Please contact support.",
    'pending.stillReview': "Your account is still under review.",
    'pending.checkFailed': "Could not check status. Please try again.",
    'thankyou.title': "Thank You",
    'thankyou.subtitle': "For Registering With Us",
    'thankyou.body1': "Our team will review your details and contact you soon. Have a nice day! 🙏",
    'thankyou.body2': "Once your account is approved, log in and you'll go straight to your dashboard.",
    'thankyou.login': "Login",
    'popup.notice': "Notice",
    'popup.gotIt': "Got it",
    'prompt.ratePlayStore': "Rate on Play Store",
    'prompt.rateAppStore': "Rate on App Store",
    'prompt.maybeLater': "Maybe later",
    'prompt.later': "Later",
    'prompt.updateRequired': "This update is required to keep using the app.",
    'editProfile.fetchFailed': "An unexpected error occurred while fetching your profile.",
    'editProfile.updateFailed': "Failed to update profile.",
    'editProfile.phName': "Enter your full name",
    'editProfile.phEmail': "Enter your email",
    'editProfile.phPhone': "Enter your phone number",
    'editProfile.phAbout': "Tell customers about your expertise and experience...",
    'editProfile.phHolder': "As per bank records",
    'editProfile.phAccount': "Bank account number",
    'profile.notFound': "Profile not found.",
    'referrals.addedByAstrowani': "Added by Astrowani",
    'referrals.paidToYou': "Paid to you",
    'referrals.inWallet': "Already in your wallet",
    'referrals.pending': "Pending",
    'referrals.paysOnDelivery': "Pays out once delivered",
    'referrals.yourRecommendations': "Your recommendations",
    'referrals.empty': "No recommendations yet",
    'customers.recommendFailed': "Could not recommend",
    'customers.micRequiredTitle': "Microphone permission required",
    'customers.micRequiredBody': "Please allow microphone access to record a voice note.",
    'customers.voiceSentTitle': "Sent!",
    'customers.voiceSentBody': "Your voice note was sent to {{name}}.",
    'customers.sendFailed': "Could not send",
    'customers.recommend': "Recommend",
    'customers.noRemedies': "No remedies available right now.",
    'wallet.invalidAmount': "Enter a valid amount",
    'wallet.exceedsBalance': "Amount exceeds your wallet balance",
    'wallet.withdrawRequestedTitle': "Withdrawal requested",
    'wallet.withdrawRequestedBody': "Your request has been submitted and is pending admin approval.",
    'wallet.withdrawFailed': "Unable to request withdrawal",
    'wallet.enterAmount': "Enter amount",
    'home.callerCancelled': "Caller cancelled the request",
    'home.acceptFailed': "Could not accept request.",
    'settings.linkFailedTitle': "Unable to open link",
    'settings.linkFailedBody': "Please check your internet connection and try again.",
    'home.nowOnline': "You're now Online",
    'home.nowOffline': "You're now Offline — customers can't reach you",
    'home.nowLive': "You are now live!",
    'home.nowNotLive': "You are offline",
    'editProfile.updatedToast': "Profile updated successfully!",
    'editProfile.updatedTitle': "Profile Updated",
    'editProfile.chargesLockedBody': "Your other details were saved, but your chat/call/video charges are locked and can only be changed by the admin team now — contact them if you need a change.",
  },
  Hindi: {
    'drawer.dashboard': 'डैशबोर्ड',
    'drawer.myCustomers': 'मेरे ग्राहक',
    'drawer.profile': 'प्रोफ़ाइल',
    'drawer.sessionHistory': 'सत्र इतिहास',
    'drawer.missedSessions': 'छूटे हुए सत्र',
    'drawer.support': 'सहायता',
    'drawer.notification': 'सूचना',
    'drawer.settings': 'सेटिंग्स',
    'drawer.ratingReview': 'रेटिंग और समीक्षा',
    'drawer.performance': 'प्रदर्शन',
    'drawer.wallet': 'वॉलेट',
    'drawer.logout': 'लॉग आउट',
    'drawer.followUs': 'हमें फॉलो करें',
    'drawer.language': 'भाषा',

    'home.youAreOnline': 'आप ऑनलाइन हैं',
    'home.youAreOffline': 'आप ऑफ़लाइन हैं',
    'home.goLive': 'लाइव जाएं',
    'home.endLive': 'लाइव समाप्त करें',
    'home.sessionHistory': 'सत्र इतिहास',
    'home.chat': 'चैट',
    'home.call': 'कॉल',
    'home.video': 'वीडियो',
    'home.todayEarnings': 'आज की कमाई',
    'home.totalEarnings': 'कुल कमाई',
    'home.walletBalance': 'वॉलेट बैलेंस',
    'home.youAreOnlineSub': 'ग्राहक आपसे चैट, कॉल और वीडियो के लिए संपर्क कर सकते हैं',
    'home.youAreOfflineSub': 'आप नए अनुरोधों से छिपे हुए हैं',
    'home.serviceSettings': 'सेवा सेटिंग्स',
    'home.completeProfile': 'अपनी प्रोफ़ाइल पूरी करें',
    'home.completeProfileSub': 'अपना फोटो, अनुभव, भाषाएं और शुल्क जोड़ें ताकि ग्राहक आपको ढूंढ सकें। पूरा करने के लिए टैप करें।',
    'home.pendingApproval': 'हम आपकी प्रोफ़ाइल की समीक्षा करेंगे और जल्द ही आपसे संपर्क करेंगे!',
    'home.suspended': 'आपका खाता निलंबित है',
    'vsupport.title': 'सहायता',
    'vsupport.sessionExpired': 'आपका सत्र समाप्त हो गया है। कृपया लॉग आउट करके दोबारा लॉग इन करें, फिर यहां आएं।',
    'vsupport.offline': 'सर्वर से संपर्क नहीं हो सका। कृपया अपना इंटरनेट कनेक्शन जांचें।',
    'vsupport.tapToRetry': 'नीचे अपना संदेश लिखें, मैं दोबारा कोशिश करूंगा।',
    'vsupport.statusAssistant': 'सहायता सहायक',
    'vsupport.statusTyping': 'लिख रहे हैं...',
    'vsupport.statusConnecting': 'टीम से जोड़ा जा रहा है...',
    'vsupport.statusTeam': 'सहायता टीम',
    'vsupport.statusWithAgent': 'सहायता से {{name}}',
    'vsupport.statusResolved': 'हल हो गया',
    'vsupport.talkToPerson': 'व्यक्ति से बात करें',
    'vsupport.fromAgent': 'सहायता टीम से {{name}}',
    'vsupport.fromTeam': 'सहायता टीम',
    'vsupport.messagePlaceholder': 'अपनी समस्या बताएं...',
    'vsupport.sendFailed': 'संदेश नहीं भेजा जा सका। कृपया कनेक्शन जांचकर दोबारा कोशिश करें।',
    'vsupport.couldNotOpen': 'अभी सहायता नहीं खुल सकी। कृपया थोड़ी देर बाद कोशिश करें।',
    'vsupport.notReady': 'सहायता चैट तैयार की जा रही है। कृपया थोड़ी देर बाद कोशिश करें।',
    'vsupport.quickHint': 'या इनमें से किसी एक से शुरू करें:',
    'vsupport.quick.payout': 'मेरी निकासी अभी तक मेरे बैंक में नहीं पहुंची',
    'vsupport.quick.requests': 'मुझे कॉल या चैट रिक्वेस्ट नहीं मिल रही हैं',
    'vsupport.quick.profile': 'मेरी प्रोफ़ाइल या अनुमोदन से जुड़ा सवाल',
    'vsupport.quick.charges': 'मैं अपने प्रति-मिनट शुल्क बदलना चाहता हूं',
    'home.suspendedSub': 'ग्राहक अभी आपको न तो देख सकते हैं और न ही आप तक पहुंच सकते हैं। सहायता से संपर्क करने के लिए टैप करें।',
    'home.sessionHistoryBtn': 'सत्र इतिहास',

    'common.ok': 'ठीक है',
    'common.cancel': 'रद्द करें',
    'common.save': 'सेव करें',
    'common.accept': 'स्वीकार करें',
    'common.reject': 'अस्वीकार करें',
    'common.perMin': '/मिनट',
    'common.submit': 'सबमिट करें',
    'common.customer': 'ग्राहक',
    'common.notAvailable': 'उपलब्ध नहीं',
    'common.notSpecified': 'निर्दिष्ट नहीं',

    'popup.incomingCall': 'इनकमिंग कॉल',
    'popup.incomingVideoCall': 'इनकमिंग वीडियो कॉल',
    'popup.requesting': 'परामर्श का अनुरोध कर रहे हैं...',
    'popup.moreWaiting': 'और प्रतीक्षारत',
    'popup.decline': 'अस्वीकार करें',

    'sessionHistory.chat': 'चैट',
    'sessionHistory.audioCall': 'ऑडियो कॉल',
    'sessionHistory.videoCall': 'वीडियो कॉल',
    'sessionHistory.live': 'लाइव',
    'sessionHistory.active': 'सक्रिय',
    'sessionHistory.completed': 'पूर्ण',
    'sessionHistory.duration': 'अवधि',
    'sessionHistory.rate': 'दर',
    'sessionHistory.earned': 'कमाया',
    'sessionHistory.noHistory': 'अभी तक कोई इतिहास नहीं',
    'sessionHistory.noHistorySub': 'कॉल समाप्त होने के बाद सत्र यहां दिखाई देंगे',

    'missed.missed': 'छूट गया',
    'missed.noMissed': 'कोई छूटा हुआ सत्र नहीं',
    'missed.noMissedSub': 'जिन कॉल का आप 1 मिनट में जवाब नहीं देते वे यहां दिखाई देते हैं',

    'notification.noNotifications': 'कोई सूचना नहीं',

    'customers.lastConnected': 'अंतिम संपर्क',
    'customers.sessionType': 'सत्र प्रकार',
    'customers.sendVoiceNote': 'वॉइस नोट भेजें',
    'customers.noCustomers': 'कोई ग्राहक नहीं मिला।',

    'profile.personalDetails': 'व्यक्तिगत विवरण',
    'profile.professionalDetails': 'व्यावसायिक विवरण',
    'profile.firstName': 'पहला नाम',
    'profile.lastName': 'उपनाम',
    'profile.gender': 'लिंग',
    'profile.phone': 'फ़ोन',
    'profile.experience': 'अनुभव',
    'profile.years': 'वर्ष',
    'profile.chatCharges': 'चैट शुल्क',
    'profile.callCharges': 'कॉल शुल्क',
    'profile.language': 'भाषा',
    'profile.editProfile': 'प्रोफ़ाइल संपादित करें',
    // --- Share an astrologer's profile out of the app (utils/shareAstrologerProfile.js) ---
    'share.namaste': 'नमस्ते!',
    'share.selfLine': 'मैं {{name}} हूँ — Astrowani पर एक ज्योतिषी।',
    'share.otherLine': 'मैं {{name}} की सिफ़ारिश करना चाहूँगा — Astrowani पर एक ज्योतिषी।',
    'share.experienceLine': 'अनुभव: {{years}} वर्ष',
    'share.specialtiesLine': 'विशेषज्ञता: {{list}}',
    'share.ratingLine': 'रेटिंग: 5 में से {{rating}}',
    'share.selfClosing': 'आप Astrowani पर चैट, कॉल या वीडियो के माध्यम से मुझसे परामर्श कर सकते हैं। मैं आपकी सहायता के लिए उपलब्ध हूँ।',
    'share.otherClosing': 'आप Astrowani पर चैट, कॉल या वीडियो के माध्यम से {{name}} से परामर्श कर सकते हैं।',
    'share.downloadLine': 'Astrowani ऐप डाउनलोड करें:',
    'device.alreadySignedInTitle': 'पहले से किसी अन्य डिवाइस पर साइन इन',
    'device.alreadySignedInBody': 'आपका खाता किसी अन्य डिवाइस पर साइन इन है:{{list}}\n\nकॉल और चैट अनुरोध केवल एक ही डिवाइस पर आते हैं। यहाँ जारी रखें और दूसरे डिवाइस से साइन आउट करें?',
    'device.continueHere': 'यहाँ जारी रखें',
    'device.keepOther': 'दूसरा डिवाइस रखें',
    'device.unknownDevice': 'अन्य डिवाइस',
    'device.justNow': 'अभी',
    'device.signedOutTitle': 'इस डिवाइस से साइन आउट',
    'device.signedOutBody': 'आपका खाता किसी अन्य डिवाइस पर साइन इन किया गया, इसलिए इस डिवाइस से साइन आउट कर दिया गया है। एक समय में केवल एक ही डिवाइस पर कॉल और चैट अनुरोध आ सकते हैं।',
    'device.signedOutOk': 'ठीक है',
    'moderation.reportTitle': 'इस ग्राहक की शिकायत करें',
    'moderation.reportSubtitle': 'हमें बताएं कि क्या हुआ। हमारी टीम हर शिकायत की समीक्षा करती है।',
    'moderation.reportSubtitleNamed': '{{name}} की शिकायत। हमारी टीम हर शिकायत की समीक्षा करती है।',
    'moderation.reason.abusive': 'अपमानजनक या अभद्र भाषा',
    'moderation.reason.harassment': 'उत्पीड़न या बार-बार अनचाहा संपर्क',
    'moderation.reason.sexual': 'यौन या अश्लील सामग्री',
    'moderation.reason.threat': 'धमकी या डराना',
    'moderation.reason.spam': 'स्पैम या विज्ञापन',
    'moderation.reason.fraud': 'धोखाधड़ी या भुगतान का दुरुपयोग',
    'moderation.reason.other': 'कुछ और',
    'moderation.notePlaceholder': 'कोई विवरण जोड़ें जो हमारी मदद करे (वैकल्पिक)',
    'moderation.alsoBlock': 'इस ग्राहक को ब्लॉक भी करें',
    'moderation.alsoBlockHint': 'वे आपसे दोबारा चैट या कॉल नहीं कर पाएंगे। आप इसे सेटिंग्स में पूर्ववत कर सकते हैं।',
    'moderation.cancel': 'रद्द करें',
    'moderation.submit': 'शिकायत भेजें',
    'moderation.reportSentTitle': 'शिकायत मिल गई',
    'moderation.reportSentBody': 'धन्यवाद। हमारी टीम इस शिकायत की समीक्षा करेगी।',
    'moderation.reportSentAndBlocked': 'धन्यवाद। हमारी टीम इसकी समीक्षा करेगी, और यह ग्राहक अब आपसे संपर्क नहीं कर सकता।',
    'moderation.reportFailedTitle': 'शिकायत नहीं भेजी जा सकी',
    'moderation.reportFailedBody': 'कृपया अपना कनेक्शन जांचें और दोबारा प्रयास करें।',
    'moderation.blockedTitle': 'ब्लॉक किए गए ग्राहक',
    'moderation.blockedEmpty': 'आपने किसी को ब्लॉक नहीं किया है। ब्लॉक किए गए ग्राहक यहाँ दिखेंगे।',
    'moderation.blockedLoadFailed': 'ब्लॉक सूची लोड नहीं हो सकी। दोबारा प्रयास के लिए नीचे खींचें।',
    'moderation.unblockTitle': 'ग्राहक को अनब्लॉक करें',
    'moderation.unblockConfirm': '{{name}} को अनब्लॉक करें? वे दोबारा आपसे चैट और कॉल कर सकेंगे।',
    'moderation.unblockAction': 'अनब्लॉक',
    'moderation.unblockFailedTitle': 'अनब्लॉक नहीं हो सका',
    'moderation.unblockFailedBody': 'कृपया अपना कनेक्शन जांचें और दोबारा प्रयास करें।',
    'moderation.blockAction': 'ब्लॉक',
    'moderation.reportAction': 'शिकायत',
    'device.minutesAgo': '{{n}} मिनट पहले',
    'device.hoursAgo': '{{n}} घंटे पहले',
    'device.daysAgo': '{{n}} दिन पहले',
    'share.androidLink': 'Android: {{url}}',
    'share.iosLink': 'iPhone: {{url}}',
    'share.dialogTitle': 'प्रोफ़ाइल साझा करें',
    'share.failedTitle': 'साझा नहीं हो सका',
    'share.failed': 'शेयर विंडो नहीं खुल सकी। कृपया पुनः प्रयास करें।',
    'share.fallbackName': 'ज्योतिषी',
    'share.shareMyProfile': 'प्रोफ़ाइल साझा करें',
    'profile.logout': 'लॉग आउट',
    'profile.confirmLogout': 'क्या आप वाकई लॉग आउट करना चाहते हैं?',
    'profile.confirm': 'पुष्टि करें',

    'settings.aboutUs': 'हमारे बारे में',
    'settings.faq': 'सामान्य प्रश्न',
    'settings.refundCancellation': 'रिफंड और रद्दीकरण',
    'settings.privacyPolicy': 'गोपनीयता नीति',
    'settings.termsConditions': 'नियम और शर्तें',
    'settings.safetyGuidelines': 'सुरक्षा दिशानिर्देश',
    'settings.childSafety': 'बाल सुरक्षा',
    'settings.deleteAccount': 'मेरा खाता हटाएं',
    'settings.confirmDeleteTitle': 'क्या आप अपना खाता हटाना चाहते हैं?',
    'settings.confirmDeleteMsg':
      'इससे आपका ज्योतिषी खाता हमेशा के लिए हट जाएगा। आपकी प्रोफ़ाइल ग्राहकों को दिखना बंद हो जाएगी और आपको कॉल या चैट मिलना बंद हो जाएंगी। इसे वापस नहीं किया जा सकता।',
    'settings.deleteChecking': 'आपका खाता जांचा जा रहा है…',
    'settings.deletePreviewFailed':
      'अभी आपका खाता जांचा नहीं जा सका। नेटवर्क आने पर दोबारा कोशिश करें।',
    'settings.deleteBlockedSession':
      'आप अभी एक परामर्श में हैं। उसे समाप्त करें, फिर दोबारा कोशिश करें।',
    'settings.deleteBlockedWithdrawal':
      'आपकी एक निकासी प्रोसेस हो रही है। भुगतान होने या अस्वीकार होने तक प्रतीक्षा करें, फिर दोबारा कोशिश करें।',
    'settings.deleteBalanceWarning':
      'आपकी ₹{{amount}} कमाई अभी बाकी है। यह जब्त हो जाएगी और वापस नहीं मिलेगी — हटाने से पहले इसे निकाल लें।',
    'settings.deleteBtn': 'हटाएं',
    'settings.accountDeleted': 'आपका खाता हटा दिया गया है।',
    'settings.deleteFailedTitle': 'खाता नहीं हटाया जा सका',
    'settings.deleteFailedMsg': 'कुछ गड़बड़ हुई। दोबारा कोशिश करें या सपोर्ट से संपर्क करें।',

    'errorBoundary.title': 'कुछ गड़बड़ हो गई',
    'errorBoundary.subtitle': 'इस स्क्रीन में समस्या आ गई। आप दोबारा कोशिश कर सकते हैं, या डैशबोर्ड पर वापस जा सकते हैं।',
    'errorBoundary.retry': 'दोबारा कोशिश करें',
    'errorBoundary.goHome': 'डैशबोर्ड पर जाएं',

    'session.expiredTitle': 'कृपया दोबारा लॉग इन करें',
    'session.expiredMsg': 'सुरक्षा कारणों से आपका सत्र समाप्त हो गया है। जारी रखने के लिए दोबारा लॉग इन करें — आपकी कमाई और सत्र इतिहास सुरक्षित है।',
    'registration.uploadImage': 'चित्र अपलोड करें (5MB से कम)',
    'registration.fullName': 'पूरा नाम',
    'registration.selectSkills': 'विशेषज्ञता चुनें',
    'registration.totalExperience': 'कुल अनुभव',
    'registration.selectGender': 'लिंग चुनें',
    'registration.selectLanguages': 'भाषाएँ चुनें',
    'registration.email': 'ईमेल आईडी दर्ज करें',
    'registration.phone': 'फ़ोन नंबर दर्ज करें',
    'registration.submit': 'जमा करें',
    'registration.alreadyHaveAccount': 'पहले से खाता है? साइन इन करें',
    'registration.male': 'पुरुष',
    'registration.female': 'महिला',
    'registration.other': 'अन्य',
    'registration.missingInfoTitle': 'जानकारी अधूरी है',
    'registration.missingNamePhone': 'कृपया कम से कम अपना पूरा नाम और फ़ोन नंबर दर्ज करें।',
    'registration.invalidPhone': 'कृपया एक वैध 10-अंकों का फ़ोन नंबर दर्ज करें।',
    'registration.failedTitle': 'पंजीकरण विफल',
    'registration.otpSendFailed': 'OTP नहीं भेजा जा सका। कृपया पुनः प्रयास करें।',
    'registration.acceptTermsA11y': 'नियम और शर्तें स्वीकार करें',
    'registration.acceptPrefix': 'मैं ',
    'registration.acceptAnd': ' और ',
    'registration.acceptSuffix': ' को पढ़कर स्वीकार करता/करती हूँ।',
    'registration.acceptRequired': 'जारी रखने के लिए कृपया नियम और शर्तें स्वीकार करें।',

    'wallet.walletBalance': 'वॉलेट बैलेंस',
    'wallet.requestWithdrawal': 'निकासी का अनुरोध करें',
    'wallet.transactions': 'लेनदेन',
    'wallet.withdrawals': 'निकासी',
    'wallet.noTransactions': 'अभी तक कोई लेनदेन नहीं।',
    'wallet.noWithdrawals': 'अभी तक कोई निकासी अनुरोध नहीं।',
    'wallet.requested': 'अनुरोध किया गया',

    'reviews.title': 'रेटिंग और समीक्षा',
    'reviews.noReviews': 'अभी तक कोई समीक्षा नहीं।',

    'performance.title': 'आपका प्रदर्शन',
    'performance.avgResponseTime': 'औसत प्रतिक्रिया समय',
    'performance.acceptanceRate': 'स्वीकृति दर',
    'performance.repeatCustomers': 'दोहराए गए ग्राहक',
    'performance.notEnoughActivity': 'आपका प्रदर्शन दिखाने के लिए अभी पर्याप्त गतिविधि नहीं है।',
    'performance.subtitlePrefix': 'ग्राहकों को आप कैसे दिखते हैं — आपके पिछले',
    'performance.subtitleSuffix': 'अनुरोधों के आधार पर।',
    'performance.avgResponseHint': 'आप आने वाले अनुरोधों को कितनी तेज़ी से स्वीकार या अस्वीकार करते हैं',
    'performance.acceptanceHint': 'आपके स्वीकृत, अस्वीकृत, या छूटे हुए अनुरोधों में से',

    'missedHome.title': 'छूटे हुए सत्र',
    'missedHome.viewAll': 'सभी देखें',
    'missedHome.today': 'आज',
    'missedHome.yesterday': 'कल',
    'missedHome.thisMonth': 'इस महीने',
    'missedHome.all': 'सभी',
    'missedHome.chat': 'चैट',
    'missedHome.videoCall': 'वीडियो कॉल',
    'missedHome.audioCall': 'ऑडियो कॉल',
    'missedHome.more': 'और',

    'call.audioCall': 'ऑडियो कॉल',
    'call.videoCall': 'वीडियो कॉल',
    'call.remoteVideoPaused': 'ग्राहक ने अपना वीडियो बंद किया है',
    'call.connecting': 'कनेक्ट हो रहा है...',
    'call.mute': 'म्यूट करें',
    'call.unmute': 'अनम्यूट करें',
    'call.video': 'वीडियो',
    'call.videoOff': 'वीडियो बंद',
    'call.flip': 'पलटें',
    'call.speaker': 'स्पीकर',
    'call.earpiece': 'ईयरपीस',
    'call.billingActive': 'बिलिंग सक्रिय',
    'call.endCallTitle': 'कॉल समाप्त करें',
    'call.endCallMsg': 'क्या आप वाकई कॉल समाप्त करना चाहते हैं?',
    'call.end': 'समाप्त करें',
    'call.permissionRequired': 'अनुमति आवश्यक है',
    'call.micPermissionMsg': 'ऑडियो कॉल के लिए माइक्रोफ़ोन एक्सेस आवश्यक है।',
    'call.micCameraPermissionMsg': 'वीडियो कॉल के लिए माइक्रोफ़ोन और कैमरा एक्सेस आवश्यक है।',
    'call.setupFailed': 'कॉल शुरू नहीं हो सकी',
    'call.setupFailedMsg': 'हम इस डिवाइस पर कॉल शुरू नहीं कर सके। कृपया जाँचें कि आपका माइक्रोफ़ोन किसी अन्य ऐप द्वारा उपयोग में नहीं है और पुनः प्रयास करें।',
    'call.typing': 'टाइप कर रहे हैं...',
    'call.messagePlaceholder': 'संदेश...',
    'call.sessionEnded': 'सत्र समाप्त',

    'editProfile.requiredNotice': 'जिन फ़ील्ड पर',
    'editProfile.requiredNoticeSuffix': 'का निशान है, वे Astrowani ग्राहक ऐप में आपकी प्रोफ़ाइल दिखाने के लिए आवश्यक हैं।',
    'editProfile.profilePhoto': 'प्रोफ़ाइल फोटो',
    'editProfile.removePhoto': 'फोटो हटाएं',
    'editProfile.fullName': 'पूरा नाम',
    'editProfile.email': 'ईमेल',
    'editProfile.phoneNumber': 'फ़ोन नंबर',
    'editProfile.gender': 'लिंग',
    'editProfile.aboutYou': 'आपके बारे में',
    'editProfile.description': 'विवरण',
    'editProfile.experienceYears': 'अनुभव (वर्ष)',
    'editProfile.chargesLockedNotice': 'आपके शुल्क लॉक हैं — आपने इन्हें एक बार सेट कर दिया है। बदलाव के लिए एडमिन टीम से संपर्क करें।',
    'editProfile.chargesHint': 'चैट / कॉल / वीडियो शुल्क में से कम से कम एक ₹0 से ऊपर सेट होना चाहिए।',
    'editProfile.chatCharges': 'चैट शुल्क (₹/मिनट)',
    'editProfile.callCharges': 'कॉल शुल्क (₹/मिनट)',
    'editProfile.videoCharges': 'वीडियो शुल्क (₹/मिनट)',
    'editProfile.languages': 'भाषाएं (कॉमा से अलग करें)',
    'editProfile.payoutDetails': 'भुगतान विवरण',
    'editProfile.payoutHint': 'निकासी का अनुरोध करने के लिए आवश्यक — बैंक खाता या UPI ID जोड़ें।',
    'editProfile.accountHolderName': 'खाताधारक का नाम',
    'editProfile.accountNumber': 'खाता संख्या',
    'editProfile.ifscCode': 'IFSC कोड',
    'editProfile.bankName': 'बैंक का नाम',
    'editProfile.upiId': 'UPI ID (बैंक विवरण का विकल्प)',
    'editProfile.saveChanges': 'बदलाव सेव करें',
    'editProfile.chooseOption': 'एक विकल्प चुनें',
    'editProfile.camera': 'कैमरा',
    'editProfile.gallery': 'गैलरी',

    'login.forAstrologers': 'ज्योतिषियों के लिए',
    'login.phoneNumber': 'फ़ोन नंबर',
    'login.continue': 'जारी रखें',
    'login.termsPrefix': 'साइन अप करके, आप हमारी',
    'login.termsOfUse': 'उपयोग की शर्तों',
    'login.and': 'और',
    'login.privacyPolicy': 'गोपनीयता नीति',
    'login.noAccount': 'खाता नहीं है? रजिस्टर करें',
    'login.close': 'बंद करें',
    'login.validationError': 'सत्यापन त्रुटि',
    'login.phoneEmpty': 'फ़ोन नंबर खाली नहीं हो सकता।',
    'login.phoneTooShort': 'फ़ोन नंबर कम से कम 10 अंकों का होना चाहिए।',
    'login.error': 'त्रुटि',
    'login.otpSendFailed': 'OTP भेजा नहीं जा सका। कृपया पुनः प्रयास करें।',
    'login.notFound': 'नहीं मिला',
    'login.noAccountFound': 'इस फ़ोन नंबर के साथ कोई ज्योतिषी खाता नहीं मिला। कृपया पहले रजिस्टर करें।',
    'login.loginError': 'लॉगिन त्रुटि',
    'login.somethingWrong': 'कुछ गलत हो गया। कृपया पुनः प्रयास करें।',

    'otp.verifyTitle': 'अपना नंबर सत्यापित करें',
    'otp.enterCode': 'भेजा गया 6-अंकों का कोड दर्ज करें',
    'otp.yourNumber': 'आपके नंबर पर',
    'otp.almostThere': 'लगभग हो गया!',
    'otp.verifyBtn': 'OTP सत्यापित करें',
    'otp.resendIn': 'OTP दोबारा भेजें',
    'otp.noOtp': 'OTP नहीं मिला?',
    'otp.sending': 'भेजा जा रहा है...',
    'otp.resend': 'OTP दोबारा भेजें',
    'otp.changeNumber': 'फ़ोन नंबर बदलें',
    'otp.invalidOtp': 'अमान्य OTP',
    'otp.enterComplete': 'कृपया पूरा 6-अंकों का कोड दर्ज करें।',
    'otp.verificationFailed': 'सत्यापन विफल',
    'otp.invalidTryAgain': 'अमान्य OTP। कृपया पुनः प्रयास करें।',
    'otp.otpSent': 'OTP भेजा गया',
    'otp.newCodeSent': 'आपके नंबर पर एक नया कोड भेजा गया है।',
    'otp.resendFailed': 'OTP दोबारा नहीं भेजा जा सका।',

    'goLive.live': 'लाइव',
    'goLive.starting': 'शुरू हो रहा है…',
    'goLive.end': 'समाप्त करें',
    'goLive.someone': 'किसी ने',
    'goLive.sent': 'भेजा',
    'goLive.guest': 'अतिथि',
    'goLive.sessionMissing': 'सत्र गुम है। कृपया फिर से लॉग इन करें।',
    'goLive.permissionsRequired': 'अनुमतियां आवश्यक हैं',
    'goLive.cameraMicRequired': 'लाइव जाने के लिए कैमरा और माइक्रोफ़ोन आवश्यक हैं।',
    'goLive.couldNotStart': 'लाइव सत्र शुरू नहीं हो सका।',
    // 2026-09-11 vendor i18n pass
    'common.error': "त्रुटि",
    'common.tryAgain': "कृपया दोबारा प्रयास करें।",
    'common.sessionMissing': "सत्र नहीं मिला। कृपया दोबारा लॉग इन करें।",
    'nav.registration': "ज्योतिषी पंजीकरण",
    'nav.thankYou': "धन्यवाद",
    'nav.myWallet': "मेरा वॉलेट",
    'drawer.whatsapp': "व्हाट्सऐप ग्राहक",
    'drawer.freeCalls': "मेरी मुफ़्त कॉल",
    'drawer.referrals': "रेफ़रल और कमीशन",
    'drawer.nameNotAvailable': "नाम उपलब्ध नहीं",
    'drawer.emailNotAvailable': "ईमेल उपलब्ध नहीं",
    'freeCalls.intro': "आपको सौंपी गई मुफ़्त परिचय कॉल। दिखाए गए समय पर ग्राहक को स्वयं कॉल करें — उन्हें कहीं जुड़ना नहीं है।",
    'freeCalls.empty': "अभी तक आपको कोई मुफ़्त कॉल नहीं सौंपी गई है।",
    'freeCalls.upcoming': "आने वाली",
    'freeCalls.earlier': "पिछली",
    'freeCalls.today': "आज",
    'freeCalls.minFree': "{{n}} मिनट · मुफ़्त",
    'freeCalls.done': "पूर्ण",
    'freeCalls.missed': "छूटी",
    'freeCalls.timePassed': "समय निकल गया",
    'freeCalls.ringsInApp': "उनके ऐप में घंटी बजेगी",
    'freeCalls.ringsInAppWithPhone': "{{phone}} · उनके ऐप में घंटी बजेगी",
    'freeCalls.note': "नोट",
    'freeCalls.calling': "कॉल हो रही है…",
    'freeCalls.callNow': "अभी कॉल करें",
    'freeCalls.markDone': "पूर्ण चिह्नित करें",
    'freeCalls.noAnswer': "जवाब नहीं मिला",
    'freeCalls.startFailed': "कॉल शुरू नहीं हो सकी",
    'freeCalls.markDoneTitle': "पूर्ण चिह्नित करें?",
    'freeCalls.markMissedTitle': "छूटी हुई चिह्नित करें?",
    'freeCalls.yesDone': "हाँ, पूर्ण",
    'freeCalls.yesMissed': "हाँ, छूटी",
    'freeCalls.thisCustomer': "यह ग्राहक",
    'freeCalls.updateFailed': "अपडेट नहीं हो सका",
    'whatsapp.openFailed': "खोला नहीं जा सका",
    'whatsapp.notSent': "नहीं भेजा गया",
    'whatsapp.handBackTitle': "सहायक को वापस सौंपें?",
    'whatsapp.handBackBody': "शॉप सहायक इस ग्राहक को फिर से जवाब देना शुरू करेगा।",
    'whatsapp.handBack': "वापस सौंपें",
    'whatsapp.handBackFailed': "वापस नहीं सौंपा जा सका",
    'whatsapp.assistant': "सहायक",
    'whatsapp.replyPlaceholder': "ग्राहक को जवाब दें…",
    'whatsapp.emptyTitle': "कोई ग्राहक प्रतीक्षा में नहीं",
    'whatsapp.emptyBody': "जब शॉप सहायक को ज्योतिषी की ज़रूरत होगी, वह ग्राहक यहाँ दिखेगा।",
    'pending.title': "खाता समीक्षा में है",
    'pending.message': "Astrowani पर पंजीकरण के लिए धन्यवाद। हमारी टीम आपके विवरण की समीक्षा करके जल्द ही आपसे संपर्क करेगी। आपका दिन शुभ हो! 🙏",
    'pending.subMessage': "खाता स्वीकृत होते ही आप अपने आप डैशबोर्ड पर पहुँच जाएँगे।",
    'pending.checkStatus': "स्वीकृति की स्थिति देखें",
    'pending.logout': "लॉग आउट",
    'pending.rejected': "आपका आवेदन स्वीकृत नहीं हुआ। कृपया सहायता से संपर्क करें।",
    'pending.stillReview': "आपका खाता अभी भी समीक्षा में है।",
    'pending.checkFailed': "स्थिति नहीं देखी जा सकी। कृपया दोबारा प्रयास करें।",
    'thankyou.title': "धन्यवाद",
    'thankyou.subtitle': "हमारे साथ पंजीकरण करने के लिए",
    'thankyou.body1': "हमारी टीम आपके विवरण की समीक्षा करके जल्द ही आपसे संपर्क करेगी। आपका दिन शुभ हो! 🙏",
    'thankyou.body2': "खाता स्वीकृत होने के बाद लॉग इन करें, आप सीधे अपने डैशबोर्ड पर पहुँचेंगे।",
    'thankyou.login': "लॉग इन",
    'popup.notice': "सूचना",
    'popup.gotIt': "ठीक है",
    'prompt.ratePlayStore': "Play Store पर रेटिंग दें",
    'prompt.rateAppStore': "App Store पर रेटिंग दें",
    'prompt.maybeLater': "बाद में",
    'prompt.later': "बाद में",
    'prompt.updateRequired': "ऐप का उपयोग जारी रखने के लिए यह अपडेट ज़रूरी है।",
    'editProfile.fetchFailed': "आपकी प्रोफ़ाइल लाते समय एक अनपेक्षित त्रुटि हुई।",
    'editProfile.updateFailed': "प्रोफ़ाइल अपडेट नहीं हो सकी।",
    'editProfile.phName': "अपना पूरा नाम लिखें",
    'editProfile.phEmail': "अपना ईमेल लिखें",
    'editProfile.phPhone': "अपना फ़ोन नंबर लिखें",
    'editProfile.phAbout': "ग्राहकों को अपनी विशेषज्ञता और अनुभव के बारे में बताएँ...",
    'editProfile.phHolder': "बैंक रिकॉर्ड के अनुसार",
    'editProfile.phAccount': "बैंक खाता संख्या",
    'profile.notFound': "प्रोफ़ाइल नहीं मिली।",
    'referrals.addedByAstrowani': "Astrowani द्वारा जोड़ा गया",
    'referrals.paidToYou': "आपको भुगतान किया गया",
    'referrals.inWallet': "पहले से आपके वॉलेट में",
    'referrals.pending': "लंबित",
    'referrals.paysOnDelivery': "डिलीवरी के बाद भुगतान होगा",
    'referrals.yourRecommendations': "आपकी सिफ़ारिशें",
    'referrals.empty': "अभी तक कोई सिफ़ारिश नहीं",
    'customers.recommendFailed': "सिफ़ारिश नहीं की जा सकी",
    'customers.micRequiredTitle': "माइक्रोफ़ोन अनुमति आवश्यक है",
    'customers.micRequiredBody': "वॉइस नोट रिकॉर्ड करने के लिए कृपया माइक्रोफ़ोन की अनुमति दें।",
    'customers.voiceSentTitle': "भेज दिया गया!",
    'customers.voiceSentBody': "आपका वॉइस नोट {{name}} को भेज दिया गया।",
    'customers.sendFailed': "भेजा नहीं जा सका",
    'customers.recommend': "सिफ़ारिश करें",
    'customers.noRemedies': "अभी कोई उपाय उपलब्ध नहीं है।",
    'wallet.invalidAmount': "मान्य राशि दर्ज करें",
    'wallet.exceedsBalance': "राशि आपके वॉलेट बैलेंस से अधिक है",
    'wallet.withdrawRequestedTitle': "निकासी का अनुरोध किया गया",
    'wallet.withdrawRequestedBody': "आपका अनुरोध जमा हो गया है और एडमिन की स्वीकृति लंबित है।",
    'wallet.withdrawFailed': "निकासी का अनुरोध नहीं हो सका",
    'wallet.enterAmount': "राशि दर्ज करें",
    'home.callerCancelled': "कॉलर ने अनुरोध रद्द कर दिया",
    'home.acceptFailed': "अनुरोध स्वीकार नहीं हो सका।",
    'settings.linkFailedTitle': "लिंक नहीं खुल सका",
    'settings.linkFailedBody': "कृपया अपना इंटरनेट कनेक्शन जांचें और दोबारा प्रयास करें।",
    'home.nowOnline': "अब आप ऑनलाइन हैं",
    'home.nowOffline': "अब आप ऑफ़लाइन हैं — ग्राहक आपसे संपर्क नहीं कर सकते",
    'home.nowLive': "अब आप लाइव हैं!",
    'home.nowNotLive': "आप ऑफ़लाइन हैं",
    'editProfile.updatedToast': "प्रोफ़ाइल सफलतापूर्वक अपडेट हो गई!",
    'editProfile.updatedTitle': "प्रोफ़ाइल अपडेट हो गई",
    'editProfile.chargesLockedBody': "आपके अन्य विवरण सहेज लिए गए, लेकिन आपके चैट/कॉल/वीडियो शुल्क लॉक हैं और अब केवल एडमिन टीम ही इन्हें बदल सकती है — बदलाव चाहिए तो उनसे संपर्क करें।",
  },
};

// A missing Provider must never be fatal. `createContext()` with no default
// returns undefined, so every one of the ~23 consumers doing
// `const {language, t} = useContext(LanguageContext)` throws
// "Cannot read property 'language' of undefined" and takes the whole screen
// down with it. That crash was reported by Sentry on 2026-08-14
// (ASTROWANI-VENDOR-4) from a dev emulator while this feature was mid-build,
// but the same shape can happen in production any time a consumer renders
// outside the Provider — including during an OTA bundle swap or a remount.
// Giving the context a real default degrades to English instead of crashing.
// The language the Provider currently has, mirrored at module scope so code that runs
// OUTSIDE the React tree can still translate — specifically the axios 401 interceptor
// in api/ApiCall.js and the ErrorBoundary fallback, neither of which has a component
// to read context from. Kept in step by the Provider below; falls back to English
// until it loads, which is also the Provider's own initial state, so the two can never
// disagree in a visible way.
let currentLanguage = 'English';

/**
 * t() for non-React callers. Identical resolution to the Provider's own t()
 * (chosen language -> English -> the raw key), plus {{param}} interpolation.
 *
 * Prefer `useContext(LanguageContext).t` inside components; this exists only for
 * module-level code that has no context available.
 */
export const translate = (key, params) => {
  let str = translations[currentLanguage]?.[key] ?? translations.English[key] ?? key;
  if (params) {
    Object.keys(params).forEach((p) => {
      str = str.replace(new RegExp(`{{${p}}}`, 'g'), params[p]);
    });
  }
  return str;
};

export const LanguageContext = createContext({
  language: 'English',
  changeLanguage: () => {},
  t: (key) => translations.English[key] ?? key,
});

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('English');

  useEffect(() => {
    const loadLanguage = async () => {
      try {
        const savedLang = await AsyncStorage.getItem('vendorAppLanguage');
        if (savedLang) {
          setLanguage(savedLang);
          currentLanguage = savedLang; // keep the standalone translate() in step
        }
      } catch (error) {
        console.log('Error loading language', error);
      }
    };
    loadLanguage();
  }, []);

  const changeLanguage = async (lang) => {
    setLanguage(lang);
    currentLanguage = lang; // keep the standalone translate() in step
    try {
      await AsyncStorage.setItem('vendorAppLanguage', lang);
    } catch (error) {
      console.log('Error saving language', error);
    }
  };

  // Interpolates {{param}} placeholders, matching the standalone translate() above and
  // the customer app's t(). It previously ignored its second argument entirely, so any
  // key carrying a placeholder rendered the braces literally to the astrologer --
  // Support.tsx's t('vsupport.statusWithAgent', {name}) showed "{{name}} from support",
  // and the shared-profile message read "I am {{name}}, an astrologer on Astrowani."
  // Found on a device; a unit test against the CUSTOMER app's strings could not catch it,
  // because only this app's t() was missing the feature.
  const t = (key, params) => {
    let str = translations[language]?.[key] ?? translations['English'][key] ?? key;
    if (params) {
      Object.keys(params).forEach((param) => {
        str = str.replace(new RegExp(`{{${param}}}`, 'g'), params[param]);
      });
    }
    return str;
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
