import React, { createContext, useState, useEffect } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

// NOTE: the context itself is created *below* `translations`, because its default
// value needs to read from it. See the comment there.

// Namespaced keys (namespace.key) to avoid collisions as coverage grows across screens.
// NOTE: numbers, currency amounts, dates/times, astrologer names, OTP codes, and the
// legal pages (Terms of Use / Privacy Policy / Refund & Cancellation) are intentionally
// NEVER translated — see astrowani_customer-main/HINDI_I18N_APP.md.
const translations = {
  English: {
    // Home
    'home.welcome': 'Welcome to Astrowani!',
    'home.search': 'Search Here',
    'home.bestAstrologers': "India's Best Astrologers",
    'home.callWithAstrologers': 'Call with Astrologers',
    'home.viewAll': 'View All',
    'home.remedies': 'Astrowani Remedies',
    'home.bookPuja': 'Book VIP Puja',
    'home.buyGemstones': 'Buy Gemstones',
    'home.readMore': 'Read More',
    'home.categories': "Astrowani's Categories",
    'home.liveAstrologers': 'Live Astrologers',
    'home.noOneLive': 'No astrologer is live right now',
    'home.freeServices': '₹1 Services',
    'home.astroReports': 'Astro Reports',
    'home.blog': "Astrowani's Blog",
    'home.whatClientsSay': 'What Our Clients Say',
    'home.discoverTrust': 'Discover why thousands trust Astrowani',
    'home.whyBest': 'Why Astrowani Is Best For Astrology?',
    'home.whyBestBody': 'Astrowani reveals the destiny that Stars has designed for us. Astrowani is a proven science with its methods and way of interpreting the influence of stars and planets on earthly affairs and human destinies. Astrowani, with its scientific method of calculation and prediction of actual events, is approving enough to make people start believing in it. And it has been doing the same since the early Vedic period.',
    'home.noReviews': 'No reviews available yet.',
    'home.requestSent': 'Request Sent',
    'home.waitingFor': 'Waiting for {{name}} to accept your request...',
    'home.cancelRequest': 'Cancel Request',
    'home.chatWithAstrologer': 'Chat with Astrologer',
    'home.talkToAstrologer': 'Talk To Astrologer',
    'home.guideHint': "Don't know what to do? Start your first chat!",

    // Common labels / actions
    'common.chat': 'Chat',
    'common.call': 'Call',
    'common.video': 'Video',
    'common.noChat': 'No Chat',
    'common.noCall': 'No Call',
    'common.noVideo': 'No Video',
    'common.offline': 'Offline',
    'common.live': 'Live',
    'common.scheduled': 'Scheduled',
    'common.home': 'Home',
    'common.wallet': 'Wallet',
    'common.profile': 'My Profile',
    'common.cancel': 'Cancel',
    'common.ok': 'OK',
    'common.error': 'Error',
    'common.language': 'Choose Language',

    // Alerts
    'alerts.unavailable': 'Unavailable',
    'alerts.notAvailableChat': '{{name}} is not available for chat right now.',
    'alerts.notAvailableCall': '{{name}} is not available for calls right now.',
    'alerts.notAvailableVideo': '{{name}} is not available for video call right now.',
    'alerts.astrologerOffline': '{{name}} is offline right now. Please check back later.',
    'alerts.astrologerBusy': 'Astrologer is busy right now. Please try again after some time.',
    'alerts.selfBusy': 'You already have an active or pending call/chat. Please finish that one first.',
    'alerts.notPickedUpAudio': 'Your audio call was not picked up. Please try again later.',
    'alerts.notPickedUpVideo': 'Your video call was not picked up. Please try again later.',
    'alerts.insufficientBalance': 'Insufficient Balance',
    'alerts.failedWalletCheck': 'Could not check your wallet balance — please check your internet connection and try again.',
    'alerts.failedRequestAstrologer': 'Failed to send request to astrologer.',
    'alerts.failedInitiateCall': 'Failed to initiate call',
    'alerts.failedInitiateVideoCall': 'Failed to initiate video call',

    // Drawer
    'drawer.myWallet': 'My Wallet',
    'drawer.mySessions': 'My Sessions',
    'drawer.remedies': 'Remedies',
    'drawer.chatWithAstrologer': 'Chat With Astrologer',
    'drawer.blogs': 'Astrowani Blogs',
    'drawer.myFavorites': 'My Favorites',
    'drawer.myOrders': 'My Orders',
    'drawer.voiceNotes': 'Voice Notes',
    'drawer.referFriend': 'Refer A Friend',
    'drawer.settings': 'Settings',
    'drawer.support': 'Support',
    'drawer.shareApp': 'Share App',
    'drawer.logout': 'Logout',
    'drawer.connectWithUs': 'Connect With Us',
    'drawer.welcome': 'Welcome!',
    'drawer.updateProfile': 'Update your profile',

    // Settings
    'settings.aboutUs': 'About Us',
    'settings.faqs': "FAQ's",
    'settings.refundCancellation': 'Refund & Cancellation',
    'settings.privacyPolicy': 'Privacy Policy',
    'settings.termsOfUse': 'Terms of Use',
    'settings.childSafety': 'Child Safety',
    'settings.safetyGuidelines': 'Safety Guidelines',
    'settings.reportVulnerability': 'Report a Vulnerability',
    'settings.deleteAccount': 'Delete my account',
    'settings.confirmLogoutTitle': 'Confirm Logout',
    'settings.confirmLogoutMsg': 'Are you sure you want to log out?',
    'settings.confirmDeleteTitle': 'Confirm Delete',
    'settings.confirmDeleteMsg': 'Are you sure you want to delete your account? Once deleted, all your saved history will be lost. Do you still wish to continue?',
    'settings.deleteBtn': 'Delete',
    'settings.accountDeleted': 'Account deleted successfully',
    'settings.loggedOut': 'Logged out successfully',

    // Login / OTP
    'login.tagline': "Best Astrologer's Team",
    'login.discoverPath': 'Discover Your Cosmic Path',
    'login.phoneNumber': 'Phone number',
    'login.continue': 'Continue',
    'login.agreeTerms': 'By signing up, you agree to our ',
    'login.and': ' & ',
    'login.noAccount': "Don't have an account? ",
    'login.register': 'Register',
    'login.selectCountry': 'Select Country',
    'login.close': 'Close',
    'login.validationError': 'Validation Error',
    'login.phoneEmpty': 'Phone number cannot be empty.',
    'login.phoneTooShort': 'Phone number must be at least 10 digits long.',
    'login.otpFailed': 'Could not send OTP. Please try again.',
    'login.noAccountTitle': 'No Account Found',
    'login.noAccountMsg': "We couldn't find an account for this number. Please sign up first.",
    'login.somethingWrong': 'Something went wrong. Please try again.',
    'login.guideHint': 'First time here? Tap Register to sign up!',

    // Remedies (static home tiles)
    'remedies.puja': 'Puja',
    'remedies.gemstones': 'Gemstones',
    'remedies.specificPuja': 'Specific Puja',
    'remedies.lifeReports': 'Life Reports',
    'remedies.buyNow': 'Buy Now',
    'pujaDetail.pujaSold': 'Puja Sold',
    'pujaDetail.details': 'Details:',
    'pujaDetail.duration': 'Duration',
    'pujaDetail.godGoddess': 'Pooja God or Goddess',
    'pujaDetail.location': 'Location',
    'pujaDetail.date': 'Date',
    'pujaDetail.benefits': 'Benefits:',
    'pujaDetail.groupPuja': 'Group Puja',
    'pujaDetail.bookNow': 'Book Now',
    'pujaDetail.bookingTitle': 'Booking',
    'pujaDetail.bookingMsg': 'Proceeding to book the puja...',
    'gemstone.carats': 'carats',
    'common.errorPrefix': 'Error:',

    'refer.title': 'Refer & Earn',
    'refer.subtitle': 'Invite friends to Astrowani and both of you win',
    'refer.getPerFriend': 'Get ₹{{amount}} per friend',
    'refer.friendsReferred': 'Friends Referred',
    'refer.totalEarned': 'Total Earned',
    'refer.yourCode': 'YOUR REFERRAL CODE',
    'refer.copy': 'Copy',
    'refer.shareInfo': 'Share this code — you earn ₹{{amount}} when your friend completes their first session',
    'refer.viaWhatsapp': 'Refer via WhatsApp',
    'refer.viaOtherApps': 'Share via other apps',
    'refer.howItWorks': 'HOW IT WORKS',
    'refer.step1': 'Your friend signs up on Astrowani using your referral code.',
    'refer.step2': 'You receive ₹{{amount}} once they complete their first chat, call, or video session.',
    'refer.copiedTitle': 'Copied to clipboard',
    'refer.copiedMsg': 'Referral code {{code}} copied!',
    'refer.whatsappNotInstalled': 'WhatsApp not installed',

    'orders.typePuja': 'Puja',
    'orders.typeGemstone': 'Gemstone',
    'orders.typeSpecificPuja': 'Specific Puja',
    'orders.typeLifeReport': 'Life Report',
    'orders.reportDelivered': 'Report delivered — tap to view',
    'orders.reportPending': 'Your report is being prepared…',
    'orders.noOrders': 'No orders yet.',
    'orders.close': 'Close',

    'favorites.empty': "No Favorites yet.\nTap the heart on an astrologer's profile to add them here.",

    'support.issueTechnical': 'Technical Issue',
    'support.issueAccount': 'Account Related Issue',
    'support.issueRefund': 'Refund Request',
    'support.issueOther': 'Other',
    'support.issueFeedback': 'Feedback',
    'support.title': 'Have any Questions?',
    'support.subtitle': 'We are happy to help. Tell us your Issue and we will get back to you earliest.',
    'support.enterName': 'Enter Your Name',
    'support.email': 'Email',
    'support.mobileNumber': 'Mobile Number',
    'support.selectIssue': 'Select Issue',
    'support.writeMessage': 'Write your message here',
    'support.submit': 'Submit',
    'support.fillAllFields': 'Please fill all fields before submitting.',
    'support.submittedSuccess': 'Support request submitted successfully!',

    'voiceNotes.noNotes': 'No voice notes yet.',

    'expertsList.liveNow': 'Live now',
    'expertsList.notifyTitle': "We'll let you know",
    'expertsList.notifyMsg': "We'll notify you when {{name}} is free.",
    'expertsList.notifyFailed': 'Could not join the waitlist. Please try again.',
    'expertsList.noneFound': 'No astrologers found.',
    'expertsList.failedSendCallRequest': 'Failed to send call request.',
    'common.noDataAvailable': 'No data available',
    'common.customer': 'Customer',
    'common.success': 'Success',

    'addReview.title': 'Review {{name}}',
    'addReview.ratingRequired': 'Please provide a rating.',
    'addReview.commentRequired': 'Please write a review comment.',
    'addReview.submittedMsg': 'Your review has been submitted successfully!',
    'addReview.failedSubmit': 'Failed to submit review.',
    'addReview.placeholder': 'Write your experience...',
    'addReview.submit': 'Submit Review',

    'review.getBestSolutions': 'Get Best Solutions',
    'review.forAstrologer': 'for {{name}}',

    'voiceNotesBanner.newNote': 'New voice note from {{name}}',
    'voiceNotesBanner.subtitle': "Tap to listen — they're checking in on you",

    'liveAarti.title': 'Live Aarti / Pooja',

    'gemBuy.buy': 'Buy',
    'gemBuy.messageFor': 'Message for {{name}}',
    'gemBuy.enterMessage': 'Enter your message',
    'gemBuy.purchase': 'Purchase',
    'gemBuy.inquiry': 'Inquiry',
    'gemBuy.submit': 'Submit',
    'gemBuy.close': 'Close',
    'gemBuy.paymentSuccessful': 'Payment Successful',
    'gemBuy.paymentId': 'Payment ID: {{id}}',
    'gemBuy.paymentFailed': 'Payment Failed',

    'walletHistory.noTransaction': 'No Transaction',
    'walletHistory.addMoney': 'Add Money',

    'freeBotChat.freeChat': 'Free chat',
    'freeBotChat.freeBanner': 'Your free 5-minute welcome chat — completely free',
    'freeBotChat.messagePlaceholder': 'Type a message…',
    'freeBotChat.completeTitle': 'Chat Complete!',
    'freeBotChat.completeMsg': "Thanks for chatting with us! Start a real chat with any astrologer whenever you're ready.",
    'freeBotChat.greatThanks': 'Great, thanks!',

    'splash.tagline': 'Consult Online Astrologers',

    'call.pleaseLogin': 'Please login to continue.',
    'call.audioCall': 'AUDIO CALL',
    'call.videoCall': 'VIDEO CALL',
    'call.connecting': 'Connecting...',
    'call.ringing': 'Ringing... {{seconds}}s',
    'call.mute': 'Mute',
    'call.unmute': 'Unmute',
    'call.camera': 'Camera',
    'call.videoOff': 'Video Off',
    'call.flip': 'Flip',
    'call.speaker': 'Speaker',
    'call.earpiece': 'Earpiece',
    'call.endCallTitle': 'End Call',
    'call.endCallMsg': 'Are you sure you want to end the call?',
    'call.end': 'End',
    'call.permissionRequired': 'Permission Required',
    'call.micPermissionMsg': 'Microphone access is needed for audio calls.',
    'call.micCameraPermissionMsg': 'Microphone and camera access are needed for video calls.',
    'call.inProgress': 'Call in progress',
    'call.stillActive': 'Your call with {{name}} is still active. Tap to return.',
    'call.videoInProgress': 'Video call in progress',
    'call.videoStillActive': 'Your video call with {{name}} is still active. Tap to return.',

    'chatSession.sessionEnded': 'Session Ended',
    'chatSession.endChatTitle': 'End Chat',
    'chatSession.endChatMsg': 'Going back will end this chat session. Are you sure you want to end the chat?',
    'chatSession.end': 'End',
    'chatSession.typing': 'typing...',
    'chatSession.connecting': 'Connecting…',
    'chatSession.waitingForAccept': 'Waiting for astrologer to accept…',
    'chatSession.messagePlaceholder': 'Type a message…',
    'chatSession.inProgress': 'Chat in progress',
    'chatSession.stillActive': 'Your chat with {{name}} is still active. Tap to return.',
    'chatSession.astrologerEnded': 'The astrologer has ended the session.',

    // ReusableList shared card
    'common.viewProfile': 'Profile',
    'common.free': 'Free',
    'common.exp': 'Exp',
    'common.yrs': 'yrs',
    'common.searchAstrologer': 'Search astrologer by name or skill...',
    'alerts.failedGenerateRoom': 'Failed to generate call room.',
    'alerts.declined': 'Declined',
    'alerts.declinedBusy': '{{name}} is currently busy and declined the call.',
    'video.waitingFor': 'Waiting for {{name}} to accept your video call...',

    // Chat request hook
    'chat.pleaseLogIn': 'Please log in first.',
    'chat.sessionInvalid': 'Session invalid. Please log out and log back in.',
    'chat.astrologerInfoMissing': 'Astrologer info missing. Please refresh and try again.',
    'chat.lowBalance': 'Low Balance',
    'chat.lowBalanceMsg': 'You need at least ₹{{charge}} to start a chat. Please recharge your wallet.',
    'chat.couldNotSendRequest': 'Could not send request: {{msg}}',
    'chat.notPickedUp': 'Your chat request was not picked up. Please try again later.',
    'status.astrologerBusyTitle': 'Astrologer Busy',
    'status.youAreBusyTitle': 'Already in a Session',
    'status.notAnsweredTitle': 'Not Answered',

    // Live tab
    'live.watching': 'watching',
    'live.joinNow': 'Join Now',
    'live.searchPlaceholder': 'Search live sessions...',
    'live.noneLive': 'No astrologers are live right now.',
    'live.connectingToLive': 'Connecting to live…',
    'live.waitingForVideo': 'Waiting for video…',
    'live.ended': 'Live ended',
    'live.endedMsg': '{{name}} has ended the live.',
    'live.theAstrologer': 'The astrologer',
    'live.sayPlaceholder': 'Say something…',
    'live.someone': 'Someone',
    'live.sent': 'sent',
    'live.guest': 'Guest',

    // AstrologerInfo profile screen
    'profile.new': 'New',
    'profile.yrs': 'Yrs',
    'profile.gift': 'Gift',
    'profile.off': 'Off',
    'profile.specialization': 'Specialization',
    'profile.aboutServices': 'About My Services',
    'profile.aboutFallback': 'Experienced and professional astrologer here to guide you through your life journey.',
    'profile.readLess': 'Read Less',
    'profile.experienceQualification': 'Experience & Qualification',
    'profile.experienceBody': "With several years of dedicated practice, I've honed my skills in {{specialties}}.",
    'profile.sendAGift': 'Send a Gift',
    'profile.clientReviews': 'Client Reviews',
    'profile.reviewsOnAstrowani': '{{count}} reviews on Astrowani',
    'profile.noReviewsYet': 'No reviews yet.',
    'profile.showAll': 'Show All',
    'profile.writeReview': '+ Write Review',
    'profile.astrowaniReplyPrefix': '↳ Astrowani: ',

    // OTP screens
    'otp.sentToNumber': 'OTP sent to your Number',
    'otp.expiresIn': 'OTP expires in {{time}}',
    'otp.verifyBtn': 'Verify OTP',
    'otp.notReceived': "Didn't receive the OTP? ",
    'otp.resend': 'Resend OTP',
    'otp.invalidTryAgain': 'Invalid OTP. Please try again.',
    'otp.failedVerify': 'Failed to verify OTP. Please try again.',
    'otp.verifyTitle': 'Verify Your Number',
    'otp.enterCodeSentTo': 'Enter the 6-digit code sent to ',
    'otp.yourNumber': 'your number',
    'otp.almostThere': 'Almost There!',
    'otp.resendIn': 'Resend OTP in {{time}}',
    'otp.sending': 'Sending...',
    'otp.changeNumber': 'Change Phone Number',
    'otp.invalidOtpTitle': 'Invalid OTP',
    'otp.enterComplete': 'Please enter the complete 6-digit code.',
    'otp.verificationFailed': 'Verification Failed',
    'otp.otpSentTitle': 'OTP Sent',
    'otp.newCodeSent': 'A new code has been sent to your number.',
    'otp.couldNotResend': 'Could not resend OTP.',
    'otp.couldNotResendRetry': 'Could not resend OTP. Please try again.',

    // About Us
    'about.tagline': 'Best Astrologers Team',
    'about.title': 'About Us',
    'about.p1': 'Astrowani is your trusted gateway to the ancient science of astrology, delivered with the convenience of modern technology. Our mission is to help you find clarity, direction, and peace of mind through personalized astrological guidance.',
    'about.p2': 'We work with a team of highly experienced and verified astrologers from across India, each specializing in Vedic astrology, numerology, palmistry, tarot reading, and more. Whether you are seeking answers about career, relationships, health, or finance, our experts are here to guide you with compassion and accuracy.',
    'about.p3': 'At Astrowani, we believe astrology is not about predicting doom or dictating your fate, but about empowering you to make informed decisions. Our consultations are rooted in authenticity, ethics, and confidentiality, ensuring that your personal details and readings remain private.',
    'about.p4': "With features like live consultations, chat sessions, and daily horoscopes, Astrowani makes it easy to connect with the right expert anytime, anywhere. Whether you're a believer or just curious, we welcome you to explore what the stars have to say.",
    'about.p5': 'Join thousands of satisfied users who have discovered guidance, inspiration, and positivity through Astrowani — where tradition meets trust.',

    // FAQ
    'faq.title': 'Frequently Asked Questions',
    'faq.q1': 'I want to chat with an Astrologer. How do I start?',
    'faq.a1': 'In order to chat with an Astrologer, all you need to do is login to your Astrowani account or sign up to create an account, add money to your wallet, and then simply choose the Astrologer you want to chat with and begin your session.',
    'faq.q2': 'Is there any requirement of minimum balance before I begin consulting an Astrologer?',
    'faq.a2': 'You need to have a minimum balance of $10 to start consulting an Astrologer on Astrowani.',
    'faq.q3': 'Are the Astrologers verified?',
    'faq.a3': 'Yes, all the Astrologers on Astrowani are verified professionals with years of experience.',
    'faq.q4': 'If I get a phone call in between a chat, will it automatically end my session?',
    'faq.a4': 'No, your session will not end automatically if you receive a phone call. The chat will be paused, and you can resume once the call ends.',

    // Wallet
    'wallet.invalidAmount': 'Invalid Amount',
    'wallet.enterValidAmount': 'Please enter a valid amount to recharge.',
    'wallet.paymentSuccessful': 'Payment Successful',
    'wallet.paymentId': 'Payment ID: {{id}}',
    'wallet.paymentFailed': 'Payment Failed',
    'wallet.addMoney': 'Add Money to Wallet',
    'wallet.rechargeSubtitle': 'Recharge seamlessly to talk to experts',
    'wallet.enterAmount': 'Enter Amount',
    'wallet.recommendedAmounts': 'Recommended amounts',
    'wallet.totalPayable': 'Total Payable',
    'wallet.proceedToPay': 'Proceed to Pay',
    'wallet.processing': 'Processing…',

    // Register screen
    'register.title': 'Register',
    'register.tapToAddPhoto': 'Tap to add photo',
    'register.fillInfoNote': 'Fill the Information for Astrologer',
    'register.takePhoto': 'Take Photo',
    'register.chooseFromLibrary': 'Choose from Library',
    'register.fullName': 'Enter your full name',
    'register.male': 'Male',
    'register.female': 'Female',
    'register.other': 'Other',
    'register.selectGender': 'Select your gender',
    'register.placeOfBirth': 'Enter your place of birth',
    'register.mobileNumber': 'Enter your 10-digit mobile number',
    'register.emailAddress': 'Enter your email address',
    'register.sendingOtp': 'Sending OTP…',
    'register.submit': 'Submit',
    'register.fillNameMobile': 'Please fill in at least your Name and Mobile Number.',
    'register.validMobile': 'Please enter a valid 10-digit mobile number.',
    'register.accountExists': 'Account Already Exists',
    'register.accountExistsMsg': 'An account already exists for this number. Please log in instead.',
    'register.cameraPermTitle': 'Camera Permission',
    'register.cameraPermMsg': 'This app needs access to your camera',
    'register.askLater': 'Ask Me Later',

    // Email OTP screen
    'emailOtp.sentToEmail': 'OTP sent to your Email',
    'emailOtp.loginFailed': 'Login Failed',
    'emailOtp.loginError': 'Login Error',
    'emailOtp.somethingWrong': 'Something went wrong. Please try again.',

    // User Profile screen
    'userProfile.personalInfo': 'Personal Info',
    'userProfile.palmHandPhoto': 'Palm/Hand Photo',
    'userProfile.removePhoto': 'Remove Photo',
    'userProfile.basicDetails': 'Basic Details',
    'userProfile.fullName': 'Full Name',
    'userProfile.mobileNumber': 'Mobile Number',
    'userProfile.emailAddress': 'Email Address',
    'userProfile.gender': 'Gender',
    'userProfile.married': 'Married',
    'userProfile.unmarried': 'Unmarried',
    'userProfile.maritalStatus': 'Marital Status',
    'userProfile.birthDetails': 'Birth Details',
    'userProfile.dateOfBirth': 'Date of Birth',
    'userProfile.timeOfBirth': 'Time of Birth',
    'userProfile.location': 'Location',
    'userProfile.cityPlaceOfBirth': 'City (Place of Birth)',
    'userProfile.state': 'State',
    'userProfile.enterField': 'Enter {{field}}',
    'userProfile.selectField': 'Select {{field}}',
    'userProfile.uploadPalmPhoto': 'Upload Palm Photo',
    'userProfile.palmPhotoInfo': 'Uploading a clear photo of your palm helps our astrologers provide more accurate palmistry readings.',
    'userProfile.noPhotoUploaded': 'No photo uploaded',
    'userProfile.saveChanges': 'Save Changes',
    'userProfile.removePhotoConfirm': 'Are you sure you want to remove this photo?',
    'userProfile.remove': 'Remove',
    'userProfile.validationError': 'Validation Error',
    'userProfile.uploadProfilePhoto': 'Please upload a Profile Photo.',
    'userProfile.enterFullName': 'Please enter your Full Name.',
    'userProfile.enterMobile': 'Please enter your Mobile Number.',
    'userProfile.emailEmpty': 'Email cannot be empty.',
    'userProfile.emailInvalid': 'Please enter a valid email address.',
    'userProfile.selectGender': 'Please select your Gender.',
    'userProfile.selectMaritalStatus': 'Please select your Marital Status.',
    'userProfile.selectDob': 'Please select your Date of Birth.',
    'userProfile.selectTob': 'Please select your Time of Birth.',
    'userProfile.enterCity': 'Please enter your City (Place of Birth).',
    'userProfile.selectState': 'Please select your State.',
    'userProfile.success': 'Success',
    'userProfile.updatedSuccessfully': 'Profile updated successfully!',
    'userProfile.updateError': 'Error updating profile',
    'userProfile.selectImage': 'Select Image',

    // My Sessions
    'session.chatSession': 'Chat Session',
    'session.audioCall': 'Audio Call',
    'session.videoCall': 'Video Call',
    'session.liveSession': 'Live Session',
    'session.tabChat': 'Chat',
    'session.tabLive': 'Live',
    'session.noneFound': 'No {{type}} found',
    'session.willAppear': 'Sessions will appear here after they end',
    'common.astrologer': 'Astrologer',
    'session.ref': 'Ref: {{id}}',
    'session.active': 'Active',
    'session.viewProfile': 'View Profile',
    'session.rate': 'Rate',
    'session.duration': 'Duration',
    'session.charged': 'Charged',
    'session.rateThisSession': 'Rate this session',
    'notifications.none': 'No new notifications',

    // Search screen
    'search.noAstrologerFound': 'No astrologer found',
    'search.mostSearched': 'Most searched on Astrowani',
    'search.tag.maritalLife': 'Marital Life',
    'search.tag.loveRelationship': 'Love & Relationship',
    'search.tag.careerJob': 'Career & Job',
    'search.tag.cheatingAffairs': 'Cheating & Affairs',
    'search.tag.financeBusiness': 'Finance & Business',
    'search.tag.breakupDivorce': 'Break-Up & Divorce',
    'search.tag.vedicAstrology': 'Vedic Astrology',
    'search.tag.psychicReading': 'Psychic Reading',
    'search.tag.tarotReading': 'Tarot Reading',
    'search.tag.numerology': 'Numerology',
    'search.tag.relationshipCounseling': 'Relationship Counseling',

    // Blog screen
    'blog.createdAt': 'Created At {{date}}',

    // Free Services — Panchang
    'panchang.enterLocation': 'Enter your location',
    'panchang.loading': 'Loading...',
    'panchang.title': 'Panchang',
    'panchang.additionalInfo': 'Additional Info',
    'panchang.auspiciousTime': 'Auspicious Time',
    'panchang.inauspiciousTime': 'Inauspicious Time',
    'panchang.vaara': 'Vaara',
    'panchang.nakshatra': 'Nakshatra',
    'panchang.tithi': 'Tithi',
    'panchang.karana': 'Karana',
    'panchang.yoga': 'Yoga',
    'panchang.sunrise': 'Sun Rise',
    'panchang.sunset': 'Sun Set',
    'panchang.moonrise': 'Moon Rise',
    'panchang.moonset': 'Moon Set',

    // Free Services — Janam Kundali
    'kundali.enterDetails': 'Enter Your Details',
    'kundali.enterFullName': 'Enter full Name',
    'kundali.selectGender': 'Select Gender',
    'kundali.selectDob': 'Select Date of Birth',
    'kundali.selectTob': 'Select Time of Birth',
    'kundali.dontKnow': "I don't know",
    'kundali.enterPlaceOfBirth': 'Enter Place of Birth',
    'kundali.showKundali': 'Show Kundali',
    'kundali.pleaseEnterName': 'Please enter your name',
    'kundali.pleaseSelectGender': 'Please select your gender',
    'kundali.pleaseSelectDob': 'Please select your date of birth',
    'kundali.pleaseSelectTob': 'Please select your time of birth or check "I don\'t know"',
    'kundali.locationFetchError': 'Could not get location coordinates for that place. Please try selecting it again.',

    // Free Services — Kundali Match
    'match.boysDetails': "Boy's Details",
    'match.girlsDetails': "Girl's Details",
    'match.enterBoyPlace': "Enter Boy's Place of Birth",
    'match.enterGirlPlace': "Enter Girl's Place of Birth",
    'match.showReport': 'Show Report',
    'match.fillAllFields': 'Please fill in all required fields',
    'match.errorFetching': 'An error occurred while fetching the report. Please try again.',

    // Free Services — Horoscope
    'horoscope.title': '{{sign}} Horoscope',
    'horoscope.unableToFetch': 'Unable to fetch horoscope data. Please try again later.',

    // Free (₹1) services visual layer
    'free.daily': 'Daily',
    'free.monthly': 'Monthly',
    'free.yearly': 'Yearly',
    'free.fullReading': 'Daily · Monthly · Yearly',
    'free.todaysReading': 'Today\'s reading',
    'free.nakshatraDetails': 'Nakshatra Details',
    'free.doshasAndYogas': 'Doshas & Yogas',
    'free.noKundaliData': 'No Kundali data available',
    'free.birthSummary': 'Birth Summary',
    'free.sunAndMoon': 'Sun & Moon',
    'free.dayLength': 'Day length',
    'free.result': 'Result',
    'free.basicDetails': 'Basic Details',
    'free.gunaDetails': 'Guna Details',
    'free.boysDetails': 'Boy\'s Details',
    'free.girlsDetails': 'Girl\'s Details',
    'free.matchScore': 'Guna Milan Score',
    'free.choghadiya': 'Choghadiya',
    'free.shubhHora': 'Shubh Hora',
    'free.gowriPanchangam': 'Gowri Panchangam',
    'free.rahuKaal': 'Rahu Kaal',
    'free.auspicious': 'Auspicious',
    'free.inauspicious': 'Inauspicious',
    'free.neutral': 'Neutral',
    'free.now': 'Now',
    'free.noServices': 'No services available',
    'zodiac.aries': 'Aries',
    'zodiac.taurus': 'Taurus',
    'zodiac.gemini': 'Gemini',
    'zodiac.cancer': 'Cancer',
    'zodiac.leo': 'Leo',
    'zodiac.virgo': 'Virgo',
    'zodiac.libra': 'Libra',
    'zodiac.scorpio': 'Scorpio',
    'zodiac.sagittarius': 'Sagittarius',
    'zodiac.capricorn': 'Capricorn',
    'zodiac.aquarius': 'Aquarius',
    'zodiac.pisces': 'Pisces',

    // AstroServices shared
    'astro.notAvailable': 'Not available',
    'astro.notAvailableMsg': 'This report is not available right now. Please try again later.',
    'astro.reportCostsMsg': 'This report costs ₹{{price}}. Your wallet balance is ₹{{balance}}. Please recharge your wallet.',
    'astro.rechargeToView': 'Please recharge your wallet to get this report.',
    'astro.confirmPurchase': 'Confirm Purchase',
    'astro.confirmPurchaseMsg': '₹{{price}} will be debited from your wallet for {{name}}.',
    'astro.payAmount': 'Pay ₹{{price}}',
    'astro.failedToGenerate': 'Failed to generate report',
    'freeServices.costMsg': 'This service costs ₹{{price}}. Your wallet balance is ₹{{balance}}. Please recharge your wallet.',
    'freeServices.confirmMsg': '₹{{price}} will be debited from your wallet to use {{name}}.',
    'freeServices.failedToCharge': 'Failed to process payment for this service',
    'astro.enterYourBirthDetails': 'Enter Your Birth Details',
    'astro.enterBirthDetails': 'Enter Birth Details',
    'astro.getKundliReport': 'Get Kundli Report',
    'astro.getDashaReport': 'Get Dasha Report',
    'astro.getDoshReport': 'Get Dosh Report',
    'astro.getLalKitabReport': 'Get Lal Kitab Report',
    'astro.getChartReport': 'Get Chart Report',
    'astro.getNumerologyReport': 'Get Numerology Report',
    'astro.getKPReport': 'Get KP Astrology Report',
    'astro.getTarotReading': 'Get Tarot Reading',
    'astro.getPdfReport': 'Get PDF Report',
    'astro.getMatchingReport': 'Get Matching Report',
    'astro.chooseChart': 'Choose Chart',
    'astro.selectAChart': 'Select a chart',
    'astro.getChart': 'Get Chart',
    'astro.matchKundli': 'Match Kundli',
    'astro.name': 'Enter Your Name',
    'astro.phoneNumber': 'Phone Number',
    'astro.getReading': 'Get Reading',
    'astro.selectTemplate': 'Select Report Type',
    'astro.pdfPlaceOfBirth': 'Place of Birth',
    'astro.enterMobileNumber': 'Enter mobile number',
    'astro.tarotTitle': 'Yes or No Tarot Reading',
    'astro.tarotSubtitle': 'Draw a card for a quick answer to your question.',
    'astro.drawCard': 'Draw a Card',
    'astro.yourReading': 'Your Reading',
    'astro.yourDetails': 'Your Details',
    'astro.chooseReport': 'Choose Report',
    'astro.selectPdfReport': 'Select a PDF report',
    'astro.generatePdfReport': 'Generate PDF Report',

    // Result screen section titles
    'result.kundliOverview': 'Kundli Overview',
    'result.ascendantReport': 'Ascendant Report',
    'result.planetDetails': 'Planet Details',
    'result.ashtakootMatching': 'Ashtakoot Matching',
    'result.dashakootMatching': 'Dashakoot Matching',
    'result.aggregateCompatibility': 'Aggregate Compatibility',
    'result.boysMangalDosh': "Boy's Mangal Dosh",
    'result.girlsMangalDosh': "Girl's Mangal Dosh",
    'result.currentMahadasha': 'Current Mahadasha',
    'result.mahadashaTimeline': 'Mahadasha Timeline',
    'result.yoginiDashaMain': 'Yogini Dasha (Main)',
    'result.yoginiDashaSub': 'Yogini Dasha (Sub)',
    'result.mangalDosh': 'Mangal Dosh',
    'result.kaalsarpDosh': 'Kaalsarp Dosh',
    'result.manglikDosh': 'Manglik Dosh',
    'result.pitraDosh': 'Pitra Dosh',
    'result.loshuGrid': 'Loshu Grid',
    'result.nameAnalysis': 'Name Analysis',
    'result.mobileAnalysis': 'Mobile Number Analysis',
    'result.luckyThings': 'Lucky Things',
    'result.personalYear': 'Personal Year',
    'result.lalKitabHoroscope': 'Lal Kitab Horoscope',
    'result.lalKitabDebts': 'Lal Kitab Debts',
    'result.lalKitabRemedies': 'Lal Kitab Remedies',
    'result.lalKitabHouses': 'Lal Kitab Houses',
    'result.lalKitabPlanets': 'Lal Kitab Planets',
    'result.cuspDetails': 'Cusp Details',
    'result.houseSignificators': 'House Significators',
    'result.reportReady': 'Your report is ready',
    'result.tapToViewDownload': 'Tap below to view or download your PDF report.',
    'result.viewReport': 'View Report',

    // Report presentation layer (src/components/astro/*) — see HINDI_I18N_APP.md
    'report.translating': 'Translating…',
    'report.langSwitchFailed': 'Could not switch language. Please try again.',
    'report.tapToEnlarge': 'Tap the chart to enlarge and zoom',
    'report.pinchHint': 'Pinch to zoom · drag to move · double-tap to reset',
    'report.chartFailed': 'This chart could not be generated. Please try again.',
    'report.tapToZoom': 'Tap to zoom',
    'report.divisionalChart': 'Divisional chart · {{div}}',
    'report.personalYearLabel': 'Personal Year',
    'report.lagnaChart': 'Lagna Chart (D1)',
    'report.yourBirthChart': 'Your birth chart',
    'report.kundliSub': 'Birth chart, positions and attributes',
    'report.birthAttributes': 'Birth Attributes',
    'report.recommendedStones': 'Recommended Stones',
    'report.ascendant': 'Ascendant',
    'report.moonSign': 'Moon Sign',
    'report.sunSign': 'Sun Sign',
    'report.planetaryPositions': 'Planetary Positions',
    'report.positionsAtBirth': '{{count}} positions at birth',
    'report.house': 'House',
    'report.degree': 'Degree',
    'report.nakshatra': 'Nakshatra',
    'report.pada': 'Pada',
    'report.nakLord': 'Nak. Lord',
    'report.signLord': 'Sign Lord',
    'report.subLord': 'Sub Lord',
    'report.subSubLord': 'Sub-sub Lord',
    'report.position': 'Position',
    'report.nature': 'Nature',
    'report.rashi': 'Rashi',
    'report.retrograde': 'Retro',
    'report.combust': 'Combust',
    'report.luckyGem': 'Lucky Gem',
    'report.luckyNumber': 'Lucky Number',
    'report.lagnaLord': 'Lagna Lord',
    'report.placedIn': 'Placed In',
    'report.strength': 'Strength',
    'report.forYouSpecifically': 'For You Specifically',
    'report.strengths': 'Strengths',
    'report.watchOutFor': 'Watch Out For',
    'report.fastingDay': 'Fasting Day',
    'report.gayatriMantra': 'Gayatri Mantra',
    'report.flagshipQualities': 'Flagship qualities',
    'report.spiritualGuidance': 'Spiritual guidance',
    'report.additionalReadings': 'Additional readings',
    'report.doshaAnalysis': 'Dosha Analysis',
    'report.doshaAnalysisSub': 'What is present, how strong, and what to do',
    'report.atAGlance': 'At a Glance',
    'report.allFourDoshas': 'All four doshas',
    'report.present': 'Present',
    'report.notPresent': 'Not Present',
    'report.partiallyPresent': 'Partially Present',
    'report.clear': 'Clear',
    'report.doshaSummaryAffected': '{{n}} of {{total}} doshas are present in your chart: {{list}}. Remedies for each are listed below.',
    'report.doshaSummaryClear': 'None of the four doshas are present in your chart.',
    'report.intensity': 'Intensity',
    'report.sources': 'Sources',
    'report.byMars': 'By Mars',
    'report.bySaturn': 'By Saturn',
    'report.byRahuKetu': 'By Rahu/Ketu',
    'report.why': 'Why',
    'report.aspects': 'Aspects',
    'report.effects': 'Effects',
    'report.remedies': 'Remedies',
    'report.cancellationScore': 'Cancellation score {{score}}',
    'report.kundaliMatching': 'Kundali Matching',
    'report.matchingSub': 'Compatibility, doshas and remedies',
    'report.overallCompatibility': 'Overall Compatibility',
    'report.everythingWeighed': 'Everything weighed together',
    'report.matchScore': 'Match Score',
    'report.totalGuna': 'Total Guna',
    'report.compatibility': 'Compatibility',
    'report.verdict': 'Verdict',
    'report.excellent': 'Excellent',
    'report.average': 'Average',
    'report.low': 'Low',
    'report.pointByPoint': 'Point-by-point compatibility',
    'report.doshaComparison': 'Dosha Comparison',
    'report.whatEachDosha': 'What each dosha means here',
    'report.detailedReading': 'Detailed reading',
    'report.boy': 'Boy',
    'report.girl': 'Girl',
    'report.yes': 'Yes',
    'report.no': 'No',
    'report.rajjuDosha': 'Rajju Dosha',
    'report.vedhaDosha': 'Vedha Dosha',
    'report.mangalDosha': 'Mangal Dosha',
    'report.pitraDosha': 'Pitra Dosha',
    'report.kaalSarpDosha': 'Kaal Sarp Dosha',
    'report.manglikSaturn': 'Manglik by Saturn',
    'report.manglikRahuKetu': 'Manglik by Rahu/Ketu',
    'report.dashaSub': 'Planetary periods across your life',
    'report.periods': '{{count}} periods',
    'report.now': 'Now',
    'report.birth': 'Birth',
    'report.earlierPeriods': 'Earlier periods',
    'report.laterPeriods': 'Later periods',
    'report.currentlyRunning': 'Currently running: {{name}} — until {{end}}',
    'report.runningNow': 'Running Right Now',
    'report.runningNowSub': 'Your five active dasha levels, outermost first',
    'report.majorPeriod': 'Major period',
    'report.subPeriod': 'Sub period',
    'report.subSubPeriod': 'Sub-sub period',
    'report.finerPeriod': 'Finer period',
    'report.finestPeriod': 'Finest period',
    'report.majorPeriods': 'Major periods',
    'report.withinMahadasha': 'Within the current Mahadasha',
    'report.withinAntardasha': 'Within the current Antardasha',
    'report.vimshottariSequence': 'Vimshottari sequence',
    'report.yoginiMajor': 'Yogini major periods',
    'report.yoginiSub': 'Yogini sub periods',
    'report.subPeriodsWithin': 'Sub periods within {{name}}',
    'report.yr': 'yr',
    'report.mo': 'mo',
    'report.numerologyReport': 'Numerology Report',
    'report.numerologySub': 'Your numbers, name, and lucky things',
    'report.yourNumbers': 'Your Numbers',
    'report.loShuGrid': 'Lo Shu Grid',
    'report.loShuHint': 'Filled cells are the digits present in your date of birth; faded cells are missing.',
    'report.missing': 'Missing',
    'report.planeStrengths': 'Plane Strengths',
    'report.numberSum': 'Number Sum',
    'report.favourable': 'Favourable',
    'report.notFavourable': 'Not Favourable',
    'report.digitMeanings': 'Digit Meanings',
    'report.fullName': 'Full Name',
    'report.firstName': 'First Name',
    'report.suggestedSpellings': 'Suggested name spellings',
    'report.luckyForYou': 'Lucky For You',
    'report.rulingPlanet': 'Ruling Planet',
    'report.element': 'Element',
    'report.bestTime': 'Best Time',
    'report.traits': 'Traits',
    'report.favourablePeriods': 'Favourable Periods',
    'report.luckFactor': 'Luck Factor',
    'report.lalKitabReport': 'Lal Kitab Report',
    'report.lalKitabSub': 'Chart, houses, debts and remedies',
    'report.lalKitabChart': 'Lal Kitab Chart',
    'report.planetsBySign': 'Planets by sign',
    'report.housesKhana': 'Houses (Khana)',
    'report.khanas': '{{count}} khanas',
    'report.lord': 'Lord',
    'report.sleeping': 'Sleeping',
    'report.pakkaGhar': 'Pakka Ghar',
    'report.kismat': 'Kismat',
    'report.planetRemedies': 'Planet Remedies',
    'report.tapPlanet': 'Tap a planet to read its effects and remedies',
    'report.karmicDebts': 'Karmic Debts (Rin)',
    'report.noDebts': 'No karmic debts found in your chart.',
    'report.found': '{{count}} found',
    'report.indications': 'Indications',
    'report.possibleEvents': 'Possible events',
    'report.kpSub': 'Krishnamurti Paddhati chart and significators',
    'report.cuspSub': 'Sign, star and sub lord per house',
    'report.sign': 'Sign',
    'report.star': 'Star',
    'report.sub': 'Sub',
    'report.subSub': 'Sub-sub',
    'report.significatorsSub': 'Planets signifying each house',
  },
  Hindi: {
    // Home
    'home.welcome': 'एस्ट्रोवाणी में आपका स्वागत है!',
    'home.search': 'यहाँ खोजें',
    'home.bestAstrologers': 'भारत के सर्वश्रेष्ठ ज्योतिषी',
    'home.callWithAstrologers': 'ज्योतिषी से कॉल करें',
    'home.viewAll': 'सभी देखें',
    'home.remedies': 'एस्ट्रोवाणी के उपाय',
    'home.bookPuja': 'वीआईपी पूजा बुक करें',
    'home.buyGemstones': 'रत्न खरीदें',
    'home.readMore': 'और पढ़ें',
    'home.categories': 'एस्ट्रोवाणी की श्रेणियाँ',
    'home.liveAstrologers': 'लाइव ज्योतिषी',
    'home.noOneLive': 'अभी कोई ज्योतिषी लाइव नहीं है',
    'home.freeServices': '₹1 सेवाएँ',
    'home.astroReports': 'ज्योतिष रिपोर्ट',
    'home.blog': 'एस्ट्रोवाणी ब्लॉग',
    'home.whatClientsSay': 'हमारे ग्राहक क्या कहते हैं',
    'home.discoverTrust': 'जानिए क्यों हज़ारों लोग एस्ट्रोवाणी पर भरोसा करते हैं',
    'home.whyBest': 'ज्योतिष के लिए एस्ट्रोवाणी सबसे बेहतर क्यों है?',
    'home.whyBestBody': 'एस्ट्रोवाणी उस नियति को उजागर करता है जो सितारों ने हमारे लिए तय की है। एस्ट्रोवाणी अपनी विधियों और सितारों व ग्रहों के पृथ्वी पर प्रभाव तथा मानव नियति की व्याख्या करने के तरीके के साथ एक सिद्ध विज्ञान है। घटनाओं की गणना और भविष्यवाणी की अपनी वैज्ञानिक पद्धति के साथ, एस्ट्रोवाणी लोगों को इस पर विश्वास करना शुरू करने के लिए पर्याप्त प्रमाणित करता है। और यह प्रारंभिक वैदिक काल से ही ऐसा करता आ रहा है।',
    'home.noReviews': 'अभी तक कोई समीक्षा उपलब्ध नहीं है।',
    'home.requestSent': 'अनुरोध भेजा गया',
    'home.waitingFor': '{{name}} के आपके अनुरोध को स्वीकार करने की प्रतीक्षा की जा रही है...',
    'home.cancelRequest': 'अनुरोध रद्द करें',
    'home.chatWithAstrologer': 'ज्योतिषी से चैट करें',
    'home.talkToAstrologer': 'ज्योतिषी से बात करें',
    'home.guideHint': 'क्या करना है समझ नहीं आ रहा? अपनी पहली चैट शुरू करें!',

    // Common labels / actions
    'common.chat': 'चैट',
    'common.call': 'कॉल',
    'common.video': 'वीडियो',
    'common.noChat': 'चैट उपलब्ध नहीं',
    'common.noCall': 'कॉल उपलब्ध नहीं',
    'common.noVideo': 'वीडियो उपलब्ध नहीं',
    'common.offline': 'ऑफ़लाइन',
    'common.live': 'लाइव',
    'common.scheduled': 'निर्धारित',
    'common.home': 'होम',
    'common.wallet': 'वॉलेट',
    'common.profile': 'मेरी प्रोफ़ाइल',
    'common.cancel': 'रद्द करें',
    'common.ok': 'ठीक है',
    'common.error': 'त्रुटि',
    'common.language': 'भाषा चुनें',

    // Alerts
    'alerts.unavailable': 'अनुपलब्ध',
    'alerts.notAvailableChat': '{{name}} अभी चैट के लिए उपलब्ध नहीं है।',
    'alerts.notAvailableCall': '{{name}} अभी कॉल के लिए उपलब्ध नहीं है।',
    'alerts.notAvailableVideo': '{{name}} अभी वीडियो कॉल के लिए उपलब्ध नहीं है।',
    'alerts.astrologerOffline': '{{name}} अभी ऑफ़लाइन है। कृपया बाद में देखें।',
    'alerts.astrologerBusy': 'ज्योतिषी अभी व्यस्त हैं। कृपया कुछ समय बाद पुनः प्रयास करें।',
    'alerts.selfBusy': 'आपकी पहले से ही एक सक्रिय या लंबित कॉल/चैट चल रही है। कृपया पहले उसे समाप्त करें।',
    'alerts.notPickedUpAudio': 'आपकी ऑडियो कॉल का जवाब नहीं दिया गया। कृपया बाद में पुनः प्रयास करें।',
    'alerts.notPickedUpVideo': 'आपकी वीडियो कॉल का जवाब नहीं दिया गया। कृपया बाद में पुनः प्रयास करें।',
    'alerts.insufficientBalance': 'अपर्याप्त बैलेंस',
    'alerts.failedWalletCheck': 'वॉलेट बैलेंस जांचा नहीं जा सका — कृपया अपना इंटरनेट कनेक्शन जांचें और पुनः प्रयास करें।',
    'alerts.failedRequestAstrologer': 'ज्योतिषी को अनुरोध भेजने में विफल।',
    'alerts.failedInitiateCall': 'कॉल शुरू करने में विफल',
    'alerts.failedInitiateVideoCall': 'वीडियो कॉल शुरू करने में विफल',

    // Drawer
    'drawer.myWallet': 'मेरा वॉलेट',
    'drawer.mySessions': 'मेरे सत्र',
    'drawer.remedies': 'उपाय',
    'drawer.chatWithAstrologer': 'ज्योतिषी से चैट करें',
    'drawer.blogs': 'एस्ट्रोवाणी ब्लॉग',
    'drawer.myFavorites': 'मेरे पसंदीदा',
    'drawer.myOrders': 'मेरे ऑर्डर',
    'drawer.voiceNotes': 'वॉइस नोट्स',
    'drawer.referFriend': 'मित्र को आमंत्रित करें',
    'drawer.settings': 'सेटिंग्स',
    'drawer.support': 'सहायता',
    'drawer.shareApp': 'ऐप शेयर करें',
    'drawer.logout': 'लॉग आउट',
    'drawer.connectWithUs': 'हमसे जुड़ें',
    'drawer.welcome': 'स्वागत है!',
    'drawer.updateProfile': 'अपनी प्रोफ़ाइल अपडेट करें',

    // Settings
    'settings.aboutUs': 'हमारे बारे में',
    'settings.faqs': 'सामान्य प्रश्न',
    'settings.refundCancellation': 'धनवापसी और रद्दीकरण',
    'settings.privacyPolicy': 'गोपनीयता नीति',
    'settings.termsOfUse': 'उपयोग की शर्तें',
    'settings.childSafety': 'बाल सुरक्षा',
    'settings.safetyGuidelines': 'सुरक्षा दिशा-निर्देश',
    'settings.reportVulnerability': 'भेद्यता की रिपोर्ट करें',
    'settings.deleteAccount': 'मेरा खाता हटाएं',
    'settings.confirmLogoutTitle': 'लॉग आउट की पुष्टि करें',
    'settings.confirmLogoutMsg': 'क्या आप वाकई लॉग आउट करना चाहते हैं?',
    'settings.confirmDeleteTitle': 'हटाने की पुष्टि करें',
    'settings.confirmDeleteMsg': 'क्या आप वाकई अपना खाता हटाना चाहते हैं? एक बार हटाने के बाद, आपका सहेजा गया सारा इतिहास खो जाएगा। क्या आप फिर भी जारी रखना चाहते हैं?',
    'settings.deleteBtn': 'हटाएं',
    'settings.accountDeleted': 'खाता सफलतापूर्वक हटा दिया गया',
    'settings.loggedOut': 'सफलतापूर्वक लॉग आउट हो गया',

    // Login / OTP
    'login.tagline': 'सर्वश्रेष्ठ ज्योतिषियों की टीम',
    'login.discoverPath': 'अपना ब्रह्मांडीय पथ खोजें',
    'login.phoneNumber': 'फ़ोन नंबर',
    'login.continue': 'जारी रखें',
    'login.agreeTerms': 'साइन अप करके, आप हमारी ',
    'login.and': ' और ',
    'login.noAccount': 'खाता नहीं है? ',
    'login.register': 'पंजीकरण करें',
    'login.selectCountry': 'देश चुनें',
    'login.close': 'बंद करें',
    'login.validationError': 'सत्यापन त्रुटि',
    'login.phoneEmpty': 'फ़ोन नंबर खाली नहीं हो सकता।',
    'login.phoneTooShort': 'फ़ोन नंबर कम से कम 10 अंकों का होना चाहिए।',
    'login.otpFailed': 'OTP भेजा नहीं जा सका। कृपया पुनः प्रयास करें।',
    'login.noAccountTitle': 'खाता नहीं मिला',
    'login.noAccountMsg': 'हमें इस नंबर के लिए कोई खाता नहीं मिला। कृपया पहले साइन अप करें।',
    'login.somethingWrong': 'कुछ गलत हो गया। कृपया पुनः प्रयास करें।',
    'login.guideHint': 'पहली बार यहाँ आए हैं? पंजीकरण करने के लिए टैप करें!',

    // Remedies (static home tiles)
    'remedies.puja': 'पूजा',
    'remedies.gemstones': 'रत्न',
    'remedies.specificPuja': 'विशिष्ट पूजा',
    'remedies.lifeReports': 'जीवन रिपोर्ट',
    'remedies.buyNow': 'अभी खरीदें',
    'pujaDetail.pujaSold': 'पूजा बेची गई',
    'pujaDetail.details': 'विवरण:',
    'pujaDetail.duration': 'अवधि',
    'pujaDetail.godGoddess': 'पूजा के देवी-देवता',
    'pujaDetail.location': 'स्थान',
    'pujaDetail.date': 'तारीख',
    'pujaDetail.benefits': 'लाभ:',
    'pujaDetail.groupPuja': 'समूह पूजा',
    'pujaDetail.bookNow': 'अभी बुक करें',
    'pujaDetail.bookingTitle': 'बुकिंग',
    'pujaDetail.bookingMsg': 'पूजा बुक की जा रही है...',
    'gemstone.carats': 'कैरेट',
    'common.errorPrefix': 'त्रुटि:',

    'refer.title': 'रेफर करें और कमाएं',
    'refer.subtitle': 'दोस्तों को एस्ट्रोवाणी में आमंत्रित करें और दोनों जीतें',
    'refer.getPerFriend': 'प्रति मित्र ₹{{amount}} पाएं',
    'refer.friendsReferred': 'रेफर किए गए मित्र',
    'refer.totalEarned': 'कुल कमाई',
    'refer.yourCode': 'आपका रेफरल कोड',
    'refer.copy': 'कॉपी करें',
    'refer.shareInfo': 'यह कोड शेयर करें — जब आपका मित्र अपना पहला सत्र पूरा करता है तो आप ₹{{amount}} कमाते हैं',
    'refer.viaWhatsapp': 'व्हाट्सएप के माध्यम से रेफर करें',
    'refer.viaOtherApps': 'अन्य ऐप्स के माध्यम से शेयर करें',
    'refer.howItWorks': 'यह कैसे काम करता है',
    'refer.step1': 'आपका मित्र आपके रेफरल कोड का उपयोग करके एस्ट्रोवाणी पर साइन अप करता है।',
    'refer.step2': 'जब वे अपना पहला चैट, कॉल या वीडियो सत्र पूरा करते हैं तो आपको ₹{{amount}} मिलते हैं।',
    'refer.copiedTitle': 'क्लिपबोर्ड पर कॉपी किया गया',
    'refer.copiedMsg': 'रेफरल कोड {{code}} कॉपी किया गया!',
    'refer.whatsappNotInstalled': 'व्हाट्सएप इंस्टॉल नहीं है',

    'orders.typePuja': 'पूजा',
    'orders.typeGemstone': 'रत्न',
    'orders.typeSpecificPuja': 'विशिष्ट पूजा',
    'orders.typeLifeReport': 'जीवन रिपोर्ट',
    'orders.reportDelivered': 'रिपोर्ट भेज दी गई — देखने के लिए टैप करें',
    'orders.reportPending': 'आपकी रिपोर्ट तैयार की जा रही है…',
    'orders.noOrders': 'अभी तक कोई ऑर्डर नहीं।',
    'orders.close': 'बंद करें',

    'favorites.empty': 'अभी तक कोई पसंदीदा नहीं।\nयहां जोड़ने के लिए किसी ज्योतिषी की प्रोफ़ाइल पर दिल पर टैप करें।',

    'support.issueTechnical': 'तकनीकी समस्या',
    'support.issueAccount': 'खाता संबंधी समस्या',
    'support.issueRefund': 'रिफंड अनुरोध',
    'support.issueOther': 'अन्य',
    'support.issueFeedback': 'प्रतिक्रिया',
    'support.title': 'कोई प्रश्न है?',
    'support.subtitle': 'हमें मदद करके खुशी होगी। हमें अपनी समस्या बताएं और हम जल्द से जल्द आपसे संपर्क करेंगे।',
    'support.enterName': 'अपना नाम दर्ज करें',
    'support.email': 'ईमेल',
    'support.mobileNumber': 'मोबाइल नंबर',
    'support.selectIssue': 'समस्या चुनें',
    'support.writeMessage': 'यहां अपना संदेश लिखें',
    'support.submit': 'सबमिट करें',
    'support.fillAllFields': 'कृपया सबमिट करने से पहले सभी फ़ील्ड भरें।',
    'support.submittedSuccess': 'सहायता अनुरोध सफलतापूर्वक सबमिट किया गया!',

    'voiceNotes.noNotes': 'अभी तक कोई वॉइस नोट नहीं।',

    'expertsList.liveNow': 'अभी लाइव',
    'expertsList.notifyTitle': 'हम आपको बताएंगे',
    'expertsList.notifyMsg': 'जब {{name}} खाली होंगे तो हम आपको सूचित करेंगे।',
    'expertsList.notifyFailed': 'प्रतीक्षा सूची में शामिल नहीं हो सके। कृपया पुनः प्रयास करें।',
    'expertsList.noneFound': 'कोई ज्योतिषी नहीं मिला।',
    'expertsList.failedSendCallRequest': 'कॉल अनुरोध भेजने में विफल।',
    'common.noDataAvailable': 'कोई डेटा उपलब्ध नहीं',
    'common.customer': 'ग्राहक',
    'common.success': 'सफलता',

    'addReview.title': '{{name}} की समीक्षा करें',
    'addReview.ratingRequired': 'कृपया एक रेटिंग दें।',
    'addReview.commentRequired': 'कृपया एक समीक्षा टिप्पणी लिखें।',
    'addReview.submittedMsg': 'आपकी समीक्षा सफलतापूर्वक सबमिट कर दी गई है!',
    'addReview.failedSubmit': 'समीक्षा सबमिट करने में विफल।',
    'addReview.placeholder': 'अपना अनुभव लिखें...',
    'addReview.submit': 'समीक्षा सबमिट करें',

    'review.getBestSolutions': 'सर्वोत्तम समाधान पाएं',
    'review.forAstrologer': '{{name}} के लिए',

    'voiceNotesBanner.newNote': '{{name}} से नया वॉइस नोट',
    'voiceNotesBanner.subtitle': 'सुनने के लिए टैप करें — वे आपका हाल-चाल पूछ रहे हैं',

    'liveAarti.title': 'लाइव आरती / पूजा',

    'gemBuy.buy': 'खरीदें',
    'gemBuy.messageFor': '{{name}} के लिए संदेश',
    'gemBuy.enterMessage': 'अपना संदेश दर्ज करें',
    'gemBuy.purchase': 'खरीद',
    'gemBuy.inquiry': 'पूछताछ',
    'gemBuy.submit': 'सबमिट करें',
    'gemBuy.close': 'बंद करें',
    'gemBuy.paymentSuccessful': 'भुगतान सफल',
    'gemBuy.paymentId': 'भुगतान आईडी: {{id}}',
    'gemBuy.paymentFailed': 'भुगतान विफल',

    'walletHistory.noTransaction': 'कोई लेनदेन नहीं',
    'walletHistory.addMoney': 'पैसे जोड़ें',

    'freeBotChat.freeChat': 'मुफ्त चैट',
    'freeBotChat.freeBanner': 'आपकी मुफ्त 5-मिनट की स्वागत चैट — पूरी तरह मुफ्त',
    'freeBotChat.messagePlaceholder': 'संदेश लिखें…',
    'freeBotChat.completeTitle': 'चैट पूर्ण!',
    'freeBotChat.completeMsg': 'हमसे चैट करने के लिए धन्यवाद! जब भी तैयार हों, किसी भी ज्योतिषी से असली चैट शुरू करें।',
    'freeBotChat.greatThanks': 'बढ़िया, धन्यवाद!',

    'splash.tagline': 'ऑनलाइन ज्योतिषियों से परामर्श करें',

    'call.pleaseLogin': 'जारी रखने के लिए कृपया लॉगिन करें।',
    'call.audioCall': 'ऑडियो कॉल',
    'call.videoCall': 'वीडियो कॉल',
    'call.connecting': 'कनेक्ट हो रहा है...',
    'call.ringing': 'रिंग हो रहा है... {{seconds}}s',
    'call.mute': 'म्यूट करें',
    'call.unmute': 'अनम्यूट करें',
    'call.camera': 'कैमरा',
    'call.videoOff': 'वीडियो बंद',
    'call.flip': 'पलटें',
    'call.speaker': 'स्पीकर',
    'call.earpiece': 'ईयरपीस',
    'call.endCallTitle': 'कॉल समाप्त करें',
    'call.endCallMsg': 'क्या आप वाकई कॉल समाप्त करना चाहते हैं?',
    'call.end': 'समाप्त करें',
    'call.permissionRequired': 'अनुमति आवश्यक है',
    'call.micPermissionMsg': 'ऑडियो कॉल के लिए माइक्रोफ़ोन एक्सेस आवश्यक है।',
    'call.micCameraPermissionMsg': 'वीडियो कॉल के लिए माइक्रोफ़ोन और कैमरा एक्सेस आवश्यक है।',
    'call.inProgress': 'कॉल चल रही है',
    'call.stillActive': '{{name}} के साथ आपकी कॉल अभी भी सक्रिय है। वापस जाने के लिए टैप करें।',
    'call.videoInProgress': 'वीडियो कॉल चल रही है',
    'call.videoStillActive': '{{name}} के साथ आपकी वीडियो कॉल अभी भी सक्रिय है। वापस जाने के लिए टैप करें।',

    'chatSession.sessionEnded': 'सत्र समाप्त',
    'chatSession.endChatTitle': 'चैट समाप्त करें',
    'chatSession.endChatMsg': 'वापस जाने से यह चैट सत्र समाप्त हो जाएगा। क्या आप वाकई चैट समाप्त करना चाहते हैं?',
    'chatSession.end': 'समाप्त करें',
    'chatSession.typing': 'टाइप कर रहे हैं...',
    'chatSession.connecting': 'कनेक्ट हो रहा है…',
    'chatSession.waitingForAccept': 'ज्योतिषी के स्वीकार करने की प्रतीक्षा की जा रही है…',
    'chatSession.messagePlaceholder': 'संदेश लिखें…',
    'chatSession.inProgress': 'चैट चल रही है',
    'chatSession.stillActive': '{{name}} के साथ आपकी चैट अभी भी सक्रिय है। वापस जाने के लिए टैप करें।',
    'chatSession.astrologerEnded': 'ज्योतिषी ने सत्र समाप्त कर दिया है।',

    // ReusableList shared card
    'common.viewProfile': 'प्रोफ़ाइल',
    'common.free': 'मुफ़्त',
    'common.exp': 'अनुभव',
    'common.yrs': 'वर्ष',
    'common.searchAstrologer': 'नाम या कौशल से ज्योतिषी खोजें...',
    'alerts.failedGenerateRoom': 'कॉल रूम बनाने में विफल।',
    'alerts.declined': 'अस्वीकृत',
    'alerts.declinedBusy': '{{name}} अभी व्यस्त हैं और उन्होंने कॉल अस्वीकार कर दी।',
    'video.waitingFor': '{{name}} के आपकी वीडियो कॉल स्वीकार करने की प्रतीक्षा की जा रही है...',

    // Chat request hook
    'chat.pleaseLogIn': 'कृपया पहले लॉग इन करें।',
    'chat.sessionInvalid': 'सत्र अमान्य है। कृपया लॉग आउट करें और पुनः लॉग इन करें।',
    'chat.astrologerInfoMissing': 'ज्योतिषी की जानकारी गायब है। कृपया ताज़ा करें और पुनः प्रयास करें।',
    'chat.lowBalance': 'कम बैलेंस',
    'chat.lowBalanceMsg': 'चैट शुरू करने के लिए आपको कम से कम ₹{{charge}} चाहिए। कृपया अपना वॉलेट रीचार्ज करें।',
    'chat.couldNotSendRequest': 'अनुरोध नहीं भेजा जा सका: {{msg}}',
    'chat.notPickedUp': 'आपके चैट अनुरोध का जवाब नहीं दिया गया। कृपया बाद में पुनः प्रयास करें।',
    'status.astrologerBusyTitle': 'ज्योतिषी व्यस्त हैं',
    'status.youAreBusyTitle': 'पहले से सत्र में हैं',
    'status.notAnsweredTitle': 'कोई जवाब नहीं',

    // Live tab
    'live.watching': 'देख रहे हैं',
    'live.joinNow': 'अभी जुड़ें',
    'live.searchPlaceholder': 'लाइव सत्र खोजें...',
    'live.noneLive': 'अभी कोई ज्योतिषी लाइव नहीं है।',
    'live.connectingToLive': 'लाइव से कनेक्ट हो रहा है…',
    'live.waitingForVideo': 'वीडियो की प्रतीक्षा की जा रही है…',
    'live.ended': 'लाइव समाप्त हुआ',
    'live.endedMsg': '{{name}} ने लाइव समाप्त कर दिया है।',
    'live.theAstrologer': 'ज्योतिषी',
    'live.sayPlaceholder': 'कुछ कहें…',
    'live.someone': 'किसी ने',
    'live.sent': 'भेजा',
    'live.guest': 'अतिथि',

    // AstrologerInfo profile screen
    'profile.new': 'नया',
    'profile.yrs': 'वर्ष',
    'profile.gift': 'उपहार',
    'profile.off': 'बंद',
    'profile.specialization': 'विशेषज्ञता',
    'profile.aboutServices': 'मेरी सेवाओं के बारे में',
    'profile.aboutFallback': 'अनुभवी और पेशेवर ज्योतिषी जो आपकी जीवन यात्रा में मार्गदर्शन के लिए यहाँ हैं।',
    'profile.readLess': 'कम पढ़ें',
    'profile.experienceQualification': 'अनुभव और योग्यता',
    'profile.experienceBody': 'कई वर्षों के समर्पित अभ्यास के साथ, मैंने {{specialties}} में अपने कौशल को निखारा है।',
    'profile.sendAGift': 'उपहार भेजें',
    'profile.clientReviews': 'ग्राहक समीक्षाएँ',
    'profile.reviewsOnAstrowani': 'एस्ट्रोवाणी पर {{count}} समीक्षाएँ',
    'profile.noReviewsYet': 'अभी तक कोई समीक्षा नहीं है।',
    'profile.showAll': 'सभी देखें',
    'profile.writeReview': '+ समीक्षा लिखें',
    'profile.astrowaniReplyPrefix': '↳ एस्ट्रोवाणी: ',

    // OTP screens
    'otp.sentToNumber': 'आपके नंबर पर OTP भेजा गया',
    'otp.expiresIn': 'OTP {{time}} में समाप्त होगा',
    'otp.verifyBtn': 'OTP सत्यापित करें',
    'otp.notReceived': 'OTP प्राप्त नहीं हुआ? ',
    'otp.resend': 'OTP पुनः भेजें',
    'otp.invalidTryAgain': 'अमान्य OTP। कृपया पुनः प्रयास करें।',
    'otp.failedVerify': 'OTP सत्यापित करने में विफल। कृपया पुनः प्रयास करें।',
    'otp.verifyTitle': 'अपना नंबर सत्यापित करें',
    'otp.enterCodeSentTo': '6 अंकों का कोड दर्ज करें जो भेजा गया ',
    'otp.yourNumber': 'आपके नंबर पर',
    'otp.almostThere': 'बस थोड़ा और!',
    'otp.resendIn': '{{time}} में OTP पुनः भेजें',
    'otp.sending': 'भेजा जा रहा है...',
    'otp.changeNumber': 'फ़ोन नंबर बदलें',
    'otp.invalidOtpTitle': 'अमान्य OTP',
    'otp.enterComplete': 'कृपया पूरा 6 अंकों का कोड दर्ज करें।',
    'otp.verificationFailed': 'सत्यापन विफल',
    'otp.otpSentTitle': 'OTP भेजा गया',
    'otp.newCodeSent': 'आपके नंबर पर एक नया कोड भेजा गया है।',
    'otp.couldNotResend': 'OTP पुनः नहीं भेजा जा सका।',
    'otp.couldNotResendRetry': 'OTP पुनः नहीं भेजा जा सका। कृपया पुनः प्रयास करें।',

    // About Us
    'about.tagline': 'सर्वश्रेष्ठ ज्योतिषियों की टीम',
    'about.title': 'हमारे बारे में',
    'about.p1': 'एस्ट्रोवाणी ज्योतिष के प्राचीन विज्ञान का आपका विश्वसनीय प्रवेशद्वार है, जो आधुनिक तकनीक की सुविधा के साथ प्रस्तुत किया गया है। हमारा मिशन व्यक्तिगत ज्योतिषीय मार्गदर्शन के माध्यम से आपको स्पष्टता, दिशा और मानसिक शांति खोजने में मदद करना है।',
    'about.p2': 'हम पूरे भारत से अत्यधिक अनुभवी और सत्यापित ज्योतिषियों की एक टीम के साथ काम करते हैं, जिनमें से प्रत्येक वैदिक ज्योतिष, अंकशास्त्र, हस्तरेखा विज्ञान, टैरो रीडिंग और अन्य में विशेषज्ञ हैं। चाहे आप करियर, रिश्तों, स्वास्थ्य या वित्त के बारे में जवाब खोज रहे हों, हमारे विशेषज्ञ करुणा और सटीकता के साथ आपका मार्गदर्शन करने के लिए यहाँ हैं।',
    'about.p3': 'एस्ट्रोवाणी में, हम मानते हैं कि ज्योतिष विनाश की भविष्यवाणी करने या आपके भाग्य को निर्धारित करने के बारे में नहीं है, बल्कि आपको सूचित निर्णय लेने के लिए सशक्त बनाने के बारे में है। हमारे परामर्श प्रामाणिकता, नैतिकता और गोपनीयता में निहित हैं, यह सुनिश्चित करते हुए कि आपका व्यक्तिगत विवरण और रीडिंग निजी रहें।',
    'about.p4': 'लाइव परामर्श, चैट सत्र और दैनिक राशिफल जैसी सुविधाओं के साथ, एस्ट्रोवाणी कभी भी, कहीं भी सही विशेषज्ञ से जुड़ना आसान बनाता है। चाहे आप विश्वासी हों या सिर्फ जिज्ञासु, हम आपका स्वागत करते हैं कि सितारों को क्या कहना है, यह जानने के लिए।',
    'about.p5': 'हजारों संतुष्ट उपयोगकर्ताओं में शामिल हों जिन्होंने एस्ट्रोवाणी के माध्यम से मार्गदर्शन, प्रेरणा और सकारात्मकता की खोज की है — जहाँ परंपरा भरोसे से मिलती है।',

    // FAQ
    'faq.title': 'अक्सर पूछे जाने वाले प्रश्न',
    'faq.q1': 'मैं एक ज्योतिषी से चैट करना चाहता हूँ। मैं कैसे शुरू करूँ?',
    'faq.a1': 'ज्योतिषी से चैट करने के लिए, आपको बस अपने एस्ट्रोवाणी खाते में लॉगिन करना है या खाता बनाने के लिए साइन अप करना है, अपने वॉलेट में पैसे जोड़ने हैं, और फिर बस उस ज्योतिषी को चुनें जिससे आप चैट करना चाहते हैं और अपना सत्र शुरू करें।',
    'faq.q2': 'क्या ज्योतिषी से परामर्श शुरू करने से पहले न्यूनतम बैलेंस की कोई आवश्यकता है?',
    'faq.a2': 'एस्ट्रोवाणी पर ज्योतिषी से परामर्श शुरू करने के लिए आपके पास कम से कम $10 का बैलेंस होना चाहिए।',
    'faq.q3': 'क्या ज्योतिषी सत्यापित हैं?',
    'faq.a3': 'हाँ, एस्ट्रोवाणी पर सभी ज्योतिषी वर्षों के अनुभव वाले सत्यापित पेशेवर हैं।',
    'faq.q4': 'अगर चैट के बीच मुझे फ़ोन कॉल आती है, तो क्या यह मेरा सत्र स्वतः समाप्त कर देगा?',
    'faq.a4': 'नहीं, फ़ोन कॉल आने पर आपका सत्र स्वतः समाप्त नहीं होगा। चैट रुक जाएगी, और कॉल समाप्त होने के बाद आप फिर से शुरू कर सकते हैं।',

    // Wallet
    'wallet.invalidAmount': 'अमान्य राशि',
    'wallet.enterValidAmount': 'कृपया रीचार्ज करने के लिए एक मान्य राशि दर्ज करें।',
    'wallet.paymentSuccessful': 'भुगतान सफल',
    'wallet.paymentId': 'भुगतान आईडी: {{id}}',
    'wallet.paymentFailed': 'भुगतान विफल',
    'wallet.addMoney': 'वॉलेट में पैसे जोड़ें',
    'wallet.rechargeSubtitle': 'विशेषज्ञों से बात करने के लिए आसानी से रीचार्ज करें',
    'wallet.enterAmount': 'राशि दर्ज करें',
    'wallet.recommendedAmounts': 'अनुशंसित राशियाँ',
    'wallet.totalPayable': 'कुल देय राशि',
    'wallet.proceedToPay': 'भुगतान करने के लिए आगे बढ़ें',
    'wallet.processing': 'प्रोसेस हो रहा है…',

    // Register screen
    'register.title': 'पंजीकरण',
    'register.tapToAddPhoto': 'फ़ोटो जोड़ने के लिए टैप करें',
    'register.fillInfoNote': 'ज्योतिषी के लिए जानकारी भरें',
    'register.takePhoto': 'फ़ोटो लें',
    'register.chooseFromLibrary': 'लाइब्रेरी से चुनें',
    'register.fullName': 'अपना पूरा नाम दर्ज करें',
    'register.male': 'पुरुष',
    'register.female': 'महिला',
    'register.other': 'अन्य',
    'register.selectGender': 'अपना लिंग चुनें',
    'register.placeOfBirth': 'अपना जन्म स्थान दर्ज करें',
    'register.mobileNumber': 'अपना 10 अंकों का मोबाइल नंबर दर्ज करें',
    'register.emailAddress': 'अपना ईमेल पता दर्ज करें',
    'register.sendingOtp': 'OTP भेजा जा रहा है…',
    'register.submit': 'जमा करें',
    'register.fillNameMobile': 'कृपया कम से कम अपना नाम और मोबाइल नंबर भरें।',
    'register.validMobile': 'कृपया एक मान्य 10 अंकों का मोबाइल नंबर दर्ज करें।',
    'register.accountExists': 'खाता पहले से मौजूद है',
    'register.accountExistsMsg': 'इस नंबर के लिए पहले से एक खाता मौजूद है। कृपया इसके बजाय लॉग इन करें।',
    'register.cameraPermTitle': 'कैमरा अनुमति',
    'register.cameraPermMsg': 'इस ऐप को आपके कैमरे तक पहुंच की आवश्यकता है',
    'register.askLater': 'मुझसे बाद में पूछें',

    // Email OTP screen
    'emailOtp.sentToEmail': 'आपके ईमेल पर OTP भेजा गया',
    'emailOtp.loginFailed': 'लॉगिन विफल',
    'emailOtp.loginError': 'लॉगिन त्रुटि',
    'emailOtp.somethingWrong': 'कुछ गलत हो गया। कृपया पुनः प्रयास करें।',

    // User Profile screen
    'userProfile.personalInfo': 'व्यक्तिगत जानकारी',
    'userProfile.palmHandPhoto': 'हथेली/हाथ की फ़ोटो',
    'userProfile.removePhoto': 'फ़ोटो हटाएं',
    'userProfile.basicDetails': 'बुनियादी जानकारी',
    'userProfile.fullName': 'पूरा नाम',
    'userProfile.mobileNumber': 'मोबाइल नंबर',
    'userProfile.emailAddress': 'ईमेल पता',
    'userProfile.gender': 'लिंग',
    'userProfile.married': 'विवाहित',
    'userProfile.unmarried': 'अविवाहित',
    'userProfile.maritalStatus': 'वैवाहिक स्थिति',
    'userProfile.birthDetails': 'जन्म विवरण',
    'userProfile.dateOfBirth': 'जन्म तिथि',
    'userProfile.timeOfBirth': 'जन्म समय',
    'userProfile.location': 'स्थान',
    'userProfile.cityPlaceOfBirth': 'शहर (जन्म स्थान)',
    'userProfile.state': 'राज्य',
    'userProfile.enterField': '{{field}} दर्ज करें',
    'userProfile.selectField': '{{field}} चुनें',
    'userProfile.uploadPalmPhoto': 'हथेली की फ़ोटो अपलोड करें',
    'userProfile.palmPhotoInfo': 'अपनी हथेली की स्पष्ट फ़ोटो अपलोड करने से हमारे ज्योतिषियों को अधिक सटीक हस्तरेखा पठन प्रदान करने में मदद मिलती है।',
    'userProfile.noPhotoUploaded': 'कोई फ़ोटो अपलोड नहीं की गई',
    'userProfile.saveChanges': 'बदलाव सहेजें',
    'userProfile.removePhotoConfirm': 'क्या आप वाकई इस फ़ोटो को हटाना चाहते हैं?',
    'userProfile.remove': 'हटाएं',
    'userProfile.validationError': 'सत्यापन त्रुटि',
    'userProfile.uploadProfilePhoto': 'कृपया एक प्रोफ़ाइल फ़ोटो अपलोड करें।',
    'userProfile.enterFullName': 'कृपया अपना पूरा नाम दर्ज करें।',
    'userProfile.enterMobile': 'कृपया अपना मोबाइल नंबर दर्ज करें।',
    'userProfile.emailEmpty': 'ईमेल खाली नहीं हो सकता।',
    'userProfile.emailInvalid': 'कृपया एक मान्य ईमेल पता दर्ज करें।',
    'userProfile.selectGender': 'कृपया अपना लिंग चुनें।',
    'userProfile.selectMaritalStatus': 'कृपया अपनी वैवाहिक स्थिति चुनें।',
    'userProfile.selectDob': 'कृपया अपनी जन्म तिथि चुनें।',
    'userProfile.selectTob': 'कृपया अपना जन्म समय चुनें।',
    'userProfile.enterCity': 'कृपया अपना शहर (जन्म स्थान) दर्ज करें।',
    'userProfile.selectState': 'कृपया अपना राज्य चुनें।',
    'userProfile.success': 'सफलता',
    'userProfile.updatedSuccessfully': 'प्रोफ़ाइल सफलतापूर्वक अपडेट हो गई!',
    'userProfile.updateError': 'प्रोफ़ाइल अपडेट करने में त्रुटि',
    'userProfile.selectImage': 'छवि चुनें',

    // My Sessions
    'session.chatSession': 'चैट सत्र',
    'session.audioCall': 'ऑडियो कॉल',
    'session.videoCall': 'वीडियो कॉल',
    'session.liveSession': 'लाइव सत्र',
    'session.tabChat': 'चैट',
    'session.tabLive': 'लाइव',
    'session.noneFound': 'कोई {{type}} नहीं मिला',
    'session.willAppear': 'सत्र समाप्त होने के बाद यहाँ दिखाई देंगे',
    'common.astrologer': 'ज्योतिषी',
    'session.ref': 'संदर्भ: {{id}}',
    'session.active': 'सक्रिय',
    'session.viewProfile': 'प्रोफ़ाइल देखें',
    'session.rate': 'दर',
    'session.duration': 'अवधि',
    'session.charged': 'शुल्क लिया गया',
    'session.rateThisSession': 'इस सत्र को रेट करें',
    'notifications.none': 'कोई नई सूचना नहीं',

    // Search screen
    'search.noAstrologerFound': 'कोई ज्योतिषी नहीं मिला',
    'search.mostSearched': 'एस्ट्रोवाणी पर सबसे ज़्यादा खोजा गया',
    'search.tag.maritalLife': 'वैवाहिक जीवन',
    'search.tag.loveRelationship': 'प्रेम और रिश्ते',
    'search.tag.careerJob': 'करियर और नौकरी',
    'search.tag.cheatingAffairs': 'धोखा और अफेयर',
    'search.tag.financeBusiness': 'वित्त और व्यवसाय',
    'search.tag.breakupDivorce': 'ब्रेकअप और तलाक',
    'search.tag.vedicAstrology': 'वैदिक ज्योतिष',
    'search.tag.psychicReading': 'साइकिक रीडिंग',
    'search.tag.tarotReading': 'टैरो रीडिंग',
    'search.tag.numerology': 'अंकशास्त्र',
    'search.tag.relationshipCounseling': 'रिश्ते परामर्श',

    // Blog screen
    'blog.createdAt': '{{date}} को बनाया गया',

    // Free Services — Panchang
    'panchang.enterLocation': 'अपना स्थान दर्ज करें',
    'panchang.loading': 'लोड हो रहा है...',
    'panchang.title': 'पंचांग',
    'panchang.additionalInfo': 'अतिरिक्त जानकारी',
    'panchang.auspiciousTime': 'शुभ समय',
    'panchang.inauspiciousTime': 'अशुभ समय',
    'panchang.vaara': 'वार',
    'panchang.nakshatra': 'नक्षत्र',
    'panchang.tithi': 'तिथि',
    'panchang.karana': 'करण',
    'panchang.yoga': 'योग',
    'panchang.sunrise': 'सूर्योदय',
    'panchang.sunset': 'सूर्यास्त',
    'panchang.moonrise': 'चंद्रोदय',
    'panchang.moonset': 'चंद्रास्त',

    // Free Services — Janam Kundali
    'kundali.enterDetails': 'अपना विवरण दर्ज करें',
    'kundali.enterFullName': 'पूरा नाम दर्ज करें',
    'kundali.selectGender': 'लिंग चुनें',
    'kundali.selectDob': 'जन्म तिथि चुनें',
    'kundali.selectTob': 'जन्म समय चुनें',
    'kundali.dontKnow': 'मुझे नहीं पता',
    'kundali.enterPlaceOfBirth': 'जन्म स्थान दर्ज करें',
    'kundali.showKundali': 'कुंडली दिखाएं',
    'kundali.pleaseEnterName': 'कृपया अपना नाम दर्ज करें',
    'kundali.pleaseSelectGender': 'कृपया अपना लिंग चुनें',
    'kundali.pleaseSelectDob': 'कृपया अपनी जन्म तिथि चुनें',
    'kundali.pleaseSelectTob': 'कृपया अपना जन्म समय चुनें या "मुझे नहीं पता" चुनें',
    'kundali.locationFetchError': 'उस स्थान के निर्देशांक प्राप्त नहीं हो सके। कृपया इसे दोबारा चुनने का प्रयास करें।',

    // Free Services — Kundali Match
    'match.boysDetails': 'लड़के का विवरण',
    'match.girlsDetails': 'लड़की का विवरण',
    'match.enterBoyPlace': 'लड़के का जन्म स्थान दर्ज करें',
    'match.enterGirlPlace': 'लड़की का जन्म स्थान दर्ज करें',
    'match.showReport': 'रिपोर्ट दिखाएं',
    'match.fillAllFields': 'कृपया सभी आवश्यक फ़ील्ड भरें',
    'match.errorFetching': 'रिपोर्ट प्राप्त करते समय एक त्रुटि हुई। कृपया पुनः प्रयास करें।',

    // Free Services — Horoscope
    'horoscope.title': '{{sign}} राशिफल',
    'horoscope.unableToFetch': 'राशिफल डेटा प्राप्त करने में असमर्थ। कृपया बाद में पुनः प्रयास करें।',

    // Free (₹1) services visual layer
    'free.daily': 'दैनिक',
    'free.monthly': 'मासिक',
    'free.yearly': 'वार्षिक',
    'free.fullReading': 'दैनिक · मासिक · वार्षिक',
    'free.todaysReading': 'आज का पठन',
    'free.nakshatraDetails': 'नक्षत्र विवरण',
    'free.doshasAndYogas': 'दोष और योग',
    'free.noKundaliData': 'कोई कुंडली डेटा उपलब्ध नहीं है',
    'free.birthSummary': 'जन्म सारांश',
    'free.sunAndMoon': 'सूर्य और चंद्र',
    'free.dayLength': 'दिन की अवधि',
    'free.result': 'परिणाम',
    'free.basicDetails': 'मूल विवरण',
    'free.gunaDetails': 'गुण विवरण',
    'free.boysDetails': 'वर का विवरण',
    'free.girlsDetails': 'वधू का विवरण',
    'free.matchScore': 'गुण मिलान अंक',
    'free.choghadiya': 'चौघड़िया',
    'free.shubhHora': 'शुभ होरा',
    'free.gowriPanchangam': 'गौरी पंचांगम',
    'free.rahuKaal': 'राहु काल',
    'free.auspicious': 'शुभ',
    'free.inauspicious': 'अशुभ',
    'free.neutral': 'सामान्य',
    'free.now': 'अभी',
    'free.noServices': 'कोई सेवा उपलब्ध नहीं है',
    'zodiac.aries': 'मेष',
    'zodiac.taurus': 'वृषभ',
    'zodiac.gemini': 'मिथुन',
    'zodiac.cancer': 'कर्क',
    'zodiac.leo': 'सिंह',
    'zodiac.virgo': 'कन्या',
    'zodiac.libra': 'तुला',
    'zodiac.scorpio': 'वृश्चिक',
    'zodiac.sagittarius': 'धनु',
    'zodiac.capricorn': 'मकर',
    'zodiac.aquarius': 'कुंभ',
    'zodiac.pisces': 'मीन',

    // AstroServices shared
    'astro.notAvailable': 'अनुपलब्ध',
    'astro.notAvailableMsg': 'यह रिपोर्ट अभी उपलब्ध नहीं है। कृपया बाद में पुनः प्रयास करें।',
    'astro.reportCostsMsg': 'इस रिपोर्ट की कीमत ₹{{price}} है। आपका वॉलेट बैलेंस ₹{{balance}} है। कृपया अपना वॉलेट रीचार्ज करें।',
    'astro.rechargeToView': 'यह रिपोर्ट प्राप्त करने के लिए कृपया अपना वॉलेट रीचार्ज करें।',
    'astro.confirmPurchase': 'खरीद की पुष्टि करें',
    'astro.confirmPurchaseMsg': '{{name}} के लिए आपके वॉलेट से ₹{{price}} काटे जाएंगे।',
    'astro.payAmount': '₹{{price}} भुगतान करें',
    'astro.failedToGenerate': 'रिपोर्ट बनाने में विफल',
    'freeServices.costMsg': 'इस सेवा की कीमत ₹{{price}} है। आपका वॉलेट बैलेंस ₹{{balance}} है। कृपया अपना वॉलेट रीचार्ज करें।',
    'freeServices.confirmMsg': '{{name}} का उपयोग करने के लिए आपके वॉलेट से ₹{{price}} काटे जाएंगे।',
    'freeServices.failedToCharge': 'इस सेवा के लिए भुगतान करने में विफल',
    'astro.enterYourBirthDetails': 'अपना जन्म विवरण दर्ज करें',
    'astro.enterBirthDetails': 'जन्म विवरण दर्ज करें',
    'astro.getKundliReport': 'कुंडली रिपोर्ट प्राप्त करें',
    'astro.getDashaReport': 'दशा रिपोर्ट प्राप्त करें',
    'astro.getDoshReport': 'दोष रिपोर्ट प्राप्त करें',
    'astro.getLalKitabReport': 'लाल किताब रिपोर्ट प्राप्त करें',
    'astro.getChartReport': 'चार्ट रिपोर्ट प्राप्त करें',
    'astro.getNumerologyReport': 'अंकशास्त्र रिपोर्ट प्राप्त करें',
    'astro.getKPReport': 'केपी ज्योतिष रिपोर्ट प्राप्त करें',
    'astro.getTarotReading': 'टैरो रीडिंग प्राप्त करें',
    'astro.getPdfReport': 'पीडीएफ रिपोर्ट प्राप्त करें',
    'astro.getMatchingReport': 'मिलान रिपोर्ट प्राप्त करें',
    'astro.chooseChart': 'चार्ट चुनें',
    'astro.selectAChart': 'एक चार्ट चुनें',
    'astro.getChart': 'चार्ट प्राप्त करें',
    'astro.matchKundli': 'कुंडली मिलान करें',
    'astro.name': 'अपना नाम दर्ज करें',
    'astro.phoneNumber': 'फ़ोन नंबर',
    'astro.getReading': 'रीडिंग प्राप्त करें',
    'astro.selectTemplate': 'रिपोर्ट का प्रकार चुनें',
    'astro.pdfPlaceOfBirth': 'जन्म स्थान',
    'astro.enterMobileNumber': 'मोबाइल नंबर दर्ज करें',
    'astro.tarotTitle': 'हाँ या नहीं टैरो रीडिंग',
    'astro.tarotSubtitle': 'अपने प्रश्न का त्वरित उत्तर पाने के लिए एक कार्ड निकालें।',
    'astro.drawCard': 'कार्ड निकालें',
    'astro.yourReading': 'आपकी रीडिंग',
    'astro.yourDetails': 'आपका विवरण',
    'astro.chooseReport': 'रिपोर्ट चुनें',
    'astro.selectPdfReport': 'एक पीडीएफ रिपोर्ट चुनें',
    'astro.generatePdfReport': 'पीडीएफ रिपोर्ट बनाएं',

    // Result screen section titles
    'result.kundliOverview': 'कुंडली अवलोकन',
    'result.ascendantReport': 'लग्न रिपोर्ट',
    'result.planetDetails': 'ग्रह विवरण',
    'result.ashtakootMatching': 'अष्टकूट मिलान',
    'result.dashakootMatching': 'दशकूट मिलान',
    'result.aggregateCompatibility': 'समग्र अनुकूलता',
    'result.boysMangalDosh': 'लड़के का मंगल दोष',
    'result.girlsMangalDosh': 'लड़की का मंगल दोष',
    'result.currentMahadasha': 'वर्तमान महादशा',
    'result.mahadashaTimeline': 'महादशा समयरेखा',
    'result.yoginiDashaMain': 'योगिनी दशा (मुख्य)',
    'result.yoginiDashaSub': 'योगिनी दशा (उप)',
    'result.mangalDosh': 'मंगल दोष',
    'result.kaalsarpDosh': 'कालसर्प दोष',
    'result.manglikDosh': 'मांगलिक दोष',
    'result.pitraDosh': 'पितृ दोष',
    'result.loshuGrid': 'लोशु ग्रिड',
    'result.nameAnalysis': 'नाम विश्लेषण',
    'result.mobileAnalysis': 'मोबाइल नंबर विश्लेषण',
    'result.luckyThings': 'भाग्यशाली चीज़ें',
    'result.personalYear': 'व्यक्तिगत वर्ष',
    'result.lalKitabHoroscope': 'लाल किताब राशिफल',
    'result.lalKitabDebts': 'लाल किताब ऋण',
    'result.lalKitabRemedies': 'लाल किताब उपाय',
    'result.lalKitabHouses': 'लाल किताब भाव',
    'result.lalKitabPlanets': 'लाल किताब ग्रह',
    'result.cuspDetails': 'कस्प विवरण',
    'result.houseSignificators': 'भाव संकेतक',
    'result.reportReady': 'आपकी रिपोर्ट तैयार है',
    'result.tapToViewDownload': 'अपनी पीडीएफ रिपोर्ट देखने या डाउनलोड करने के लिए नीचे टैप करें।',
    'result.viewReport': 'रिपोर्ट देखें',

    // Report presentation layer (src/components/astro/*) — see HINDI_I18N_APP.md
    'report.translating': 'अनुवाद हो रहा है…',
    'report.langSwitchFailed': 'भाषा नहीं बदली जा सकी। कृपया पुनः प्रयास करें।',
    'report.tapToEnlarge': 'बड़ा करने और ज़ूम करने के लिए चक्र पर टैप करें',
    'report.pinchHint': 'ज़ूम के लिए पिंच करें · खिसकाने के लिए खींचें · रीसेट के लिए डबल-टैप करें',
    'report.chartFailed': 'यह चक्र नहीं बनाया जा सका। कृपया पुनः प्रयास करें।',
    'report.tapToZoom': 'ज़ूम के लिए टैप करें',
    'report.divisionalChart': 'वर्ग चक्र · {{div}}',
    'report.personalYearLabel': 'व्यक्तिगत वर्ष',
    'report.lagnaChart': 'लग्न चक्र (D1)',
    'report.yourBirthChart': 'आपकी जन्म कुंडली',
    'report.kundliSub': 'जन्म कुंडली, ग्रह स्थिति और विशेषताएँ',
    'report.birthAttributes': 'जन्म विशेषताएँ',
    'report.recommendedStones': 'अनुशंसित रत्न',
    'report.ascendant': 'लग्न',
    'report.moonSign': 'चंद्र राशि',
    'report.sunSign': 'सूर्य राशि',
    'report.planetaryPositions': 'ग्रहों की स्थिति',
    'report.positionsAtBirth': 'जन्म के समय {{count}} स्थितियाँ',
    'report.house': 'भाव',
    'report.degree': 'अंश',
    'report.nakshatra': 'नक्षत्र',
    'report.pada': 'पाद',
    'report.nakLord': 'नक्षत्र स्वामी',
    'report.signLord': 'राशि स्वामी',
    'report.subLord': 'उप स्वामी',
    'report.subSubLord': 'उप-उप स्वामी',
    'report.position': 'स्थिति',
    'report.nature': 'प्रकृति',
    'report.rashi': 'राशि',
    'report.retrograde': 'वक्री',
    'report.combust': 'अस्त',
    'report.luckyGem': 'भाग्यशाली रत्न',
    'report.luckyNumber': 'भाग्यशाली अंक',
    'report.lagnaLord': 'लग्नेश',
    'report.placedIn': 'स्थित',
    'report.strength': 'बल',
    'report.forYouSpecifically': 'विशेष रूप से आपके लिए',
    'report.strengths': 'शक्तियाँ',
    'report.watchOutFor': 'सावधानी रखें',
    'report.fastingDay': 'व्रत का दिन',
    'report.gayatriMantra': 'गायत्री मंत्र',
    'report.flagshipQualities': 'प्रमुख गुण',
    'report.spiritualGuidance': 'आध्यात्मिक मार्गदर्शन',
    'report.additionalReadings': 'अतिरिक्त विवरण',
    'report.doshaAnalysis': 'दोष विश्लेषण',
    'report.doshaAnalysisSub': 'क्या उपस्थित है, कितना प्रबल है, और क्या करें',
    'report.atAGlance': 'एक नज़र में',
    'report.allFourDoshas': 'चारों दोष',
    'report.present': 'उपस्थित',
    'report.notPresent': 'अनुपस्थित',
    'report.partiallyPresent': 'आंशिक रूप से उपस्थित',
    'report.clear': 'मुक्त',
    'report.doshaSummaryAffected': 'आपकी कुंडली में {{total}} में से {{n}} दोष उपस्थित हैं: {{list}}। प्रत्येक के उपाय नीचे दिए गए हैं।',
    'report.doshaSummaryClear': 'आपकी कुंडली में चारों में से कोई भी दोष उपस्थित नहीं है।',
    'report.intensity': 'तीव्रता',
    'report.sources': 'स्रोत',
    'report.byMars': 'मंगल से',
    'report.bySaturn': 'शनि से',
    'report.byRahuKetu': 'राहु/केतु से',
    'report.why': 'कारण',
    'report.aspects': 'दृष्टि',
    'report.effects': 'प्रभाव',
    'report.remedies': 'उपाय',
    'report.cancellationScore': 'निवारण अंक {{score}}',
    'report.kundaliMatching': 'कुंडली मिलान',
    'report.matchingSub': 'अनुकूलता, दोष और उपाय',
    'report.overallCompatibility': 'समग्र अनुकूलता',
    'report.everythingWeighed': 'सब कुछ एक साथ आँका गया',
    'report.matchScore': 'मिलान अंक',
    'report.totalGuna': 'कुल गुण',
    'report.compatibility': 'अनुकूलता',
    'report.verdict': 'निष्कर्ष',
    'report.excellent': 'उत्तम',
    'report.average': 'मध्यम',
    'report.low': 'निम्न',
    'report.pointByPoint': 'बिंदुवार अनुकूलता',
    'report.doshaComparison': 'दोष तुलना',
    'report.whatEachDosha': 'यहाँ प्रत्येक दोष का अर्थ',
    'report.detailedReading': 'विस्तृत विवरण',
    'report.boy': 'वर',
    'report.girl': 'वधू',
    'report.yes': 'हाँ',
    'report.no': 'नहीं',
    'report.rajjuDosha': 'रज्जु दोष',
    'report.vedhaDosha': 'वेध दोष',
    'report.mangalDosha': 'मंगल दोष',
    'report.pitraDosha': 'पितृ दोष',
    'report.kaalSarpDosha': 'काल सर्प दोष',
    'report.manglikSaturn': 'शनि से मांगलिक',
    'report.manglikRahuKetu': 'राहु/केतु से मांगलिक',
    'report.dashaSub': 'आपके जीवन भर की ग्रह दशाएँ',
    'report.periods': '{{count}} अवधियाँ',
    'report.now': 'अभी',
    'report.birth': 'जन्म',
    'report.earlierPeriods': 'पूर्व की अवधियाँ',
    'report.laterPeriods': 'आगे की अवधियाँ',
    'report.currentlyRunning': 'वर्तमान में चल रही है: {{name}} — {{end}} तक',
    'report.runningNow': 'अभी चल रही दशाएँ',
    'report.runningNowSub': 'आपकी पाँच सक्रिय दशा श्रेणियाँ, बाहरी से भीतरी क्रम में',
    'report.majorPeriod': 'महादशा अवधि',
    'report.subPeriod': 'अंतर्दशा अवधि',
    'report.subSubPeriod': 'प्रत्यंतर्दशा अवधि',
    'report.finerPeriod': 'सूक्ष्म अवधि',
    'report.finestPeriod': 'प्राण अवधि',
    'report.majorPeriods': 'महादशाएँ',
    'report.withinMahadasha': 'वर्तमान महादशा के अंतर्गत',
    'report.withinAntardasha': 'वर्तमान अंतर्दशा के अंतर्गत',
    'report.vimshottariSequence': 'विंशोत्तरी क्रम',
    'report.yoginiMajor': 'योगिनी महादशाएँ',
    'report.yoginiSub': 'योगिनी अंतर्दशाएँ',
    'report.subPeriodsWithin': '{{name}} के अंतर्गत अंतर्दशाएँ',
    'report.yr': 'वर्ष',
    'report.mo': 'माह',
    'report.numerologyReport': 'अंक ज्योतिष रिपोर्ट',
    'report.numerologySub': 'आपके अंक, नाम और शुभ वस्तुएँ',
    'report.yourNumbers': 'आपके अंक',
    'report.loShuGrid': 'लो शू ग्रिड',
    'report.loShuHint': 'भरे हुए खाने आपकी जन्मतिथि में मौजूद अंक हैं; धुँधले खाने अनुपस्थित अंक हैं।',
    'report.missing': 'अनुपस्थित',
    'report.planeStrengths': 'तलों की शक्ति',
    'report.numberSum': 'अंकों का योग',
    'report.favourable': 'अनुकूल',
    'report.notFavourable': 'प्रतिकूल',
    'report.digitMeanings': 'अंकों के अर्थ',
    'report.fullName': 'पूरा नाम',
    'report.firstName': 'पहला नाम',
    'report.suggestedSpellings': 'सुझाई गई नाम वर्तनी',
    'report.luckyForYou': 'आपके लिए शुभ',
    'report.rulingPlanet': 'स्वामी ग्रह',
    'report.element': 'तत्व',
    'report.bestTime': 'शुभ समय',
    'report.traits': 'गुण',
    'report.favourablePeriods': 'शुभ अवधियाँ',
    'report.luckFactor': 'भाग्य कारक',
    'report.lalKitabReport': 'लाल किताब रिपोर्ट',
    'report.lalKitabSub': 'चक्र, भाव, ऋण और उपाय',
    'report.lalKitabChart': 'लाल किताब चक्र',
    'report.planetsBySign': 'राशि अनुसार ग्रह',
    'report.housesKhana': 'भाव (खाना)',
    'report.khanas': '{{count}} खाने',
    'report.lord': 'स्वामी',
    'report.sleeping': 'सोया हुआ',
    'report.pakkaGhar': 'पक्का घर',
    'report.kismat': 'किस्मत',
    'report.planetRemedies': 'ग्रह उपाय',
    'report.tapPlanet': 'प्रभाव और उपाय पढ़ने के लिए ग्रह पर टैप करें',
    'report.karmicDebts': 'ऋण (कर्ज)',
    'report.noDebts': 'आपकी कुंडली में कोई ऋण नहीं मिला।',
    'report.found': '{{count}} मिले',
    'report.indications': 'संकेत',
    'report.possibleEvents': 'संभावित घटनाएँ',
    'report.kpSub': 'कृष्णमूर्ति पद्धति चक्र और कारक ग्रह',
    'report.cuspSub': 'प्रत्येक भाव का राशि, नक्षत्र और उप स्वामी',
    'report.sign': 'राशि',
    'report.star': 'नक्षत्र',
    'report.sub': 'उप',
    'report.subSub': 'उप-उप',
    'report.significatorsSub': 'प्रत्येक भाव के कारक ग्रह',
  },
};

// Resolve a key against the English table, applying the same {{param}}
// interpolation the Provider's own t() does. Shared by the context default
// below so a Provider-less render behaves identically, just without switching.
const translateEnglish = (key, params) => {
  let str = translations.English[key] ?? key;
  if (params) {
    Object.keys(params).forEach(p => {
      str = str.replace(new RegExp(`{{${p}}}`, 'g'), params[p]);
    });
  }
  return str;
};

// A missing Provider must never be fatal. `createContext()` with no default
// returns undefined, so every consumer doing
// `const {language, t} = useContext(LanguageContext)` throws
// "Cannot read property 'language' of undefined" and takes the whole screen
// down with it. The vendor app hit exactly that (Sentry ASTROWANI-VENDOR-4,
// 2026-08-14) and this app carries the identical shape — it can happen any
// time a consumer renders outside the Provider, including during an OTA
// bundle swap or a remount. Defaulting to English degrades instead of crashing.
export const LanguageContext = createContext({
  language: 'English',
  changeLanguage: () => {},
  t: translateEnglish,
});

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('English');

  useEffect(() => {
    const loadLanguage = async () => {
      try {
        const savedLang = await AsyncStorage.getItem('appLanguage');
        if (savedLang) {
          setLanguage(savedLang);
        }
      } catch (error) {
        console.log('Error loading language', error);
      }
    };
    loadLanguage();
  }, []);

  const changeLanguage = async (lang) => {
    setLanguage(lang);
    try {
      await AsyncStorage.setItem('appLanguage', lang);
    } catch (error) {
      console.log('Error saving language', error);
    }
  };

  // t('home.waitingFor', { name: 'Ramesh' }) → replaces {{name}} in the resolved string.
  const t = (key, params) => {
    let str = translations[language]?.[key] ?? translations['English'][key] ?? key;
    if (params) {
      Object.keys(params).forEach(p => {
        str = str.replace(new RegExp(`{{${p}}}`, 'g'), params[p]);
      });
    }
    return str;
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
