import React, { createContext, useState, useEffect } from 'react';
import AsyncStorage from '@react-native-async-storage/async-storage';

export const LanguageContext = createContext();

// Namespaced keys (namespace.key) to avoid collisions as coverage grows across screens.
// NOTE: numbers, currency amounts, dates/times, astrologer names, OTP codes, and the
// legal pages (Terms of Use / Privacy Policy / Refund & Cancellation) are intentionally
// NEVER translated — see astrowani_customer-main/HINDI_I18N_APP.md.
const translations = {
  English: {
    // Home
    'home.welcome': 'Welcome to Astrowani!',
    'home.search': 'Search Here',
    'home.bestAstrologers': "India's Best Astrologers",
    'home.viewAll': 'View All',
    'home.remedies': 'Astrowani Remedies',
    'home.bookPuja': 'Book VIP Puja',
    'home.buyGemstones': 'Buy Gemstones',
    'home.readMore': 'Read More',
    'home.categories': "Astrowani's Categories",
    'home.liveAstrologers': 'Live Astrologers',
    'home.freeServices': 'Free Services',
    'home.astroReports': 'Astro Reports',
    'home.blog': "Astrowani's Blog",
    'home.whatClientsSay': 'What Our Clients Say',
    'home.discoverTrust': 'Discover why thousands trust Astrowani',
    'home.whyBest': 'Why Astrowani Is Best For Astrology?',
    'home.whyBestBody': 'Astrowani reveals the destiny that Stars has designed for us. Astrowani is a proven science with its methods and way of interpreting the influence of stars and planets on earthly affairs and human destinies. Astrowani, with its scientific method of calculation and prediction of actual events, is approving enough to make people start believing in it. And it has been doing the same since the early Vedic period.',
    'home.noReviews': 'No reviews available yet.',
    'home.requestSent': 'Request Sent',
    'home.waitingFor': 'Waiting for {{name}} to accept your request...',
    'home.cancelRequest': 'Cancel Request',
    'home.chatWithAstrologer': 'Chat with Astrologer',
    'home.talkToAstrologer': 'Talk To Astrologer',

    // Common labels / actions
    'common.chat': 'Chat',
    'common.call': 'Call',
    'common.video': 'Video',
    'common.noChat': 'No Chat',
    'common.noCall': 'No Call',
    'common.noVideo': 'No Video',
    'common.offline': 'Offline',
    'common.live': 'Live',
    'common.scheduled': 'Scheduled',
    'common.home': 'Home',
    'common.wallet': 'Wallet',
    'common.profile': 'My Profile',
    'common.cancel': 'Cancel',
    'common.ok': 'OK',
    'common.error': 'Error',
    'common.language': 'Choose Language',

    // Alerts
    'alerts.unavailable': 'Unavailable',
    'alerts.notAvailableChat': '{{name}} is not available for chat right now.',
    'alerts.notAvailableCall': '{{name}} is not available for calls right now.',
    'alerts.notAvailableVideo': '{{name}} is not available for video call right now.',
    'alerts.astrologerOffline': '{{name}} is offline right now. Please check back later.',
    'alerts.astrologerBusy': 'Astrologer is busy right now. Please try again after some time.',
    'alerts.notPickedUpAudio': 'Your audio call was not picked up. Please try again later.',
    'alerts.notPickedUpVideo': 'Your video call was not picked up. Please try again later.',
    'alerts.insufficientBalance': 'Insufficient Balance',
    'alerts.failedWalletCheck': 'Failed to verify wallet balance.',
    'alerts.failedRequestAstrologer': 'Failed to send request to astrologer.',
    'alerts.failedInitiateCall': 'Failed to initiate call',
    'alerts.failedInitiateVideoCall': 'Failed to initiate video call',

    // Drawer
    'drawer.myWallet': 'My Wallet',
    'drawer.mySessions': 'My Sessions',
    'drawer.remedies': 'Remedies',
    'drawer.chatWithAstrologer': 'Chat With Astrologer',
    'drawer.blogs': 'Astrowani Blogs',
    'drawer.myFavorites': 'My Favorites',
    'drawer.myOrders': 'My Orders',
    'drawer.voiceNotes': 'Voice Notes',
    'drawer.referFriend': 'Refer A Friend',
    'drawer.settings': 'Settings',
    'drawer.support': 'Support',
    'drawer.shareApp': 'Share App',
    'drawer.logout': 'Logout',
    'drawer.connectWithUs': 'Connect With Us',
    'drawer.welcome': 'Welcome!',
    'drawer.updateProfile': 'Update your profile',

    // Settings
    'settings.aboutUs': 'About Us',
    'settings.faqs': "FAQ's",
    'settings.refundCancellation': 'Refund & Cancellation',
    'settings.privacyPolicy': 'Privacy Policy',
    'settings.termsOfUse': 'Terms of Use',
    'settings.deleteAccount': 'Delete my account',
    'settings.confirmLogoutTitle': 'Confirm Logout',
    'settings.confirmLogoutMsg': 'Are you sure you want to log out?',
    'settings.confirmDeleteTitle': 'Confirm Delete',
    'settings.confirmDeleteMsg': 'Are you sure you want to delete your account? Once deleted, all your saved history will be lost. Do you still wish to continue?',
    'settings.deleteBtn': 'Delete',
    'settings.accountDeleted': 'Account deleted successfully',
    'settings.loggedOut': 'Logged out successfully',

    // Login / OTP
    'login.tagline': "Best Astrologer's Team",
    'login.discoverPath': 'Discover Your Cosmic Path',
    'login.phoneNumber': 'Phone number',
    'login.continue': 'Continue',
    'login.agreeTerms': 'By signing up, you agree to our ',
    'login.and': ' & ',
    'login.noAccount': "Don't have an account? ",
    'login.register': 'Register',
    'login.selectCountry': 'Select Country',
    'login.close': 'Close',
    'login.validationError': 'Validation Error',
    'login.phoneEmpty': 'Phone number cannot be empty.',
    'login.phoneTooShort': 'Phone number must be at least 10 digits long.',
    'login.otpFailed': 'Could not send OTP. Please try again.',
    'login.noAccountTitle': 'No Account Found',
    'login.noAccountMsg': "We couldn't find an account for this number. Please sign up first.",
    'login.somethingWrong': 'Something went wrong. Please try again.',

    // Remedies (static home tiles)
    'remedies.puja': 'Puja',
    'remedies.gemstones': 'Gemstones',
    'remedies.specificPuja': 'Specific Puja',
    'remedies.lifeReports': 'Life Reports',
    'remedies.buyNow': 'Buy Now',

    'call.pleaseLogin': 'Please login to continue.',

    // ReusableList shared card
    'common.viewProfile': 'Profile',
    'common.free': 'Free',
    'common.exp': 'Exp',
    'common.yrs': 'yrs',
    'common.searchAstrologer': 'Search astrologer by name or skill...',
    'alerts.failedGenerateRoom': 'Failed to generate call room.',
    'alerts.declined': 'Declined',
    'alerts.declinedBusy': '{{name}} is currently busy and declined the call.',
    'video.waitingFor': 'Waiting for {{name}} to accept your video call...',

    // Chat request hook
    'chat.pleaseLogIn': 'Please log in first.',
    'chat.sessionInvalid': 'Session invalid. Please log out and log back in.',
    'chat.astrologerInfoMissing': 'Astrologer info missing. Please refresh and try again.',
    'chat.lowBalance': 'Low Balance',
    'chat.lowBalanceMsg': 'You need at least ₹{{charge}} to start a chat. Please recharge your wallet.',
    'chat.couldNotSendRequest': 'Could not send request: {{msg}}',
    'chat.notPickedUp': 'Your chat request was not picked up. Please try again later.',
    'status.astrologerBusyTitle': 'Astrologer Busy',
    'status.notAnsweredTitle': 'Not Answered',

    // Live tab
    'live.watching': 'watching',
    'live.joinNow': 'Join Now',
    'live.searchPlaceholder': 'Search live sessions...',
    'live.noneLive': 'No astrologers are live right now.',

    // AstrologerInfo profile screen
    'profile.new': 'New',
    'profile.yrs': 'Yrs',
    'profile.gift': 'Gift',
    'profile.off': 'Off',
    'profile.specialization': 'Specialization',
    'profile.aboutServices': 'About My Services',
    'profile.aboutFallback': 'Experienced and professional astrologer here to guide you through your life journey.',
    'profile.readLess': 'Read Less',
    'profile.experienceQualification': 'Experience & Qualification',
    'profile.experienceBody': "With several years of dedicated practice, I've honed my skills in {{specialties}}.",
    'profile.clientReviews': 'Client Reviews',
    'profile.reviewsOnAstrowani': '{{count}} reviews on Astrowani',
    'profile.noReviewsYet': 'No reviews yet.',
    'profile.showAll': 'Show All',
    'profile.writeReview': '+ Write Review',
    'profile.astrowaniReplyPrefix': '↳ Astrowani: ',

    // OTP screens
    'otp.sentToNumber': 'OTP sent to your Number',
    'otp.expiresIn': 'OTP expires in {{time}}',
    'otp.verifyBtn': 'Verify OTP',
    'otp.notReceived': "Didn't receive the OTP? ",
    'otp.resend': 'Resend OTP',
    'otp.invalidTryAgain': 'Invalid OTP. Please try again.',
    'otp.failedVerify': 'Failed to verify OTP. Please try again.',
    'otp.verifyTitle': 'Verify Your Number',
    'otp.enterCodeSentTo': 'Enter the 6-digit code sent to ',
    'otp.yourNumber': 'your number',
    'otp.almostThere': 'Almost There!',
    'otp.resendIn': 'Resend OTP in {{time}}',
    'otp.sending': 'Sending...',
    'otp.changeNumber': 'Change Phone Number',
    'otp.invalidOtpTitle': 'Invalid OTP',
    'otp.enterComplete': 'Please enter the complete 6-digit code.',
    'otp.verificationFailed': 'Verification Failed',
    'otp.otpSentTitle': 'OTP Sent',
    'otp.newCodeSent': 'A new code has been sent to your number.',
    'otp.couldNotResend': 'Could not resend OTP.',
    'otp.couldNotResendRetry': 'Could not resend OTP. Please try again.',

    // About Us
    'about.tagline': 'Best Astrologers Team',
    'about.title': 'About Us',
    'about.p1': 'Astrowani is your trusted gateway to the ancient science of astrology, delivered with the convenience of modern technology. Our mission is to help you find clarity, direction, and peace of mind through personalized astrological guidance.',
    'about.p2': 'We work with a team of highly experienced and verified astrologers from across India, each specializing in Vedic astrology, numerology, palmistry, tarot reading, and more. Whether you are seeking answers about career, relationships, health, or finance, our experts are here to guide you with compassion and accuracy.',
    'about.p3': 'At Astrowani, we believe astrology is not about predicting doom or dictating your fate, but about empowering you to make informed decisions. Our consultations are rooted in authenticity, ethics, and confidentiality, ensuring that your personal details and readings remain private.',
    'about.p4': "With features like live consultations, chat sessions, and daily horoscopes, Astrowani makes it easy to connect with the right expert anytime, anywhere. Whether you're a believer or just curious, we welcome you to explore what the stars have to say.",
    'about.p5': 'Join thousands of satisfied users who have discovered guidance, inspiration, and positivity through Astrowani — where tradition meets trust.',

    // FAQ
    'faq.title': 'Frequently Asked Questions',
    'faq.q1': 'I want to chat with an Astrologer. How do I start?',
    'faq.a1': 'In order to chat with an Astrologer, all you need to do is login to your Astrowani account or sign up to create an account, add money to your wallet, and then simply choose the Astrologer you want to chat with and begin your session.',
    'faq.q2': 'Is there any requirement of minimum balance before I begin consulting an Astrologer?',
    'faq.a2': 'You need to have a minimum balance of $10 to start consulting an Astrologer on Astrowani.',
    'faq.q3': 'Are the Astrologers verified?',
    'faq.a3': 'Yes, all the Astrologers on Astrowani are verified professionals with years of experience.',
    'faq.q4': 'If I get a phone call in between a chat, will it automatically end my session?',
    'faq.a4': 'No, your session will not end automatically if you receive a phone call. The chat will be paused, and you can resume once the call ends.',

    // Wallet
    'wallet.invalidAmount': 'Invalid Amount',
    'wallet.enterValidAmount': 'Please enter a valid amount to recharge.',
    'wallet.paymentSuccessful': 'Payment Successful',
    'wallet.paymentId': 'Payment ID: {{id}}',
    'wallet.paymentFailed': 'Payment Failed',
    'wallet.addMoney': 'Add Money to Wallet',
    'wallet.rechargeSubtitle': 'Recharge seamlessly to talk to experts',
    'wallet.enterAmount': 'Enter Amount',
    'wallet.recommendedAmounts': 'Recommended amounts',
    'wallet.totalPayable': 'Total Payable',
    'wallet.proceedToPay': 'Proceed to Pay',

    // Register screen
    'register.title': 'Register',
    'register.tapToAddPhoto': 'Tap to add photo',
    'register.fullName': 'Full Name',
    'register.male': 'Male',
    'register.female': 'Female',
    'register.other': 'Other',
    'register.selectGender': 'Select Gender',
    'register.placeOfBirth': 'Place of Birth',
    'register.mobileNumber': 'Mobile Number',
    'register.emailAddress': 'Email Address',
    'register.sendingOtp': 'Sending OTP…',
    'register.submit': 'Submit',
    'register.fillNameMobile': 'Please fill in at least your Name and Mobile Number.',
    'register.validMobile': 'Please enter a valid 10-digit mobile number.',
    'register.accountExists': 'Account Already Exists',
    'register.accountExistsMsg': 'An account already exists for this number. Please log in instead.',
    'register.cameraPermTitle': 'Camera Permission',
    'register.cameraPermMsg': 'This app needs access to your camera',
    'register.askLater': 'Ask Me Later',

    // Email OTP screen
    'emailOtp.sentToEmail': 'OTP sent to your Email',
    'emailOtp.loginFailed': 'Login Failed',
    'emailOtp.loginError': 'Login Error',
    'emailOtp.somethingWrong': 'Something went wrong. Please try again.',

    // User Profile screen
    'userProfile.personalInfo': 'Personal Info',
    'userProfile.palmHandPhoto': 'Palm/Hand Photo',
    'userProfile.removePhoto': 'Remove Photo',
    'userProfile.basicDetails': 'Basic Details',
    'userProfile.fullName': 'Full Name',
    'userProfile.mobileNumber': 'Mobile Number',
    'userProfile.emailAddress': 'Email Address',
    'userProfile.gender': 'Gender',
    'userProfile.married': 'Married',
    'userProfile.unmarried': 'Unmarried',
    'userProfile.maritalStatus': 'Marital Status',
    'userProfile.birthDetails': 'Birth Details',
    'userProfile.dateOfBirth': 'Date of Birth',
    'userProfile.timeOfBirth': 'Time of Birth',
    'userProfile.location': 'Location',
    'userProfile.cityPlaceOfBirth': 'City (Place of Birth)',
    'userProfile.state': 'State',
    'userProfile.enterField': 'Enter {{field}}',
    'userProfile.selectField': 'Select {{field}}',
    'userProfile.uploadPalmPhoto': 'Upload Palm Photo',
    'userProfile.palmPhotoInfo': 'Uploading a clear photo of your palm helps our astrologers provide more accurate palmistry readings.',
    'userProfile.noPhotoUploaded': 'No photo uploaded',
    'userProfile.saveChanges': 'Save Changes',
    'userProfile.removePhotoConfirm': 'Are you sure you want to remove this photo?',
    'userProfile.remove': 'Remove',
    'userProfile.validationError': 'Validation Error',
    'userProfile.uploadProfilePhoto': 'Please upload a Profile Photo.',
    'userProfile.enterFullName': 'Please enter your Full Name.',
    'userProfile.enterMobile': 'Please enter your Mobile Number.',
    'userProfile.emailEmpty': 'Email cannot be empty.',
    'userProfile.emailInvalid': 'Please enter a valid email address.',
    'userProfile.selectGender': 'Please select your Gender.',
    'userProfile.selectMaritalStatus': 'Please select your Marital Status.',
    'userProfile.selectDob': 'Please select your Date of Birth.',
    'userProfile.selectTob': 'Please select your Time of Birth.',
    'userProfile.enterCity': 'Please enter your City (Place of Birth).',
    'userProfile.selectState': 'Please select your State.',
    'userProfile.success': 'Success',
    'userProfile.updatedSuccessfully': 'Profile updated successfully!',
    'userProfile.updateError': 'Error updating profile',
    'userProfile.selectImage': 'Select Image',

    // My Sessions
    'session.chatSession': 'Chat Session',
    'session.audioCall': 'Audio Call',
    'session.videoCall': 'Video Call',
    'session.liveSession': 'Live Session',
    'session.tabChat': 'Chat',
    'session.tabLive': 'Live',
    'session.noneFound': 'No {{type}} found',
    'session.willAppear': 'Sessions will appear here after they end',
    'common.astrologer': 'Astrologer',
    'session.ref': 'Ref: {{id}}',
    'session.active': 'Active',
    'session.viewProfile': 'View Profile',
    'session.rate': 'Rate',
    'session.duration': 'Duration',
    'session.charged': 'Charged',
    'session.rateThisSession': 'Rate this session',
    'notifications.none': 'No new notifications',

    // Search screen
    'search.noAstrologerFound': 'No astrologer found',
    'search.mostSearched': 'Most searched on Astrowani',
    'search.tag.maritalLife': 'Marital Life',
    'search.tag.loveRelationship': 'Love & Relationship',
    'search.tag.careerJob': 'Career & Job',
    'search.tag.cheatingAffairs': 'Cheating & Affairs',
    'search.tag.financeBusiness': 'Finance & Business',
    'search.tag.breakupDivorce': 'Break-Up & Divorce',
    'search.tag.vedicAstrology': 'Vedic Astrology',
    'search.tag.psychicReading': 'Psychic Reading',
    'search.tag.tarotReading': 'Tarot Reading',
    'search.tag.numerology': 'Numerology',
    'search.tag.relationshipCounseling': 'Relationship Counseling',

    // Blog screen
    'blog.createdAt': 'Created At {{date}}',

    // Free Services — Panchang
    'panchang.enterLocation': 'Enter your location',
    'panchang.loading': 'Loading...',
    'panchang.title': 'Panchang',
    'panchang.additionalInfo': 'Additional Info',
    'panchang.auspiciousTime': 'Auspicious Time',
    'panchang.inauspiciousTime': 'Inauspicious Time',
    'panchang.vaara': 'Vaara',
    'panchang.nakshatra': 'Nakshatra',
    'panchang.tithi': 'Tithi',
    'panchang.karana': 'Karana',
    'panchang.yoga': 'Yoga',
    'panchang.sunrise': 'Sun Rise',
    'panchang.sunset': 'Sun Set',
    'panchang.moonrise': 'Moon Rise',
    'panchang.moonset': 'Moon Set',

    // Free Services — Janam Kundali
    'kundali.enterDetails': 'Enter Your Details',
    'kundali.enterFullName': 'Enter full Name',
    'kundali.selectGender': 'Select Gender',
    'kundali.selectDob': 'Select Date of Birth',
    'kundali.selectTob': 'Select Time of Birth',
    'kundali.dontKnow': "I don't know",
    'kundali.enterPlaceOfBirth': 'Enter Place of Birth',
    'kundali.showKundali': 'Show Kundali',
    'kundali.pleaseEnterName': 'Please enter your name',
    'kundali.pleaseSelectGender': 'Please select your gender',
    'kundali.pleaseSelectDob': 'Please select your date of birth',
    'kundali.pleaseSelectTob': 'Please select your time of birth or check "I don\'t know"',

    // Free Services — Kundali Match
    'match.boysDetails': "Boy's Details",
    'match.girlsDetails': "Girl's Details",
    'match.enterBoyPlace': "Enter Boy's Place of Birth",
    'match.enterGirlPlace': "Enter Girl's Place of Birth",
    'match.showReport': 'Show Report',
    'match.fillAllFields': 'Please fill in all required fields',
    'match.errorFetching': 'An error occurred while fetching the report. Please try again.',

    // Free Services — Horoscope
    'horoscope.title': '{{sign}} Horoscope',
    'horoscope.unableToFetch': 'Unable to fetch horoscope data. Please try again later.',
    'zodiac.aries': 'Aries',
    'zodiac.taurus': 'Taurus',
    'zodiac.gemini': 'Gemini',
    'zodiac.cancer': 'Cancer',
    'zodiac.leo': 'Leo',
    'zodiac.virgo': 'Virgo',
    'zodiac.libra': 'Libra',
    'zodiac.scorpio': 'Scorpio',
    'zodiac.sagittarius': 'Sagittarius',
    'zodiac.capricorn': 'Capricorn',
    'zodiac.aquarius': 'Aquarius',
    'zodiac.pisces': 'Pisces',

    // AstroServices shared
    'astro.notAvailable': 'Not available',
    'astro.notAvailableMsg': 'This report is not available right now. Please try again later.',
    'astro.reportCostsMsg': 'This report costs ₹{{price}}. Your wallet balance is ₹{{balance}}. Please recharge your wallet.',
    'astro.rechargeToView': 'Please recharge your wallet to get this report.',
    'astro.failedToGenerate': 'Failed to generate report',
    'astro.enterYourBirthDetails': 'Enter Your Birth Details',
    'astro.enterBirthDetails': 'Enter Birth Details',
    'astro.getKundliReport': 'Get Kundli Report',
    'astro.getDashaReport': 'Get Dasha Report',
    'astro.getDoshReport': 'Get Dosh Report',
    'astro.getLalKitabReport': 'Get Lal Kitab Report',
    'astro.getChartReport': 'Get Chart Report',
    'astro.getNumerologyReport': 'Get Numerology Report',
    'astro.getKPReport': 'Get KP Astrology Report',
    'astro.getTarotReading': 'Get Tarot Reading',
    'astro.getPdfReport': 'Get PDF Report',
    'astro.getMatchingReport': 'Get Matching Report',
    'astro.chooseChart': 'Choose Chart',
    'astro.selectAChart': 'Select a chart',
    'astro.getChart': 'Get Chart',
    'astro.matchKundli': 'Match Kundli',
    'astro.name': 'Enter Your Name',
    'astro.phoneNumber': 'Phone Number',
    'astro.getReading': 'Get Reading',
    'astro.selectTemplate': 'Select Report Type',
    'astro.pdfPlaceOfBirth': 'Place of Birth',
    'astro.enterMobileNumber': 'Enter mobile number',
    'astro.tarotTitle': 'Yes or No Tarot Reading',
    'astro.tarotSubtitle': 'Draw a card for a quick answer to your question.',
    'astro.drawCard': 'Draw a Card',
    'astro.yourReading': 'Your Reading',
    'astro.yourDetails': 'Your Details',
    'astro.chooseReport': 'Choose Report',
    'astro.selectPdfReport': 'Select a PDF report',
    'astro.generatePdfReport': 'Generate PDF Report',

    // Result screen section titles
    'result.kundliOverview': 'Kundli Overview',
    'result.ascendantReport': 'Ascendant Report',
    'result.planetDetails': 'Planet Details',
    'result.ashtakootMatching': 'Ashtakoot Matching',
    'result.dashakootMatching': 'Dashakoot Matching',
    'result.aggregateCompatibility': 'Aggregate Compatibility',
    'result.boysMangalDosh': "Boy's Mangal Dosh",
    'result.girlsMangalDosh': "Girl's Mangal Dosh",
    'result.currentMahadasha': 'Current Mahadasha',
    'result.mahadashaTimeline': 'Mahadasha Timeline',
    'result.yoginiDashaMain': 'Yogini Dasha (Main)',
    'result.yoginiDashaSub': 'Yogini Dasha (Sub)',
    'result.mangalDosh': 'Mangal Dosh',
    'result.kaalsarpDosh': 'Kaalsarp Dosh',
    'result.manglikDosh': 'Manglik Dosh',
    'result.pitraDosh': 'Pitra Dosh',
    'result.loshuGrid': 'Loshu Grid',
    'result.nameAnalysis': 'Name Analysis',
    'result.mobileAnalysis': 'Mobile Number Analysis',
    'result.luckyThings': 'Lucky Things',
    'result.personalYear': 'Personal Year',
    'result.lalKitabHoroscope': 'Lal Kitab Horoscope',
    'result.lalKitabDebts': 'Lal Kitab Debts',
    'result.lalKitabRemedies': 'Lal Kitab Remedies',
    'result.lalKitabHouses': 'Lal Kitab Houses',
    'result.lalKitabPlanets': 'Lal Kitab Planets',
    'result.cuspDetails': 'Cusp Details',
    'result.houseSignificators': 'House Significators',
    'result.reportReady': 'Your report is ready',
    'result.tapToViewDownload': 'Tap below to view or download your PDF report.',
    'result.viewReport': 'View Report',
  },
  Hindi: {
    // Home
    'home.welcome': 'एस्ट्रोवाणी में आपका स्वागत है!',
    'home.search': 'यहाँ खोजें',
    'home.bestAstrologers': 'भारत के सर्वश्रेष्ठ ज्योतिषी',
    'home.viewAll': 'सभी देखें',
    'home.remedies': 'एस्ट्रोवाणी के उपाय',
    'home.bookPuja': 'वीआईपी पूजा बुक करें',
    'home.buyGemstones': 'रत्न खरीदें',
    'home.readMore': 'और पढ़ें',
    'home.categories': 'एस्ट्रोवाणी की श्रेणियाँ',
    'home.liveAstrologers': 'लाइव ज्योतिषी',
    'home.freeServices': 'मुफ़्त सेवाएँ',
    'home.astroReports': 'ज्योतिष रिपोर्ट',
    'home.blog': 'एस्ट्रोवाणी ब्लॉग',
    'home.whatClientsSay': 'हमारे ग्राहक क्या कहते हैं',
    'home.discoverTrust': 'जानिए क्यों हज़ारों लोग एस्ट्रोवाणी पर भरोसा करते हैं',
    'home.whyBest': 'ज्योतिष के लिए एस्ट्रोवाणी सबसे बेहतर क्यों है?',
    'home.whyBestBody': 'एस्ट्रोवाणी उस नियति को उजागर करता है जो सितारों ने हमारे लिए तय की है। एस्ट्रोवाणी अपनी विधियों और सितारों व ग्रहों के पृथ्वी पर प्रभाव तथा मानव नियति की व्याख्या करने के तरीके के साथ एक सिद्ध विज्ञान है। घटनाओं की गणना और भविष्यवाणी की अपनी वैज्ञानिक पद्धति के साथ, एस्ट्रोवाणी लोगों को इस पर विश्वास करना शुरू करने के लिए पर्याप्त प्रमाणित करता है। और यह प्रारंभिक वैदिक काल से ही ऐसा करता आ रहा है।',
    'home.noReviews': 'अभी तक कोई समीक्षा उपलब्ध नहीं है।',
    'home.requestSent': 'अनुरोध भेजा गया',
    'home.waitingFor': '{{name}} के आपके अनुरोध को स्वीकार करने की प्रतीक्षा की जा रही है...',
    'home.cancelRequest': 'अनुरोध रद्द करें',
    'home.chatWithAstrologer': 'ज्योतिषी से चैट करें',
    'home.talkToAstrologer': 'ज्योतिषी से बात करें',

    // Common labels / actions
    'common.chat': 'चैट',
    'common.call': 'कॉल',
    'common.video': 'वीडियो',
    'common.noChat': 'चैट उपलब्ध नहीं',
    'common.noCall': 'कॉल उपलब्ध नहीं',
    'common.noVideo': 'वीडियो उपलब्ध नहीं',
    'common.offline': 'ऑफ़लाइन',
    'common.live': 'लाइव',
    'common.scheduled': 'निर्धारित',
    'common.home': 'होम',
    'common.wallet': 'वॉलेट',
    'common.profile': 'मेरी प्रोफ़ाइल',
    'common.cancel': 'रद्द करें',
    'common.ok': 'ठीक है',
    'common.error': 'त्रुटि',
    'common.language': 'भाषा चुनें',

    // Alerts
    'alerts.unavailable': 'अनुपलब्ध',
    'alerts.notAvailableChat': '{{name}} अभी चैट के लिए उपलब्ध नहीं है।',
    'alerts.notAvailableCall': '{{name}} अभी कॉल के लिए उपलब्ध नहीं है।',
    'alerts.notAvailableVideo': '{{name}} अभी वीडियो कॉल के लिए उपलब्ध नहीं है।',
    'alerts.astrologerOffline': '{{name}} अभी ऑफ़लाइन है। कृपया बाद में देखें।',
    'alerts.astrologerBusy': 'ज्योतिषी अभी व्यस्त हैं। कृपया कुछ समय बाद पुनः प्रयास करें।',
    'alerts.notPickedUpAudio': 'आपकी ऑडियो कॉल का जवाब नहीं दिया गया। कृपया बाद में पुनः प्रयास करें।',
    'alerts.notPickedUpVideo': 'आपकी वीडियो कॉल का जवाब नहीं दिया गया। कृपया बाद में पुनः प्रयास करें।',
    'alerts.insufficientBalance': 'अपर्याप्त बैलेंस',
    'alerts.failedWalletCheck': 'वॉलेट बैलेंस सत्यापित करने में विफल।',
    'alerts.failedRequestAstrologer': 'ज्योतिषी को अनुरोध भेजने में विफल।',
    'alerts.failedInitiateCall': 'कॉल शुरू करने में विफल',
    'alerts.failedInitiateVideoCall': 'वीडियो कॉल शुरू करने में विफल',

    // Drawer
    'drawer.myWallet': 'मेरा वॉलेट',
    'drawer.mySessions': 'मेरे सत्र',
    'drawer.remedies': 'उपाय',
    'drawer.chatWithAstrologer': 'ज्योतिषी से चैट करें',
    'drawer.blogs': 'एस्ट्रोवाणी ब्लॉग',
    'drawer.myFavorites': 'मेरे पसंदीदा',
    'drawer.myOrders': 'मेरे ऑर्डर',
    'drawer.voiceNotes': 'वॉइस नोट्स',
    'drawer.referFriend': 'मित्र को आमंत्रित करें',
    'drawer.settings': 'सेटिंग्स',
    'drawer.support': 'सहायता',
    'drawer.shareApp': 'ऐप शेयर करें',
    'drawer.logout': 'लॉग आउट',
    'drawer.connectWithUs': 'हमसे जुड़ें',
    'drawer.welcome': 'स्वागत है!',
    'drawer.updateProfile': 'अपनी प्रोफ़ाइल अपडेट करें',

    // Settings
    'settings.aboutUs': 'हमारे बारे में',
    'settings.faqs': 'सामान्य प्रश्न',
    'settings.refundCancellation': 'धनवापसी और रद्दीकरण',
    'settings.privacyPolicy': 'गोपनीयता नीति',
    'settings.termsOfUse': 'उपयोग की शर्तें',
    'settings.deleteAccount': 'मेरा खाता हटाएं',
    'settings.confirmLogoutTitle': 'लॉग आउट की पुष्टि करें',
    'settings.confirmLogoutMsg': 'क्या आप वाकई लॉग आउट करना चाहते हैं?',
    'settings.confirmDeleteTitle': 'हटाने की पुष्टि करें',
    'settings.confirmDeleteMsg': 'क्या आप वाकई अपना खाता हटाना चाहते हैं? एक बार हटाने के बाद, आपका सहेजा गया सारा इतिहास खो जाएगा। क्या आप फिर भी जारी रखना चाहते हैं?',
    'settings.deleteBtn': 'हटाएं',
    'settings.accountDeleted': 'खाता सफलतापूर्वक हटा दिया गया',
    'settings.loggedOut': 'सफलतापूर्वक लॉग आउट हो गया',

    // Login / OTP
    'login.tagline': 'सर्वश्रेष्ठ ज्योतिषियों की टीम',
    'login.discoverPath': 'अपना ब्रह्मांडीय पथ खोजें',
    'login.phoneNumber': 'फ़ोन नंबर',
    'login.continue': 'जारी रखें',
    'login.agreeTerms': 'साइन अप करके, आप हमारी ',
    'login.and': ' और ',
    'login.noAccount': 'खाता नहीं है? ',
    'login.register': 'पंजीकरण करें',
    'login.selectCountry': 'देश चुनें',
    'login.close': 'बंद करें',
    'login.validationError': 'सत्यापन त्रुटि',
    'login.phoneEmpty': 'फ़ोन नंबर खाली नहीं हो सकता।',
    'login.phoneTooShort': 'फ़ोन नंबर कम से कम 10 अंकों का होना चाहिए।',
    'login.otpFailed': 'OTP भेजा नहीं जा सका। कृपया पुनः प्रयास करें।',
    'login.noAccountTitle': 'खाता नहीं मिला',
    'login.noAccountMsg': 'हमें इस नंबर के लिए कोई खाता नहीं मिला। कृपया पहले साइन अप करें।',
    'login.somethingWrong': 'कुछ गलत हो गया। कृपया पुनः प्रयास करें।',

    // Remedies (static home tiles)
    'remedies.puja': 'पूजा',
    'remedies.gemstones': 'रत्न',
    'remedies.specificPuja': 'विशिष्ट पूजा',
    'remedies.lifeReports': 'जीवन रिपोर्ट',
    'remedies.buyNow': 'अभी खरीदें',

    'call.pleaseLogin': 'जारी रखने के लिए कृपया लॉगिन करें।',

    // ReusableList shared card
    'common.viewProfile': 'प्रोफ़ाइल',
    'common.free': 'मुफ़्त',
    'common.exp': 'अनुभव',
    'common.yrs': 'वर्ष',
    'common.searchAstrologer': 'नाम या कौशल से ज्योतिषी खोजें...',
    'alerts.failedGenerateRoom': 'कॉल रूम बनाने में विफल।',
    'alerts.declined': 'अस्वीकृत',
    'alerts.declinedBusy': '{{name}} अभी व्यस्त हैं और उन्होंने कॉल अस्वीकार कर दी।',
    'video.waitingFor': '{{name}} के आपकी वीडियो कॉल स्वीकार करने की प्रतीक्षा की जा रही है...',

    // Chat request hook
    'chat.pleaseLogIn': 'कृपया पहले लॉग इन करें।',
    'chat.sessionInvalid': 'सत्र अमान्य है। कृपया लॉग आउट करें और पुनः लॉग इन करें।',
    'chat.astrologerInfoMissing': 'ज्योतिषी की जानकारी गायब है। कृपया ताज़ा करें और पुनः प्रयास करें।',
    'chat.lowBalance': 'कम बैलेंस',
    'chat.lowBalanceMsg': 'चैट शुरू करने के लिए आपको कम से कम ₹{{charge}} चाहिए। कृपया अपना वॉलेट रीचार्ज करें।',
    'chat.couldNotSendRequest': 'अनुरोध नहीं भेजा जा सका: {{msg}}',
    'chat.notPickedUp': 'आपके चैट अनुरोध का जवाब नहीं दिया गया। कृपया बाद में पुनः प्रयास करें।',
    'status.astrologerBusyTitle': 'ज्योतिषी व्यस्त हैं',
    'status.notAnsweredTitle': 'कोई जवाब नहीं',

    // Live tab
    'live.watching': 'देख रहे हैं',
    'live.joinNow': 'अभी जुड़ें',
    'live.searchPlaceholder': 'लाइव सत्र खोजें...',
    'live.noneLive': 'अभी कोई ज्योतिषी लाइव नहीं है।',

    // AstrologerInfo profile screen
    'profile.new': 'नया',
    'profile.yrs': 'वर्ष',
    'profile.gift': 'उपहार',
    'profile.off': 'बंद',
    'profile.specialization': 'विशेषज्ञता',
    'profile.aboutServices': 'मेरी सेवाओं के बारे में',
    'profile.aboutFallback': 'अनुभवी और पेशेवर ज्योतिषी जो आपकी जीवन यात्रा में मार्गदर्शन के लिए यहाँ हैं।',
    'profile.readLess': 'कम पढ़ें',
    'profile.experienceQualification': 'अनुभव और योग्यता',
    'profile.experienceBody': 'कई वर्षों के समर्पित अभ्यास के साथ, मैंने {{specialties}} में अपने कौशल को निखारा है।',
    'profile.clientReviews': 'ग्राहक समीक्षाएँ',
    'profile.reviewsOnAstrowani': 'एस्ट्रोवाणी पर {{count}} समीक्षाएँ',
    'profile.noReviewsYet': 'अभी तक कोई समीक्षा नहीं है।',
    'profile.showAll': 'सभी देखें',
    'profile.writeReview': '+ समीक्षा लिखें',
    'profile.astrowaniReplyPrefix': '↳ एस्ट्रोवाणी: ',

    // OTP screens
    'otp.sentToNumber': 'आपके नंबर पर OTP भेजा गया',
    'otp.expiresIn': 'OTP {{time}} में समाप्त होगा',
    'otp.verifyBtn': 'OTP सत्यापित करें',
    'otp.notReceived': 'OTP प्राप्त नहीं हुआ? ',
    'otp.resend': 'OTP पुनः भेजें',
    'otp.invalidTryAgain': 'अमान्य OTP। कृपया पुनः प्रयास करें।',
    'otp.failedVerify': 'OTP सत्यापित करने में विफल। कृपया पुनः प्रयास करें।',
    'otp.verifyTitle': 'अपना नंबर सत्यापित करें',
    'otp.enterCodeSentTo': '6 अंकों का कोड दर्ज करें जो भेजा गया ',
    'otp.yourNumber': 'आपके नंबर पर',
    'otp.almostThere': 'बस थोड़ा और!',
    'otp.resendIn': '{{time}} में OTP पुनः भेजें',
    'otp.sending': 'भेजा जा रहा है...',
    'otp.changeNumber': 'फ़ोन नंबर बदलें',
    'otp.invalidOtpTitle': 'अमान्य OTP',
    'otp.enterComplete': 'कृपया पूरा 6 अंकों का कोड दर्ज करें।',
    'otp.verificationFailed': 'सत्यापन विफल',
    'otp.otpSentTitle': 'OTP भेजा गया',
    'otp.newCodeSent': 'आपके नंबर पर एक नया कोड भेजा गया है।',
    'otp.couldNotResend': 'OTP पुनः नहीं भेजा जा सका।',
    'otp.couldNotResendRetry': 'OTP पुनः नहीं भेजा जा सका। कृपया पुनः प्रयास करें।',

    // About Us
    'about.tagline': 'सर्वश्रेष्ठ ज्योतिषियों की टीम',
    'about.title': 'हमारे बारे में',
    'about.p1': 'एस्ट्रोवाणी ज्योतिष के प्राचीन विज्ञान का आपका विश्वसनीय प्रवेशद्वार है, जो आधुनिक तकनीक की सुविधा के साथ प्रस्तुत किया गया है। हमारा मिशन व्यक्तिगत ज्योतिषीय मार्गदर्शन के माध्यम से आपको स्पष्टता, दिशा और मानसिक शांति खोजने में मदद करना है।',
    'about.p2': 'हम पूरे भारत से अत्यधिक अनुभवी और सत्यापित ज्योतिषियों की एक टीम के साथ काम करते हैं, जिनमें से प्रत्येक वैदिक ज्योतिष, अंकशास्त्र, हस्तरेखा विज्ञान, टैरो रीडिंग और अन्य में विशेषज्ञ हैं। चाहे आप करियर, रिश्तों, स्वास्थ्य या वित्त के बारे में जवाब खोज रहे हों, हमारे विशेषज्ञ करुणा और सटीकता के साथ आपका मार्गदर्शन करने के लिए यहाँ हैं।',
    'about.p3': 'एस्ट्रोवाणी में, हम मानते हैं कि ज्योतिष विनाश की भविष्यवाणी करने या आपके भाग्य को निर्धारित करने के बारे में नहीं है, बल्कि आपको सूचित निर्णय लेने के लिए सशक्त बनाने के बारे में है। हमारे परामर्श प्रामाणिकता, नैतिकता और गोपनीयता में निहित हैं, यह सुनिश्चित करते हुए कि आपका व्यक्तिगत विवरण और रीडिंग निजी रहें।',
    'about.p4': 'लाइव परामर्श, चैट सत्र और दैनिक राशिफल जैसी सुविधाओं के साथ, एस्ट्रोवाणी कभी भी, कहीं भी सही विशेषज्ञ से जुड़ना आसान बनाता है। चाहे आप विश्वासी हों या सिर्फ जिज्ञासु, हम आपका स्वागत करते हैं कि सितारों को क्या कहना है, यह जानने के लिए।',
    'about.p5': 'हजारों संतुष्ट उपयोगकर्ताओं में शामिल हों जिन्होंने एस्ट्रोवाणी के माध्यम से मार्गदर्शन, प्रेरणा और सकारात्मकता की खोज की है — जहाँ परंपरा भरोसे से मिलती है।',

    // FAQ
    'faq.title': 'अक्सर पूछे जाने वाले प्रश्न',
    'faq.q1': 'मैं एक ज्योतिषी से चैट करना चाहता हूँ। मैं कैसे शुरू करूँ?',
    'faq.a1': 'ज्योतिषी से चैट करने के लिए, आपको बस अपने एस्ट्रोवाणी खाते में लॉगिन करना है या खाता बनाने के लिए साइन अप करना है, अपने वॉलेट में पैसे जोड़ने हैं, और फिर बस उस ज्योतिषी को चुनें जिससे आप चैट करना चाहते हैं और अपना सत्र शुरू करें।',
    'faq.q2': 'क्या ज्योतिषी से परामर्श शुरू करने से पहले न्यूनतम बैलेंस की कोई आवश्यकता है?',
    'faq.a2': 'एस्ट्रोवाणी पर ज्योतिषी से परामर्श शुरू करने के लिए आपके पास कम से कम $10 का बैलेंस होना चाहिए।',
    'faq.q3': 'क्या ज्योतिषी सत्यापित हैं?',
    'faq.a3': 'हाँ, एस्ट्रोवाणी पर सभी ज्योतिषी वर्षों के अनुभव वाले सत्यापित पेशेवर हैं।',
    'faq.q4': 'अगर चैट के बीच मुझे फ़ोन कॉल आती है, तो क्या यह मेरा सत्र स्वतः समाप्त कर देगा?',
    'faq.a4': 'नहीं, फ़ोन कॉल आने पर आपका सत्र स्वतः समाप्त नहीं होगा। चैट रुक जाएगी, और कॉल समाप्त होने के बाद आप फिर से शुरू कर सकते हैं।',

    // Wallet
    'wallet.invalidAmount': 'अमान्य राशि',
    'wallet.enterValidAmount': 'कृपया रीचार्ज करने के लिए एक मान्य राशि दर्ज करें।',
    'wallet.paymentSuccessful': 'भुगतान सफल',
    'wallet.paymentId': 'भुगतान आईडी: {{id}}',
    'wallet.paymentFailed': 'भुगतान विफल',
    'wallet.addMoney': 'वॉलेट में पैसे जोड़ें',
    'wallet.rechargeSubtitle': 'विशेषज्ञों से बात करने के लिए आसानी से रीचार्ज करें',
    'wallet.enterAmount': 'राशि दर्ज करें',
    'wallet.recommendedAmounts': 'अनुशंसित राशियाँ',
    'wallet.totalPayable': 'कुल देय राशि',
    'wallet.proceedToPay': 'भुगतान करने के लिए आगे बढ़ें',

    // Register screen
    'register.title': 'पंजीकरण',
    'register.tapToAddPhoto': 'फ़ोटो जोड़ने के लिए टैप करें',
    'register.fullName': 'पूरा नाम',
    'register.male': 'पुरुष',
    'register.female': 'महिला',
    'register.other': 'अन्य',
    'register.selectGender': 'लिंग चुनें',
    'register.placeOfBirth': 'जन्म स्थान',
    'register.mobileNumber': 'मोबाइल नंबर',
    'register.emailAddress': 'ईमेल पता',
    'register.sendingOtp': 'OTP भेजा जा रहा है…',
    'register.submit': 'जमा करें',
    'register.fillNameMobile': 'कृपया कम से कम अपना नाम और मोबाइल नंबर भरें।',
    'register.validMobile': 'कृपया एक मान्य 10 अंकों का मोबाइल नंबर दर्ज करें।',
    'register.accountExists': 'खाता पहले से मौजूद है',
    'register.accountExistsMsg': 'इस नंबर के लिए पहले से एक खाता मौजूद है। कृपया इसके बजाय लॉग इन करें।',
    'register.cameraPermTitle': 'कैमरा अनुमति',
    'register.cameraPermMsg': 'इस ऐप को आपके कैमरे तक पहुंच की आवश्यकता है',
    'register.askLater': 'मुझसे बाद में पूछें',

    // Email OTP screen
    'emailOtp.sentToEmail': 'आपके ईमेल पर OTP भेजा गया',
    'emailOtp.loginFailed': 'लॉगिन विफल',
    'emailOtp.loginError': 'लॉगिन त्रुटि',
    'emailOtp.somethingWrong': 'कुछ गलत हो गया। कृपया पुनः प्रयास करें।',

    // User Profile screen
    'userProfile.personalInfo': 'व्यक्तिगत जानकारी',
    'userProfile.palmHandPhoto': 'हथेली/हाथ की फ़ोटो',
    'userProfile.removePhoto': 'फ़ोटो हटाएं',
    'userProfile.basicDetails': 'बुनियादी जानकारी',
    'userProfile.fullName': 'पूरा नाम',
    'userProfile.mobileNumber': 'मोबाइल नंबर',
    'userProfile.emailAddress': 'ईमेल पता',
    'userProfile.gender': 'लिंग',
    'userProfile.married': 'विवाहित',
    'userProfile.unmarried': 'अविवाहित',
    'userProfile.maritalStatus': 'वैवाहिक स्थिति',
    'userProfile.birthDetails': 'जन्म विवरण',
    'userProfile.dateOfBirth': 'जन्म तिथि',
    'userProfile.timeOfBirth': 'जन्म समय',
    'userProfile.location': 'स्थान',
    'userProfile.cityPlaceOfBirth': 'शहर (जन्म स्थान)',
    'userProfile.state': 'राज्य',
    'userProfile.enterField': '{{field}} दर्ज करें',
    'userProfile.selectField': '{{field}} चुनें',
    'userProfile.uploadPalmPhoto': 'हथेली की फ़ोटो अपलोड करें',
    'userProfile.palmPhotoInfo': 'अपनी हथेली की स्पष्ट फ़ोटो अपलोड करने से हमारे ज्योतिषियों को अधिक सटीक हस्तरेखा पठन प्रदान करने में मदद मिलती है।',
    'userProfile.noPhotoUploaded': 'कोई फ़ोटो अपलोड नहीं की गई',
    'userProfile.saveChanges': 'बदलाव सहेजें',
    'userProfile.removePhotoConfirm': 'क्या आप वाकई इस फ़ोटो को हटाना चाहते हैं?',
    'userProfile.remove': 'हटाएं',
    'userProfile.validationError': 'सत्यापन त्रुटि',
    'userProfile.uploadProfilePhoto': 'कृपया एक प्रोफ़ाइल फ़ोटो अपलोड करें।',
    'userProfile.enterFullName': 'कृपया अपना पूरा नाम दर्ज करें।',
    'userProfile.enterMobile': 'कृपया अपना मोबाइल नंबर दर्ज करें।',
    'userProfile.emailEmpty': 'ईमेल खाली नहीं हो सकता।',
    'userProfile.emailInvalid': 'कृपया एक मान्य ईमेल पता दर्ज करें।',
    'userProfile.selectGender': 'कृपया अपना लिंग चुनें।',
    'userProfile.selectMaritalStatus': 'कृपया अपनी वैवाहिक स्थिति चुनें।',
    'userProfile.selectDob': 'कृपया अपनी जन्म तिथि चुनें।',
    'userProfile.selectTob': 'कृपया अपना जन्म समय चुनें।',
    'userProfile.enterCity': 'कृपया अपना शहर (जन्म स्थान) दर्ज करें।',
    'userProfile.selectState': 'कृपया अपना राज्य चुनें।',
    'userProfile.success': 'सफलता',
    'userProfile.updatedSuccessfully': 'प्रोफ़ाइल सफलतापूर्वक अपडेट हो गई!',
    'userProfile.updateError': 'प्रोफ़ाइल अपडेट करने में त्रुटि',
    'userProfile.selectImage': 'छवि चुनें',

    // My Sessions
    'session.chatSession': 'चैट सत्र',
    'session.audioCall': 'ऑडियो कॉल',
    'session.videoCall': 'वीडियो कॉल',
    'session.liveSession': 'लाइव सत्र',
    'session.tabChat': 'चैट',
    'session.tabLive': 'लाइव',
    'session.noneFound': 'कोई {{type}} नहीं मिला',
    'session.willAppear': 'सत्र समाप्त होने के बाद यहाँ दिखाई देंगे',
    'common.astrologer': 'ज्योतिषी',
    'session.ref': 'संदर्भ: {{id}}',
    'session.active': 'सक्रिय',
    'session.viewProfile': 'प्रोफ़ाइल देखें',
    'session.rate': 'दर',
    'session.duration': 'अवधि',
    'session.charged': 'शुल्क लिया गया',
    'session.rateThisSession': 'इस सत्र को रेट करें',
    'notifications.none': 'कोई नई सूचना नहीं',

    // Search screen
    'search.noAstrologerFound': 'कोई ज्योतिषी नहीं मिला',
    'search.mostSearched': 'एस्ट्रोवाणी पर सबसे ज़्यादा खोजा गया',
    'search.tag.maritalLife': 'वैवाहिक जीवन',
    'search.tag.loveRelationship': 'प्रेम और रिश्ते',
    'search.tag.careerJob': 'करियर और नौकरी',
    'search.tag.cheatingAffairs': 'धोखा और अफेयर',
    'search.tag.financeBusiness': 'वित्त और व्यवसाय',
    'search.tag.breakupDivorce': 'ब्रेकअप और तलाक',
    'search.tag.vedicAstrology': 'वैदिक ज्योतिष',
    'search.tag.psychicReading': 'साइकिक रीडिंग',
    'search.tag.tarotReading': 'टैरो रीडिंग',
    'search.tag.numerology': 'अंकशास्त्र',
    'search.tag.relationshipCounseling': 'रिश्ते परामर्श',

    // Blog screen
    'blog.createdAt': '{{date}} को बनाया गया',

    // Free Services — Panchang
    'panchang.enterLocation': 'अपना स्थान दर्ज करें',
    'panchang.loading': 'लोड हो रहा है...',
    'panchang.title': 'पंचांग',
    'panchang.additionalInfo': 'अतिरिक्त जानकारी',
    'panchang.auspiciousTime': 'शुभ समय',
    'panchang.inauspiciousTime': 'अशुभ समय',
    'panchang.vaara': 'वार',
    'panchang.nakshatra': 'नक्षत्र',
    'panchang.tithi': 'तिथि',
    'panchang.karana': 'करण',
    'panchang.yoga': 'योग',
    'panchang.sunrise': 'सूर्योदय',
    'panchang.sunset': 'सूर्यास्त',
    'panchang.moonrise': 'चंद्रोदय',
    'panchang.moonset': 'चंद्रास्त',

    // Free Services — Janam Kundali
    'kundali.enterDetails': 'अपना विवरण दर्ज करें',
    'kundali.enterFullName': 'पूरा नाम दर्ज करें',
    'kundali.selectGender': 'लिंग चुनें',
    'kundali.selectDob': 'जन्म तिथि चुनें',
    'kundali.selectTob': 'जन्म समय चुनें',
    'kundali.dontKnow': 'मुझे नहीं पता',
    'kundali.enterPlaceOfBirth': 'जन्म स्थान दर्ज करें',
    'kundali.showKundali': 'कुंडली दिखाएं',
    'kundali.pleaseEnterName': 'कृपया अपना नाम दर्ज करें',
    'kundali.pleaseSelectGender': 'कृपया अपना लिंग चुनें',
    'kundali.pleaseSelectDob': 'कृपया अपनी जन्म तिथि चुनें',
    'kundali.pleaseSelectTob': 'कृपया अपना जन्म समय चुनें या "मुझे नहीं पता" चुनें',

    // Free Services — Kundali Match
    'match.boysDetails': 'लड़के का विवरण',
    'match.girlsDetails': 'लड़की का विवरण',
    'match.enterBoyPlace': 'लड़के का जन्म स्थान दर्ज करें',
    'match.enterGirlPlace': 'लड़की का जन्म स्थान दर्ज करें',
    'match.showReport': 'रिपोर्ट दिखाएं',
    'match.fillAllFields': 'कृपया सभी आवश्यक फ़ील्ड भरें',
    'match.errorFetching': 'रिपोर्ट प्राप्त करते समय एक त्रुटि हुई। कृपया पुनः प्रयास करें।',

    // Free Services — Horoscope
    'horoscope.title': '{{sign}} राशिफल',
    'horoscope.unableToFetch': 'राशिफल डेटा प्राप्त करने में असमर्थ। कृपया बाद में पुनः प्रयास करें।',
    'zodiac.aries': 'मेष',
    'zodiac.taurus': 'वृषभ',
    'zodiac.gemini': 'मिथुन',
    'zodiac.cancer': 'कर्क',
    'zodiac.leo': 'सिंह',
    'zodiac.virgo': 'कन्या',
    'zodiac.libra': 'तुला',
    'zodiac.scorpio': 'वृश्चिक',
    'zodiac.sagittarius': 'धनु',
    'zodiac.capricorn': 'मकर',
    'zodiac.aquarius': 'कुंभ',
    'zodiac.pisces': 'मीन',

    // AstroServices shared
    'astro.notAvailable': 'अनुपलब्ध',
    'astro.notAvailableMsg': 'यह रिपोर्ट अभी उपलब्ध नहीं है। कृपया बाद में पुनः प्रयास करें।',
    'astro.reportCostsMsg': 'इस रिपोर्ट की कीमत ₹{{price}} है। आपका वॉलेट बैलेंस ₹{{balance}} है। कृपया अपना वॉलेट रीचार्ज करें।',
    'astro.rechargeToView': 'यह रिपोर्ट प्राप्त करने के लिए कृपया अपना वॉलेट रीचार्ज करें।',
    'astro.failedToGenerate': 'रिपोर्ट बनाने में विफल',
    'astro.enterYourBirthDetails': 'अपना जन्म विवरण दर्ज करें',
    'astro.enterBirthDetails': 'जन्म विवरण दर्ज करें',
    'astro.getKundliReport': 'कुंडली रिपोर्ट प्राप्त करें',
    'astro.getDashaReport': 'दशा रिपोर्ट प्राप्त करें',
    'astro.getDoshReport': 'दोष रिपोर्ट प्राप्त करें',
    'astro.getLalKitabReport': 'लाल किताब रिपोर्ट प्राप्त करें',
    'astro.getChartReport': 'चार्ट रिपोर्ट प्राप्त करें',
    'astro.getNumerologyReport': 'अंकशास्त्र रिपोर्ट प्राप्त करें',
    'astro.getKPReport': 'केपी ज्योतिष रिपोर्ट प्राप्त करें',
    'astro.getTarotReading': 'टैरो रीडिंग प्राप्त करें',
    'astro.getPdfReport': 'पीडीएफ रिपोर्ट प्राप्त करें',
    'astro.getMatchingReport': 'मिलान रिपोर्ट प्राप्त करें',
    'astro.chooseChart': 'चार्ट चुनें',
    'astro.selectAChart': 'एक चार्ट चुनें',
    'astro.getChart': 'चार्ट प्राप्त करें',
    'astro.matchKundli': 'कुंडली मिलान करें',
    'astro.name': 'अपना नाम दर्ज करें',
    'astro.phoneNumber': 'फ़ोन नंबर',
    'astro.getReading': 'रीडिंग प्राप्त करें',
    'astro.selectTemplate': 'रिपोर्ट का प्रकार चुनें',
    'astro.pdfPlaceOfBirth': 'जन्म स्थान',
    'astro.enterMobileNumber': 'मोबाइल नंबर दर्ज करें',
    'astro.tarotTitle': 'हाँ या नहीं टैरो रीडिंग',
    'astro.tarotSubtitle': 'अपने प्रश्न का त्वरित उत्तर पाने के लिए एक कार्ड निकालें।',
    'astro.drawCard': 'कार्ड निकालें',
    'astro.yourReading': 'आपकी रीडिंग',
    'astro.yourDetails': 'आपका विवरण',
    'astro.chooseReport': 'रिपोर्ट चुनें',
    'astro.selectPdfReport': 'एक पीडीएफ रिपोर्ट चुनें',
    'astro.generatePdfReport': 'पीडीएफ रिपोर्ट बनाएं',

    // Result screen section titles
    'result.kundliOverview': 'कुंडली अवलोकन',
    'result.ascendantReport': 'लग्न रिपोर्ट',
    'result.planetDetails': 'ग्रह विवरण',
    'result.ashtakootMatching': 'अष्टकूट मिलान',
    'result.dashakootMatching': 'दशकूट मिलान',
    'result.aggregateCompatibility': 'समग्र अनुकूलता',
    'result.boysMangalDosh': 'लड़के का मंगल दोष',
    'result.girlsMangalDosh': 'लड़की का मंगल दोष',
    'result.currentMahadasha': 'वर्तमान महादशा',
    'result.mahadashaTimeline': 'महादशा समयरेखा',
    'result.yoginiDashaMain': 'योगिनी दशा (मुख्य)',
    'result.yoginiDashaSub': 'योगिनी दशा (उप)',
    'result.mangalDosh': 'मंगल दोष',
    'result.kaalsarpDosh': 'कालसर्प दोष',
    'result.manglikDosh': 'मांगलिक दोष',
    'result.pitraDosh': 'पितृ दोष',
    'result.loshuGrid': 'लोशु ग्रिड',
    'result.nameAnalysis': 'नाम विश्लेषण',
    'result.mobileAnalysis': 'मोबाइल नंबर विश्लेषण',
    'result.luckyThings': 'भाग्यशाली चीज़ें',
    'result.personalYear': 'व्यक्तिगत वर्ष',
    'result.lalKitabHoroscope': 'लाल किताब राशिफल',
    'result.lalKitabDebts': 'लाल किताब ऋण',
    'result.lalKitabRemedies': 'लाल किताब उपाय',
    'result.lalKitabHouses': 'लाल किताब भाव',
    'result.lalKitabPlanets': 'लाल किताब ग्रह',
    'result.cuspDetails': 'कस्प विवरण',
    'result.houseSignificators': 'भाव संकेतक',
    'result.reportReady': 'आपकी रिपोर्ट तैयार है',
    'result.tapToViewDownload': 'अपनी पीडीएफ रिपोर्ट देखने या डाउनलोड करने के लिए नीचे टैप करें।',
    'result.viewReport': 'रिपोर्ट देखें',
  },
};

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('English');

  useEffect(() => {
    const loadLanguage = async () => {
      try {
        const savedLang = await AsyncStorage.getItem('appLanguage');
        if (savedLang) {
          setLanguage(savedLang);
        }
      } catch (error) {
        console.log('Error loading language', error);
      }
    };
    loadLanguage();
  }, []);

  const changeLanguage = async (lang) => {
    setLanguage(lang);
    try {
      await AsyncStorage.setItem('appLanguage', lang);
    } catch (error) {
      console.log('Error saving language', error);
    }
  };

  // t('home.waitingFor', { name: 'Ramesh' }) → replaces {{name}} in the resolved string.
  const t = (key, params) => {
    let str = translations[language]?.[key] ?? translations['English'][key] ?? key;
    if (params) {
      Object.keys(params).forEach(p => {
        str = str.replace(new RegExp(`{{${p}}}`, 'g'), params[p]);
      });
    }
    return str;
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
